### ISSUE TITLE
TypeError: position is undefined

### ISSUE THREAD

**Issue by lopinsjk** [stevenwanderski/bxslider-4#10]
I have a strange issue:

I create a script.js like this:

```
  $(document).ready(function(){

$('.bxslider').bxSlider({
    pager: false,
    mode: 'fade',
    auto: true,
    autoHover: true
});

$('.depliant').bxSlider({
    pager: false
});

$('.bxcarousel').bxSlider({
    pager: false,
    minSlides: 2,
    maxSlides: 3,
    slideWidth: 155,
    slideMargin: 20
});

$('.bx_preview_slider').bxSlider({
    pagerCustom: '#bx-pager',
});

  });
```

I use two slideshow, one carousel and one thumb. If I insert only thumbnail pager into my page there is an error on jquery.bxslider.js, line 380: TypeError: position is undefined. In this page I have only the thumbnail pager. If I delete slideWidth and slideMargin from .bxcarousel into script.js it is work.

Can you help me? Thank you in advance.

**Comment by ircphp** [comment]
What is setPositionProperty() function?
