### ISSUE TITLE
how to load html content

### ISSUE THREAD

**Issue by keden6309** [stevenwanderski/bxslider-4#1017]
is there a way to specify an html page to load, or  a file containing html?  I've gotten it to work with images, and hard coded html in a list.
thanks

**Comment by keden6309** [comment]
never mind, found it.

**Comment by pkshefi** [comment]
you need a local hosting software my pleasure sir thank you

On Mon, Jun 6, 2016 at 8:59 PM, keden6309 <notifications@github.com> wrote:

> never mind, found it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/stevenwanderski/bxslider-4/issues/1017#issuecomment-223994517>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARfw6K2DiHXi2NGCXbIWniwfi5-BxrLfks5qJDzkgaJpZM4Iu8ko>
> .
>



-- 
With Regards.

Mohammed Shafeeq.PK
