### ISSUE TITLE
fade mode bug > same slide and onSlideAfter not working

### ISSUE THREAD

**Issue by MWDavidH** [stevenwanderski/bxslider-4#1021]
Hi,

everythink is working nice with `mode: 'horizontal'`, but when mode is set to "fade" and after clicking many times, the slide is still the same and the "onSlideAfter " callback doesn't work.
Here is my settings and a JsFiddle link : 

https://jsfiddle.net/gamedware/Lupcs8mv/9/

``` js
var $xlslider = $('#xl-slider .bxslider').bxSlider({
     mode: 'fade',
     pager: 0,
     auto: 1,
     speed: 1500,
     pause: 5000,                
     onSlideAfter: function($slideElement) {                    
        $('.xlso-item').removeClass('active');
        $($slideElement).find('.xlso-item').addClass('active');
   }
});
```

**Comment by sn3ka** [comment]
Hi,

I guess this is the result you were looking for:

https://jsfiddle.net/Lupcs8mv/55/

**Comment by MWDavidH** [comment]
Hi thanks a lot !

After many times sometimes or when you **click quickly many times on next/prev arrows** I still have a bug, the fade animation is strange and the callback doesn't appear. But it is better than my first jsFiddle ;)

**Comment by sn3ka** [comment]
Hey,
This can be caused but the css transition that takes more time to execute than your fast clicks.
Also you could check this fix for BxSlider about fast ans repetitive clicks:
https://github.com/stevenwanderski/bxslider-4/issues/998

Give it a try. Cheerz

**Comment by MWDavidH** [comment]
I think I will hide controls 'onSlideBefore' and show it 'onSlideAfter'

**Comment by Libida** [comment]
@MWDavidH ,
thanks for your solution. 

Also instead of hide/show, it's possible to add/remove class with pointer-events: none.

**Comment by MWDavidH** [comment]
@Libida yes, I did not think about it !
