### ISSUE TITLE
Old download link on official site

### ISSUE THREAD

**Issue by SeregaSpaceApp** [stevenwanderski/bxslider-4#1040]
At http://bxslider.com the button "Download" at top right corner links to very old version of year 2014.

**Comment by ildarkhasanshin** [comment]
must be https://github.com/stevenwanderski/bxslider-4/archive/master.zip

**Comment by viktorbijlenga** [comment]
@stevenwanderski This would be a good thing to solve straight away.

**Comment by stevenwanderski** [comment]
The doc site now has the latest version (v4.2.7). I am currently making changes to the site that will auto-deploy each new version.
