### ISSUE TITLE
have prev/next manual controls and also be able to click on an image for next slide

### ISSUE THREAD

**Issue by katiabudnik** [stevenwanderski/bxslider-4#1044]
I want to have control selectors Prev/Next and also be able to click on an image for next or previous slide.
I noticed that now I can have either one or another option.
when I added this code:

 $('.bxslider1').bxSlider({
  		mode: 'fade',
		pager: true,
		pagerType: 'short',
		nextSelector: '#slider-next1',
	    prevSelector: '#slider-prev1',
	    nextText: 'Prev/',
	    prevText: 'Next'
	  });
an option to press an image for next slide disappeared. 

am I missing something?

thank you for your help

**Comment by katiabudnik** [comment]
solved

**Comment by Walkeezy** [comment]
Mind telling us how?
