### ISSUE TITLE
Rectangular boxes appear on Chrome Android

### ISSUE THREAD

**Issue by elektray** [stevenwanderski/bxslider-4#1063]
Chrome for Android displays black boxes with a cross on the `<ul>` item of the slider. There is a box for each `<li>` item.  [See here](https://i.stack.imgur.com/S7T2j.png)

Does anyone knows why this is happening?

Thanks

**Comment by polat** [comment]
Could it be pager?

`pager: false;`
Would you try it?

**Comment by sn3ka** [comment]
Hello,

why don't you try to hide them with a css class 
`.bx-pager-item {display:none;}`

**Comment by elektray** [comment]
Hi guys,

thanks for the tips. After a bit of debugging I have come to the conclusion that this issue is not with bxslider but some other part of my code. Thanks anyway!
