### ISSUE TITLE
node version dependency

### ISSUE THREAD

**Issue by sweetroll** [stevenwanderski/bxslider-4#1064]
Any issue with bumping the node version requirements up to the current LTS version? The current "~0.10.28" rule prevents it from being installed by yarn on a more current version of node.

**Comment by jeroendesloovere** [comment]
I'm having the same problem.
`yarn add bxslider` throws the error that `node@~0.10.28` version is expected.

`npm install bxslider` works, but I need to use yarn...

Can you guys please look at this and fix it? Thanks.

**Comment by jeroendesloovere** [comment]
Seems like this PR https://github.com/stevenwanderski/bxslider-4/pull/1058 provides some workarounds.

**Comment by dasanra** [comment]
This issue is solved in version 4.2.10
