### ISSUE TITLE
Is possible add a current number of slider?

### ISSUE THREAD

**Issue by ajgbcool** [stevenwanderski/bxslider-4#1066]
First, I don't know too much Javascript, but I'am learning and need to know for a project get the current slider (and change every time) and get the total slider in this format: 1/3

Example: 
first slide: 1/3
second slide: 2/3
third slide: 3/3
and loop.

Thanks a lot!

**Comment by sn3ka** [comment]
Hello,

just add the pager option in your code:
pager: true,
pagerType: 'short'

you will have a pager in the requested format.
