### ISSUE TITLE
The full source codes of examples in jquery.bxslider.zip

### ISSUE THREAD

**Issue by emitsuco3** [stevenwanderski/bxslider-4#1068]
To try bxSlider, I downloaded it from the top page of bxSlider, and tried to use it according to "How to install". But I don't know where to place it, what to be required. So I could not understand its behavior.

Also, I tried "Image gallery with captions" on the example pages, but I could not for the same reason.

Therefore, I think that the beginners can try bxSlider quickly if the full source codes of examples are included in `jquery.bxslider.zip`.

**Comment by sn3ka** [comment]
Hello,

in the head of your html page you have to include jQuery, BxSlider js and the css.
```
<html>
<head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="/your/path/to/js/jquery.bxslider.min.js"></script>
<link href="/your/path/to/lib/jquery.bxslider.css" rel="stylesheet" />
</head>
```

then in the body of your page the markup:

```
<body>
<ul class="bxslider">
  <li><img src="http://placehold.it/350x150"></li>
  <li><img src="http://placehold.it/350x150"></li>
  <li><img src="http://placehold.it/350x150"></li>
  <li><img src="http://placehold.it/350x150"></li>
</ul>
```

and finally call the slider:

```
$(document).ready(function(){
  $('.bxslider').bxSlider();
});
</body>
</html>

Hope it helps.
```

**Comment by emitsuco3** [comment]
@sn3ka 
Thank you for telling me such a wonderful thing.
I appreciate your kindness.
