### ISSUE TITLE
Showing current slide number, but start from '1' rather than '0'

### ISSUE THREAD

**Issue by matthewjrallen** [stevenwanderski/bxslider-4#1071]
I want to add a slide count and have got it working but the issue is the current slide number starts from '0' instead of '1'. Is there any way to change that.

This is my code so far

`onSlideAfter: function() { $('.slide-number').text(site.activeSlider.getCurrentSlide() + ' / ' + site.activeSlider.getSlideCount()); }`

which shows almost right on the website: 0 / 4

**Comment by sn3ka** [comment]
hello,

can you try this ?

`onSlideAfter: function($slideElement, oldIndex, newIndex) { $('.slide-number').text(newIndex+1 + ' / ' + site.activeSlider.getSlideCount()); }`

**Comment by matthewjrallen** [comment]
Thanks, that worked!
