### ISSUE TITLE
Has BxSlider development ended?

### ISSUE THREAD

**Issue by viktorbijlenga** [stevenwanderski/bxslider-4#1076]
Dear BxSlider,

Is this project currently maintained or has development of BxSlider ended? At the moment there are 53 pull request waiting for review and 300+ issues.

There seems to be a good community around the slider, can we as a community help out with the development in any way?

Or is it time to start looking for an alternative solution for sliders?

**Comment by sekmenhuseyin** [comment]
i fixed some issues: https://github.com/sekmenhuseyin/bxslider-4
you can use this one,

**Comment by Jaxel** [comment]
@sekmenhuseyin 

I'm liking your version. Is there a chance I can get you to add a public method for when the auto rotate status changes? Like when the pause/play buttons are pressed? Something along the lines of `onAutoChange`?

    default: function(){}
    options: function(state){ // your code here }
    arguments:
      state: the new state of "auto": boolean (true / false)

**Comment by sekmenhuseyin** [comment]
of course, right away

**Comment by Anjing1993** [comment]
@sekmenhuseyin  
Hi,I user your code of bxslider-4,but the pictures of page will flicker while refreshing the page.
How do I solve?

**Comment by sekmenhuseyin** [comment]
@Anjing1993 do you have an address that we can see?

**Comment by viktorbijlenga** [comment]
Please stay on topic here.

**Comment by stevenwanderski** [comment]
@viktorbijlenga Unfortunately I have stopped active development on bxslider-4 but would love to keep the plugin alive as it has an amazing and lovely community. Any suggestions on starting the process of finding a maintainer?

**Comment by viktorbijlenga** [comment]
Thank you so much for your work with bxslider Steven. I've had so much use of it during the last few years. You will always have a good friend in Sweden 👏👏

I saw that you opened a new issue for the search of a new maintainer, so I think we can close this and continue the discussion over there.

**Comment by viktorbijlenga** [comment]
See Issue #1095
