### ISSUE TITLE
Prev / Next buttons fail when two sliders on same page

### ISSUE THREAD

**Issue by compumatter** [stevenwanderski/bxslider-4#1089]
Hello,

When I used one slider all works perfectly.  However, introducing the second slider causes all prev / next buttons to fail to work.

I have created a video which makes it more obvious.

I should say, when using only one slider, it works perfectly.  I have verified the Slider ID's are unique

https://youtu.be/3qfkBsbod9I

Thank you.

Jay
CompuMatter

**Comment by sn3ka** [comment]
Hi,

can you more details about your code ?
can you replicate the issue in a jsfiddle ? or give some sample of your bxSlider function.
personally I have seen this behavior in many situations, and it is mostly due to jquery or css conflict, not with bxslider itself.

**Comment by sekmenhuseyin** [comment]
[jsfiddle](https://jsfiddle.net/sekmenhuseyin/aafn1u6q/)
problem occurs when auto option is selected and pressed next/prev a few times

**Comment by compumatter** [comment]
Thanks for the input.  I have gone in a different direction do to this issue and a few others.  We created what we needed from scratch.
