### ISSUE TITLE
.load() incompatibility issue with jQuery 3.0

### ISSUE THREAD

**Issue by dave11mj** [stevenwanderski/bxslider-4#1100]
The issue is about jQuery version 3.0 and compatibility with bxslider.js. And this issue was arised by jQuery .load() function. You have to change bxslider.js's one line to solve this issue. Open your bxslider.js file and find .load() function's code line. It was used only 1 time in bxslider.js, so the necessary change is:

From
```
$(this).load();
```

To
```
$(this).trigger('load');
```

Original Source:
http://stackoverflow.com/questions/38486524/jquery-bxslider-exception

Tested the answer and seemed to work for me.

**Comment by stevenwanderski** [comment]
This has been fixed here: https://github.com/stevenwanderski/bxslider-4/pull/1024

The fixed version has been deployed to the doc site as well.
