### ISSUE TITLE
bxSlider breaks position:fixed header on scroll

### ISSUE THREAD

**Issue by leojauncey** [stevenwanderski/bxslider-4#1103]
I have a header that sites above the BX Slider and when I change to position:fixed half of it disappears. Only the logo remains. Any help please.

**Comment by leojauncey** [comment]
By the way only an issue on Chrom/Safari, Firefox fine.

**Comment by viktorbijlenga** [comment]
Is there a live URL where I can look at the issue?
Sounds like a `z-index` issue in general.

**Comment by leojauncey** [comment]
Unfortunately it is on a password protected client dev site. I have managed to fix it but not sure why the fix worked. 
The nav in the header is a list and had text-align right with the first item text-align left (so I could text-indent the text out of the way and use a background icon) when I removed the text-align:left from the :first-child the problem stopped.
I had the z-index organised and translteZ too.

**Comment by viktorbijlenga** [comment]
Great! Can we mark this as closed then?

**Comment by leojauncey** [comment]
Yes, there is definitely an issue with bx slider and fixed position elements sitting over the top but this is fixed for now.

**Comment by viktorbijlenga** [comment]
Ok. Good to know. 

If you want to contribute back to other users, make a Codepen (or similar) on how the `position: fixed ` issue looks like and add it as a comment here. It might be a good way to help others further down the road.

I’m marking this as closed.
