### ISSUE TITLE
how to deal with the img not being center?

### ISSUE THREAD

**Issue by weituotian** [stevenwanderski/bxslider-4#1111]
![image](https://cloud.githubusercontent.com/assets/7270968/23838876/da1b415e-07d4-11e7-8820-dc86e95b243d.png)

there is no option to make the pic to be center,is there a way to do that?

**Comment by viktorbijlenga** [comment]
I would guess an easy way to solve this is to add ‘margin: 0 auto;‘ to a class named ‘.bx-wrapper img‘

**Comment by viktorbijlenga** [comment]
@weituotian Have you managed to solve this so we can close the issue?

**Comment by weituotian** [comment]
@viktorbijlenga it is amazing! have solve this problem!thanks
