### ISSUE TITLE
Slider skipping items when next/ previous button pressed too fast

### ISSUE THREAD

**Issue by tony98789** [stevenwanderski/bxslider-4#1112]
If you have a slider with lets say ten images, and then you click the next button twice, on the next click the slider will skip one image. Ive only been able to reproduce this in jquery 1.9.1.

When you click next twice in rapid succession the slider only moves once, however on the next click the slider will skip on slide. It appears as though during the two initial clicks the index of the current slide is updated twice even though the slider on transitions once.

Will try to debug this and see whats happening in the event but any help would be appreciated. Just to make sure i haven't missed anything jquery 1.9.1 is supposed to be supported right?

I have reproduced the issue in this fiddle. http://jsfiddle.net/Yq3RM/1557/

**Comment by sekmenhuseyin** [comment]
https://github.com/stevenwanderski/bxslider-4/commit/cb40ef3e707142e5cf07dcacf023222497fb887f
