### ISSUE TITLE
slideSelector not working

### ISSUE THREAD

**Issue by GreenLondon** [stevenwanderski/bxslider-4#1116]
I have tried to use bxslider on the following code http://pastebin.com/iPf4xfdU

with this jquery lines

`$('#slider1).bxSlider({
slideSelector: '.vc_col-sm-4'
});`

All it showed was a big white box.

is there something wrong with my jquery lines?

Thank you.

**Comment by viktorbijlenga** [comment]
Hi there. Your jquery code snippet seems a bit off. Here's a demo on how to use bxslider. http://bxslider.com/examples/image-slideshow-captions

Feel free to close the issue or ask more questions. I'm happy to help.

**Comment by GreenLondon** [comment]
Hi, my mistake created the issue in a hurry.

The correct code is as follows

$('#slider1').bxSlider({
  slideSelector: '.vc_col-sm-4'
});

**Comment by viktorbijlenga** [comment]
I created a really fast Codepen to see what happend. The problem seems to be related to the HTML markup, not BxSlider itself. 

As you can see here, it works better if you change the classes a bit, and make the markup a bit easier.
https://codepen.io/anon/pen/jBxMPw

**Comment by GreenLondon** [comment]
The thing is that I need to create one slider from two rows. Not one slider for each row which what you are suggesting.

That's why I have been using #slider1 as the element on jquery.

**Comment by viktorbijlenga** [comment]
I'm not sure if that's possible since the slides needs to be children to the wrapper. 

If I were you I would create a simplified version with with a leaner markup. It's a good way to find out if it's possible.

**Comment by GreenLondon** [comment]
I created a new row with all six items inside it. I only need the slider to work on mobile phones therefore the two rows with three items each are only visible to pc without the slider and the single row with 6 items is converted to a slider if the width of the screen is under 767px.
