### ISSUE TITLE
bx-slider loding issue

### ISSUE THREAD

**Issue by rahule** [stevenwanderski/bxslider-4#1121]
![screenshot from 2017-04-01 16-00-10](https://cloud.githubusercontent.com/assets/26835512/24577903/66bab62a-16f4-11e7-9319-767fc3902ef6.png)
 Not loading bx-slider in chrome,

**Comment by viktorbijlenga** [comment]
You'll need to provide more information about your issue to be able to get help from the community. 

How can someone reproduce your issue?

**Comment by sn3ka** [comment]
Hi,

Check your console and tell us if you have any warning or error. Shouldn't be complicated to fix this.

**Comment by sekmenhuseyin** [comment]
@rahule are you there?
