### ISSUE TITLE
Error Uncaught TypeError: o.fitVids is not a function

### ISSUE THREAD

**Issue by RobertCC18** [stevenwanderski/bxslider-4#1122]
I am having an issue with this error "Uncaught TypeError: o.fitVids is not a function" when I try to use the slider, what am I missing?

Does the fitfids plugin require a specific file path within the file structure?

**Comment by viktorbijlenga** [comment]
Can you show us the relevant parts of your included scripts?

**Comment by RobertCC18** [comment]
s.settings.video&&o.fitVids(), is where the error is happening

**Comment by viktorbijlenga** [comment]
Could you set up a demo of your issue on something like JsFiddle?

**Comment by RobertCC18** [comment]
Only if you have external links to the bxslider files. I am currently using this in a wordpress plugin, I have tried multiple versions of jQuery and still the fitvids issue remains

**Comment by RobertCC18** [comment]
Thanks for the help but I got it. It was a simple matter of making sure the fitvids file was added before the jquery.bxslider.js was.
