### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by imza86** [stevenwanderski/bxslider-4#1123]
Hi, I am not sure why my one is not working.

Pls help me check out http://www.noor-azmi.com/element/slider.html

**Comment by sn3ka** [comment]
Hi,

simply clean the javascript code on your page:
replace:
```
$('.fuck').bxSlider();
        });
```
by:
`$('.fuck').bxSlider();`

or use the function when the DOM is ready:

```
$( document ).ready(function() {
    $('.fuck').bxSlider();
});
```

**Comment by imza86** [comment]
Hi, thanks its working now and have changed the class name from .fuck to .bxslider.

So now i am trying to make it auto play
http://bxslider.com/examples/auto-show-start-stop-controls

But when i do this, it doesnt work and goes back to the slider image one on top of the other.

**Comment by sn3ka** [comment]
can you update the page so i can see what is wrong ?

**Comment by imza86** [comment]
Hi, already updated here http://www.noor-azmi.com/element/

Thanks so much

**Comment by sn3ka** [comment]
```
$( document ).ready(function() {
        $('.bxslider').bxSlider({auto: true,autoControls: true});
});

```

**Comment by viktorbijlenga** [comment]
Seems to be solved now. I’m closing the issue.
