### ISSUE TITLE
mainfile not included in bower.json

### ISSUE THREAD

**Issue by arpit9295** [stevenwanderski/bxslider-4#1125]
Causes issues during automatically injecting the dependency, as is the case with the requirejs task in grunt.

**Comment by arpit9295** [comment]
Suggested changes -

{
  "name": "bxslider",
  "homepage": "https://github.com/wandoledzep/bxslider",
  **"main": "./jquery.bxSlider.min.js",**
  "_release": "64fd709291",
  "_resolution": {
    "type": "branch",
    "branch": "master",
    "commit": "64fd709291ae2ede1604a336b3312939c1858dfa"
  },
  "_source": "https://github.com/wandoledzep/bxslider.git",
  "_target": "*",
  "_originalSource": "bxslider",
  "_direct": true
}

**Comment by sekmenhuseyin** [comment]
that part exists in our bower.json
https://github.com/stevenwanderski/bxslider-4/blob/master/bower.json

can you explain more about the problem

**Comment by arpit9295** [comment]
For a certain reason, this wasn't showing up in the installed `bower.json`, was easily solved upon updating.
