### ISSUE TITLE
spacing issue left and top 

### ISSUE THREAD

**Issue by treis32** [stevenwanderski/bxslider-4#1132]
Hi, I have a slider on this page that i can't work out why there is a space on left and top.

http://thejunctionworks.org/NewsRoom/JunkFreeJune1.aspx
![screen shot 2017-05-29 at 4 35 37 pm](https://cloud.githubusercontent.com/assets/7157597/26538920/e83d890a-448c-11e7-999d-b3345e64cc29.png)

Would anyone know how to fix this please.
Thanks

**Comment by sn3ka** [comment]
Hi,

add a css class with:
.bxslider {margin:0; padding:0}

I checked on your page and it fixes it.

Cheerz

**Comment by treis32** [comment]
Hi There, that is great. I had to put !important; but it did fix it. Thank you.
