### ISSUE TITLE
Error: s.viewport.on is not a function

### ISSUE THREAD

**Issue by bigflannel** [stevenwanderski/bxslider-4#1135]
I am getting a JS error as try to update from V3 to the current version of bxSlider.

This is my call:
```
slider = $('#slider1').bxSlider({
   pager: false,
   controls: false
 });
```
This is the error:
> jquery.bxSlider.min.js:7 Uncaught TypeError: s.viewport.on is not a function
>     at N (jquery.bxSlider.min.js:7)
>     at g (jquery.bxSlider.min.js:7)
>     at HTMLImageElement.<anonymous> (jquery.bxSlider.min.js:7)
>     at HTMLImageElement.g (jquery.js:3)
>     at HTMLImageElement.handle (jquery.js:3)
>     at HTMLImageElement.k (jquery.js:2)
>     at Object.trigger (jquery.js:3)
>     at HTMLImageElement.<anonymous> (jquery.js:3)
>     at Function.each (jquery.js:2)
>     at init.each (jquery.js:2)

I can't think of any reason, any guidance / pointers / suggestion gladly received. I am updating this site:

https://clampart.com/2017/04/ghost-ship-3/

currently the new code is only local however.

Regards
Mike

**Comment by sn3ka** [comment]
HI,

can you tell us what version of jQuery you are using ? 
and do you call your bxSlider in a window.onload or document.ready ?

**Comment by ginsterbusch** [comment]
To instantly check the current version in use: https://stackoverflow.com/a/6973954

**Comment by bigflannel** [comment]
Hi

Thanks so much for getting back to me, it's jQuery 1.6.4. I think this must be the issue (I am using the latest bxslider). It never occurred to me.

I will update jQuery and take it from there.

Really appreciate the question!

I will post back when I have worked it through.

Regards
Mike

**Comment by bigflannel** [comment]
It was my version of jQuery.

Thank you so much for the advice. Much appreciated.

Regards
Mike
