### ISSUE TITLE
disabling bxslider via userscript

### ISSUE THREAD

**Issue by annie-l** [stevenwanderski/bxslider-4#1138]
i thought i'd come to the source on this...

https://www.herecomestheguide.com uses your library for venue pages, e.g. https://www.herecomestheguide.com/northern-california/wedding-venues/idesst-sausalito-portuguese-hall. i don't know what they're doing but it's a pretty frustrating user experience. i often find myself not able to click on specific thumbnails because of what i assume is the autoplay logic. and they don't have controls to stop the autoplay.

so i thought i'd write a userscript for my tampermonkey chrome extension to stop the gallery from autoplaying. i'm starting by re-initializing the `bxSlider` with essentially the parameters that they set in https://www.herecomestheguide.com/js/min/bx-min.js (although i'm trying turning off the auto parameters), then calling `stopAuto()`. it's not stopping the slider though, and when i click on a thumbnail, the player shuffles through all of them and then goes blank.

here's my code:
https://gist.github.com/annie-l/9abbca87a078af2e1b3669479d50685b

any hints on how i can retrieve the slider that they set up in a separate script -- without reinitializing it -- and then stop it from playing automatically?

**Comment by sn3ka** [comment]
Hi,

I am not really familiar with Tampermonkey but, it looks like it changes your code, and some options are no more 'false' but '!0'. 

I made a jsfiddle with your sources and code (the first as it is, the second with the javascript calling bxSlider and the auto option to 'false' and not '!0').

https://jsfiddle.net/xkoytt1L/1/

https://jsfiddle.net/xkoytt1L/2/

Looks like it is working.
Cheerz

**Comment by annie-l** [comment]
thanks. unfortunately i think that something is up with how tampermonkey works because no matter what i try it's still not stopping the original bxSlider. i don't control the original page, i'm just a viewer of the page, and trying to use tampermonkey to override the source code.

i appreciate the help though.
