### ISSUE TITLE
Disable touch (drag) when all slides are showing in carousel

### ISSUE THREAD

**Issue by bbceg** [stevenwanderski/bxslider-4#1146]
When all items in a carousel are visible (for example due to a large screen width and a small number of items) the next and previous controls are correctly disabled (for there is no need to scroll). However swiping the slider is still possible and the result is (understandably) a bit odd with the effect of duplicate slides and white space appearing at either end of the slider.

If touch support could be disabled at the same time as the controls are disabled that would seem the best solution.

Thanks for your time.

**Comment by david884** [comment]
謝謝 我的手機比較老舊沒法那麼快自己還亂下載一些有的沒用的 也不敢亂刪掉就越來越慢如同人說的要用電腦才能用

**Comment by sajidshah** [comment]
> 謝謝 我的手機比較老舊沒法那麼快自己還亂下載一些有的沒用的 也不敢亂刪掉就越來越慢如同人說的要用電腦才能用

Well said... :D
