### ISSUE TITLE
How can I use it with my ReactJS Project? 

### ISSUE THREAD

**Issue by chandan7193** [stevenwanderski/bxslider-4#1159]
I am getting message "warning  'bxSlider' is defined but never used " and my chrome console is showing message 
 "Uncaught TypeError: (0 , _jquery2.default)(...).bxSlider is not a function at HTMLDocument<anonymous> (Section2.js:12) at mightThrow (jquery.js:3583) at process (jquery.js:3651) 

I have imported
 import $ from 'jquery';
import bxSlider from 'bxslider'

**Comment by Meebo-** [comment]
Make sure your jquery comes before bxslider, if not, try and remove jquery and import from the link in the docs. <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> otherwise your section2.js might be the error.  Let me know.

**Comment by chandan7193** [comment]
@Meebo- Thanks for the help. I have added jQuery CDN to my index.html and it worked properly.
Thanks again.
