### ISSUE TITLE
jQuery UI Tabs + multiple carousels does not work

### ISSUE THREAD

**Issue by mpgjunky** [stevenwanderski/bxslider-4#117]
Hi,

I have a vertical tab, using jQuery UI Tabs, with 5 tabs. Each tab contains a carousel, but whilst the first tab shows a perfect carousel, the second tab show a messed up carousel. I have poked around as much as possible, but I can't figure out what's causing it. I do however, suspect the calculations are going wrong.

Any ideas anyone?

Cheers,
Michael.
![screenshot_418](https://f.cloud.github.com/assets/3842410/256287/b96ba752-8c25-11e2-806c-e55d6c2f444e.png)
![screenshot_419](https://f.cloud.github.com/assets/3842410/256288/befb2378-8c25-11e2-91a9-d3afced129fd.png)

**Comment by krishana** [comment]
Check it

http://jsfiddle.net/phpdeveloperrahul/bejFM/
