### ISSUE TITLE
bug left click on slide or slide content is not working in FireFox 59.0

### ISSUE THREAD

**Issue by comcava** [stevenwanderski/bxslider-4#1187]
Actually, I'm not sure is it ff bug or bxslider, but it seems that in Firefox 59.0 - when you click on slide -nothing is happened. Console log is still empty.

**Comment by NikolasVer** [comment]
Yep! I have same issue in firefox 59. In 58 was okay. Any solution?

**Comment by ifelse-** [comment]
Ran into the same issue today. Please see for possible solution. 
https://github.com/stevenwanderski/bxslider-4/issues/1188

**Comment by comcava** [comment]
Thank's! The problem is gone!
