### ISSUE TITLE
Add option for show/hide control arrows on viewport hover

### ISSUE THREAD

**Issue by zulfia** [stevenwanderski/bxslider-4#131]
Please, add option for show/hide control arrows on viewport hover. Like this:

$(document).ready(function(){
  $('.bxslider').bxSlider({
        controls: true,
        onSliderLoad: function () {
            $('.bx-controls-direction').hide();
            $('.bx-wrapper').hover(
                function () { $('.bx-controls-direction').fadeIn(300); },
                function () { $('.bx-controls-direction').fadeOut(300); }
            );
        }  
  });
});

**Comment by musaspot** [comment]
that really helps! thank you!
