### ISSUE TITLE
Webkit (Chrome, Safari) Window Resize Issue

### ISSUE THREAD

**Issue by TheWinner** [stevenwanderski/bxslider-4#136]
Hello,

Resizing the browser window of Chrome or Safari causes bxslider to stop and none of the controls do not work anymore.

Ex:

 var slider = $('#highlights').bxSlider({

            minSlides: 1,
            maxSlides: 4,
            
            slideWidth: 245,

            ticker: false, controls: false,
            auto: true,
            speed: 2000
        });

If you resize the browser window couple of times, the auto function of slider stops to work and you can not change the actual page anymore.

Quick Fix: 

Removing the following line fixes the problem.

$(window).bind('resize', resizeWindow);

Regards,
Berk

**Comment by Tidal-Wave** [comment]
Fixed in 4.2.2
