### ISSUE TITLE
slideWidth value sets bx-wrapper max-width

### ISSUE THREAD

**Issue by ghost** [stevenwanderski/bxslider-4#137]
//script 
$('.home .row-2 .company-slides').bxSlider({
        controls: true,
        pager: false,
        minSlides : 4,
        minSlides : 4,
        slideWidth: 200
});

//style

.company-slide-container {
            width: 940px;
            margin: 0 auto;

```
        .company-slides {
            width: 940px;
            float: left;

            .slide {
                width: 200px;
            }
        }
```

}

//html

<div class="row-2">
    <div class="company-slide-container">
        <div class="company-slides">
            <div class="slide"></div>
            <div class="slide"></div>
            <div class="slide"></div>
                        <div class="slide"></div>
        </div>
    </div>
</div>

The value of slideWidth is adding an inline style to bx-wrapper "max-width: 200px" (or whatever value I set slideWidth).

**Comment by macdonjo** [comment]
This also happens with ul and li
