### ISSUE TITLE
Using 'fade' in carousel mode doesn't appear to work.

### ISSUE THREAD

**Issue by FrankEBailey** [stevenwanderski/bxslider-4#144]
Hi, I'm not sure if I've just gone blind, but I don't see anything in the documentation about using 'fade' as the transition when displaying multiple slides at once being a problem, yet when I do so only one slide is visible. Is there something innately impossible about fading multiple slides when in carousel mode, or am I just missing something blindingly obvious as usual?

Thanks in advance!

Using 'horizontal' (default):

![All_Good](https://f.cloud.github.com/assets/273418/338062/7dbe78ec-9d00-11e2-95a5-5190404356c5.jpg)

Using 'fade'

![Whoopsy ](https://f.cloud.github.com/assets/273418/338063/b43a9f04-9d00-11e2-9da1-54a9bdf3128a.jpg)

**Comment by studioraygun** [comment]
Can the documentation be updated to state that this doesn't work? It's near the top of the options page, and should be stated so people don't download it expecting this feature.
