### ISSUE TITLE
[Chrome]Bx Slider start with "First Clone"

### ISSUE THREAD

**Issue by Metalchocobo** [stevenwanderski/bxslider-4#154]
Hello folk,
i use bxSlider since 2011,but now i met a strange issue only with Chrome.

Open this link with CHROME : http://essenza.adostudio.it/

Refresh that page a lot of times. You can see that sometimes bxSlider doesn't start with the first slide (index 0), but with first clone of last slide. 
This happen only with Chrome for desktop. IE/FF/Opera, Chrome on Android are ok.

You can see this problem? Any solution?
Thank you very much.

**Comment by Tidal-Wave** [comment]
Hey there folks. I've been added to the project to assist in maintaining it. Sorry for any lack of communication. 

Im trying to get a handle on the issue here, and have seen it before, but I need to review some items, I have this issue marked for review after I push a much needed update.

**Comment by JulienMelissas** [comment]
Hey dude! Looks like we run in some of the same circles ;)

**Comment by Tidal-Wave** [comment]
I saw you a few comments up after I posted this. Good to see ya. We are assisting @stevenwanderski in dusting this project off and showing it some love. Just trying to wade through all this and get a plan of attack ready.

**Comment by JulienMelissas** [comment]
@Tidal-Wave That's great man! I always loved bxslider, but most recently have moved on to OwlCarousel, which is also not been maintained in a while :(

**Comment by Tidal-Wave** [comment]
We also admire some of the things that Owl does well, and will be looking to see what we can do to win people like you back. Would love to discuss this once we get our bearings.

**Comment by JulienMelissas** [comment]
Sounds good. I've actually offered to help him maintain Owl, but at the end of the day I just want a good slider/carousel to use ha

**Comment by noxbriones** [comment]
@thomasgriffin, quick & easy fix! Thanks!

**Comment by bglaz** [comment]
@thomasgriffin Thank you!

**Comment by raszagar** [comment]
I had the same issue when starSlide distinct 0 in firefox and chrome. IE10 work correctly.
```
$('#bxslider1').bxSlider({
   pagerCustom : '#bxpager1',
   adaptiveHeight: true,
   startSlide: 1
});
```
@thomasgriffin not fix problem

**Comment by namlq93** [comment]
Step 1: Set css:  `.bx-clone {display: none;}`
Step 2: `$('.slider').bxSlider(
      {
        onSlideBefore: function(){
          $(".bx-clone").show();
        }
      }
    );`
