### ISSUE TITLE
Disable "Previous button" (.bx-prev) if I'm at the first page of the slider and "Next button" (.bx-next) if I'm at the last page of the slider

### ISSUE THREAD

**Issue by renatocarvalho** [stevenwanderski/bxslider-4#156]
Hi guys, I was wondering if anyone has already managed to implement something that adds a ".disabled" class on "Previous button" (.bx-prev) if I'm at the first page of the slider and "Next button" (.bx-next) if I'm at the last page of the slider.

Also, I think it would be really cool if this feature would come in bxslider by default.

Thanks!

**Comment by kishan-chauhan** [comment]
I have same issue, but i try this option bxslider it's works...

$(".bxslider").bxSlider({auto:true,hideControlOnEnd:true,infiniteLoop:false});

**Comment by arkid** [comment]
Can I suggest that this value changes its default depending on the value of the infiniteLoop parameter?  It would be far more logical for hideControlOnEnd to be true when infiniteLoop is disabled.
