### ISSUE TITLE
Add the ability to constrain the height

### ISSUE THREAD

**Issue by neo314** [stevenwanderski/bxslider-4#158]
For "designed sliders" it does not really matter, but I was also trying to use a responsive slider/gallery that could contain video or images as a CMS gallery. 

That means I don't have the same control over the images that will be displayed, especially in a responsive layout. I am using a jquery-ui dialog opening at 90% of the screen size. I need to be able to be sure the image stays in the dialog without scrolling, and portrait images really screw this up.

I solved the issue for this implementation with the code below, but it would be nice if this was a feature. I couldn't find any other slider providing this feature.

// Set the gallery Height initially to the inner height of the parent container minus the top and bottom padding
	var galleryH = $('#lightboxCont', window.parent.document).innerHeight()-parseInt($('#lightboxCont', window.parent.document).css("padding-top"))-parseInt($('#lightboxCont', window.parent.document).css("padding-bottom"));
	// Initialize the slider
	
	slider = $("#gallery").bxSlider({
		adaptiveHeight:true,
		auto:true,
		autoStart:false,
		autoControls:true,
		slideMargin:100,
		onSliderLoad: function() {
			// Reduce the gallery height by the bottom margin of the bx slider which is css fixed.
			galleryH = galleryH - parseInt($(".bx-wrapper:first").css("margin-bottom"));
			// If there are controls, reduce the height by their height
			if ($(".bx-controls:first").length) {
				galleryH = galleryH - $(".bx-wrapper .bx-pager:first").outerHeight();
			}
			// Set the corrected height of the gallery
			$("#gallery").css("height", galleryH+"px");
			var slides = slider.children("div");
			slides.each(function() {
				var item = $(this).find("img, iframe");
				if (item.length) {
					if ((($(".bx-viewport:first").innerWidth()/item.width()) * item.height()) > galleryH) {
						var ratio = galleryH/item.height();
						var w = Math.round(item.width()*ratio);
						var h = Math.round(item.height()*ratio);
						item.css({"width":w,"margin":"auto"});
						if (typeof(item.attr("width")) != "undefined") {
							item.attr("width",parseInt(w));
						}
						if (typeof(item.attr("height")) != "undefined") {
							item.attr("height",h);
						} 
					}
				}
			});
			$(".bx-viewport:first").css("height",galleryH+"px");
		},
		// For some reason, Safari and Opera want each slide checked for images.
		onSlideBefore: function(slide) {
			var img = slide.find("img:first");
			if (img.length) {
				if ( (($(".bx-viewport:first").innerWidth()/img.width()) * img.height()) > galleryH) {
					var ratio = galleryH/img.height();
					var w = Math.round(img.width()*ratio);
					img.css({"width":w,"margin":"auto"});
					img.parents(".bx-viewport").css({"height":img.css("height")});
				}
			}
		}
	});

**Comment by Tidal-Wave** [comment]
Will look at this for future update. Currently focused on issue updates. Closing for house keeping.
