### ISSUE TITLE
cordova, jqmobile changes other element's events

### ISSUE THREAD

**Issue by gizur-ess-anshuk** [stevenwanderski/bxslider-4#159]
I am developing an app using cordova on android with the setup

	<link rel="stylesheet" href="js/jquery.mobile-1.2.1/jquery.mobile-1.2.1.min.css" />
	<link href="css/jquery.bxslider.css" rel="stylesheet" />	
	
	<script src="js/jquery.mobile-1.2.1/jquery-1.8.3.min.js"></script>
	<script src="js/jquery.mobile-1.2.1/jquery.mobile-1.2.1.min.js"></script>
	<script src="js/jquery.bxslider.min.js"></script>	

I have a multi page html page a navbar and some select elements.

The slider works smoothly but when i click on the the navbar the select box's options pop up. 

Also I have to tap twice over the select box to see its options.

Any idea whats causing this?

**Comment by Tidal-Wave** [comment]
Closing issue due to age and lack of information.
