### ISSUE TITLE
Image resize only happens when you resize the window

### ISSUE THREAD

**Issue by cascadia-helentsang** [stevenwanderski/bxslider-4#167]
I've been using the slider for a while. It works very well when the images do not have to be resized. However, when I have a browser window that is smaller than the images (thus requiring the images to be scaled down when loading), the images do not show up at all. As soon as I resize the window, however, the images are properly resized and loaded. I guess the window resize event is triggering a image resize that should have been called at the initial load as well?

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/136, https://github.com/stevenwanderski/bxslider-4/issues/705, https://github.com/stevenwanderski/bxslider-4/issues/694.

Closing due to duplication and housekeeping. Hope to address this in the next update.
