### ISSUE TITLE
Auto stops working when the Window is resized during Slide-Transition

### ISSUE THREAD

**Issue by apircher** [stevenwanderski/bxslider-4#169]
Resizing the Window triggers the resizeWindow-Function and finally the drawSlider-Function. When that happens during a Slide-Transition, the "slider.working"-Property is never set back to false. As a result, the Auto-Mode does not work anymore and calling Functions like goToSlide has no effect.

I solved it by checking the "slider.working"-Property in the resizeWindow-Function. If it has the value true, I exit.

<code>
var resizeWindow = function (e) {
  **if (slider.working) return;**
  ...
}
</code>

**Comment by Tidal-Wave** [comment]
related to https://github.com/stevenwanderski/bxslider-4/issues/702 and others. Looking to address resize issues in next update.

**Comment by Tidal-Wave** [comment]
I have addressed this issue in 4.2.2, but please let me know if any issues still arise.

**Comment by commwork** [comment]
None of these solutions help. Still have this problem. Sometimes it seems to work but when leaving the window for a longer time the problem is back.
