### ISSUE TITLE
"pagerCustom" won't work when using reloadSlider

### ISSUE THREAD

**Issue by jackyon** [stevenwanderski/bxslider-4#171]
Hi, I just found out the "pagerCustom" won't work when using reloadSlider, it disappeared when reload the slider.

plz advise. million thx!

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/pull/610.

Will fix in next update.

**Comment by Tidal-Wave** [comment]
Fixed in 4.1.3
