### ISSUE TITLE
Feature request: Public Method or var for current slider 'number'

### ISSUE THREAD

**Issue by mw-ph** [stevenwanderski/bxslider-4#173]
Trying to style the navigation pager based on which slider is active using the onSlideAfter public method.  Can't seem to find a var with the number in to find the a.bx-pager-link by a look using [data-slide-index="' + var +'"] find.

**Comment by Tidal-Wave** [comment]
Will look at this for our next update.

**Comment by Tidal-Wave** [comment]
`getCurrentSlide` returns current (zero-based) slide index.
