### ISSUE TITLE
Last slide auto moves

### ISSUE THREAD

**Issue by scarlettQuest** [stevenwanderski/bxslider-4#174]
Hi,
I'm using bxslider to display video thumbnails, where the video is loaded on click of the image. I need to expand and contract each slide so that the video can play.

My issue is with the last slide. I am showing 3 slides at each instance. Say I have 10 slides, when I reach the last set, it displays the 9th and 10th slide. I want it to show only the 10th slide. 

There is an auto move when it detects that there is only 1 slide left. Is there a way to avoid that?

I hope that made sense.
Thanks in advance!

**Comment by Tidal-Wave** [comment]
Closing due to lack of example. Im not sure I understand the issue at hand. If you would like to continue this issue, please reopen with an example if possible.
