### ISSUE TITLE
When carrousel items have lateral margin, it doesn't work properly

### ISSUE THREAD

**Issue by gonssal** [stevenwanderski/bxslider-4#181]
Let's say I have this:

ul {
  margin: 0 0 0 -2%;
}
 ul li {
  float: left;
  width: 23%;
  margin: 0 0 2%  2%;
 }

This is common when doing responsive stuff with floated items. The thing is when the list items have the lateral percentage margin and you apply bxSlider with slideWidth, because the plugin will set the ul's width to amount_of_slides * slide_width, that 2% margin will be a lot different than what you wanted.

**Comment by Tidal-Wave** [comment]
Closing due to age of issue and lack of example. We are currently focusing our energy on provided a much needed update. If you would like to pursue this issue please reopen with an example of the issue.
