### ISSUE TITLE
bxSlider inside another bxSlider doesn't work properly

### ISSUE THREAD

**Issue by Peter1976** [stevenwanderski/bxslider-4#190]
Hi!
I want to put one bxSlider into another bxslider, like this:

http://jsfiddle.net/Peter76/aKEDT/

As you can see, there is a problem after the last third slide, when the "inner slider" is shown again.
I've partly solved the problem - I just swapped the sliders in JS section, like this:

http://jsfiddle.net/Peter76/aKEDT/1/

But there is still another problem. Please switch number of "inner slider" on 2, click "next" three times, and then look at the slide of "inner slider" before transition is complete. Something is wrong with the transition.

I found a way on this issue as well. If you start "outer slider" with normal content, everything is OK. But if you have "inner slider" as a first slide, something is wrong during transition.
This is an example: the "outer slider" which begins with the normal content:

http://jsfiddle.net/Peter76/aKEDT/2/

As you can see everything is OK, but sometimes I need to have "inner slider" on a first position.

Please for help. Im completly devastated by this. 
Sorry for my English
Thanks a lot in advance. 
Peter

**Comment by Tidal-Wave** [comment]
Closing due to age and lack of live example. Please reopen if question still needs assistance.
