### ISSUE TITLE
Hyperlink in captions of picture

### ISSUE THREAD

**Issue by cudencuden** [stevenwanderski/bxslider-4#193]
Captions pull from the title of images. Is there any way possible to have hypertext links (anchor tag) as part of the captions?

An example of a caption in a picture would be: "This is a caption. To learn more click here"

**Comment by llahnoraa** [comment]
It doesn't work on 4.1.2 on carousel or slider.

**Comment by cudencuden** [comment]
gotta open new issue

**Comment by cudencuden** [comment]
ohh.... I reopen

**Comment by kuldeepkaushik** [comment]
> It doesn't work on 4.1.2 on carousel or slider.

yes i am facing same issue. did you get any solution ?

**Comment by ayyilmaz** [comment]
I cant add links to captions. How can I do?
