### ISSUE TITLE
IE8 li collapses

### ISSUE THREAD

**Issue by dt35** [stevenwanderski/bxslider-4#197]
IE8 was collapsing the li elments when loading.
If you add a style.
.bxslider li {
	width: 175px;
}

They work fine
Or some jQuery to find image width and match the li?

var liWidth = jQuery('.bxslider img').width()
jQuery('.bxslider li').width(liWidth)

**Comment by Tidal-Wave** [comment]
Closing due to lack of example and unable to reproduce.
