### ISSUE TITLE
"flash" mode in transitions - new feature request

### ISSUE THREAD

**Issue by ghost** [stevenwanderski/bxslider-4#199]
I'd ask you, if possible, an option to make a flash of white (or different color) between slides, in fade transition mode.

The idea is to have a fade between divs o images, but also a "flash" empty box, just to emphasize the change.

Thanks.

**Comment by Tidal-Wave** [comment]
Closing because this is not a current priority as we clean house. Will consider this as a future update if the community show a desire to have it.
