### ISSUE TITLE
Pager touch issues on mobile

### ISSUE THREAD

**Issue by marcopanichi** [stevenwanderski/bxslider-4#200]
I'm using a Galaxy S2 with Firefox.

The pager is activated.

It's very difficult to touch the anchors. They react randomly.  It's difficult even though I enlarge the screen.

Any suggestions?

**Comment by Tidal-Wave** [comment]
possibly related to https://github.com/stevenwanderski/bxslider-4/pull/596. Closing because of duplicate issue and housekeeping. Will address in update.
