### ISSUE TITLE
Auto slide show stopped working on clicking on pager/next/previous

### ISSUE THREAD

**Issue by ManiAkasapu** [stevenwanderski/bxslider-4#201]
Thanks for awesome plugin.
using 4.1,
First my code:

$('.bxslider').bxSlider({

		    auto: true,
		    pause: 1000,
		    randomStart : true,
		    autoHover: true

		});

My Problem: If I click on (next / previous / Jump to any slide ) its moving to that slide but afterwards it is not automatically moving to next slide. What i need is if i jump to any slide it should start animation from the next slide to it.

Hope I explained well enough.

Please look into the issue and help me.

**Comment by Tidal-Wave** [comment]
Closing due to lack of example and age of issue. Please provide a working example of the issue. Possibly related to https://github.com/stevenwanderski/bxslider-4/issues/702.
