### ISSUE TITLE
Slider prevents JqueryUI dialog from opening in Safari only

### ISSUE THREAD

**Issue by cutefuzzy** [stevenwanderski/bxslider-4#204]
I've got a bxslider underneath a jqueryui dialog. In Safari 5.1.7 Win the dialog does not appear. As far as I can tell it is due to something in bxslider but can't quite narrow down what. Works fine in Chrome, so it isn't a Webkit issue. 

See example at frigment.com/apcrimetest/mockup.php
Click About or Login to show a modal.

Works fine in everything but Safari. (Haven't cross booted to the Mac to test it in legit Mac Safari, sorry.)

**Comment by Tidal-Wave** [comment]
Closing due to unsupported browser issue. If I remember correctly Win Safari 5.1.7 didn't support this, and is currently discontinued. `useCSS: false` is the only solution if that browser is required.
