### ISSUE TITLE
Can Bxslider be used with Scott Jehl's Picture Fill?

### ISSUE THREAD

**Issue by sumitpaul** [stevenwanderski/bxslider-4#206]
I am working on a responsive website that uses picturefill to load different image sizes at different breakpoints. But at times, I have noticed that the slideshow container collapses. Has anybody used Bxslider with responsive images being loaded at different media queries with solid results? ... Hoping to hear some suggestions.

The only alternative I can see is loading/destroying/reloading different slideshow containers for different media queries.

**Comment by Tidal-Wave** [comment]
Hi, my name is Eric and i've been added to this project to help maintain it and provide updates.

There are some known issues (https://github.com/stevenwanderski/bxslider-4/issues/560, https://github.com/stevenwanderski/bxslider-4/issues/683) revolving around image loading and resizing. We are looking into these issues for our next update.  Thank you for all the information provided.

**Comment by Tidal-Wave** [comment]
Issues with the slider breaking when transitioning and browser changing slide should be addressed and with loading issues. Let me know if anything pops up.
