### ISSUE TITLE
Issue with Ticker: unwanted thing at the bottom of the image

### ISSUE THREAD

**Issue by zemanee** [stevenwanderski/bxslider-4#207]
Hi, I am new with BxSlider. I am trying to use Ticker and i get some unwanted things at the bottom of the image. Please take a look at the attached image.

Can anyone please help me with this. 

Regards
Zakaria

![bxslider-error](https://f.cloud.github.com/assets/4544206/570142/75e43cc0-c72f-11e2-852e-733fdae6035d.png)

**Comment by Tidal-Wave** [comment]
Closing due to lack of example. Without more of an image or a link to an example of the issue I can't tell what those 'things' are.
