### ISSUE TITLE
Flash of content on load

### ISSUE THREAD

**Issue by justiny** [stevenwanderski/bxslider-4#210]
For some reason I can't get the preloader to work while using this configuration:
```
j('.bxslider-top-feature').bxSlider({
   mode: 'fade',
   pagerType:'short',
   preloadImages:'visible',
   auto:'true'
});
```

```
<div class="bxslider-top-feature">

     <div class="wrap">
          
          <img src="...">
     
     </div>

</div>
```

```
.bx-wrapper .bx-loading {
	min-height: 50px;
	background: url(../images/bx_loader.gif) center center no-repeat #fff;
	height: 100%;
	width: 100%;
	position: absolute;
	top: 0;
	left: 0;
	z-index: 2000;
}
```

I continue to get a flash of all the content before the slider kicks in.  I know the path is correct to the loader.  Not sure what I could be doing wrong.

Thanks for any help!

Justin

**Comment by Tidal-Wave** [comment]
Closing this issue for now. We will review FOUC issues in our next update.
