### ISSUE TITLE
Controls do not update on window resize

### ISSUE THREAD

**Issue by sanmau** [stevenwanderski/bxslider-4#216]
If all slides fit into the viewport on page load the prev and next controls do not show. If the window gets resized so that the slides no longer fit into the viewport (meaning, sliding left and right is neccessary) the controls still not show up. If page is rendered again, they show up. But I want them to show and hide automatically on resize.

**Comment by Tidal-Wave** [comment]
Closing issue due to lack of working example and information. We are reviewing improving the responsiveness of the controls in a future update. Possibly related to https://github.com/stevenwanderski/bxslider-4/issues/712.
