### ISSUE TITLE
Fixed, the cutted slide effect

### ISSUE THREAD

**Issue by myconcretelab** [stevenwanderski/bxslider-4#219]
I found this bug when window is resized on carousel mode. Before the number of slide is recalculed a slide was cutted (look on the screenshot). I've added a "else" to the "getSlideWidth" function and all seems working now. 
I've not tested on all configuration but with bootstrap responsive, all working.

		var getSlideWidth = function(){
			// start with any user-supplied slide width
			var newElWidth = slider.settings.slideWidth;
			// get the current viewport width
			var wrapWidth = slider.viewport.width();
			// if slide width was not supplied, or is larger than the viewport use the viewport width
			if(slider.settings.slideWidth == 0 ||
				(slider.settings.slideWidth > wrapWidth && !slider.carousel) ||
				slider.settings.mode == 'vertical'){
				newElWidth = wrapWidth;
			// if carousel, use the thresholds to determine the width
			}else if(slider.settings.maxSlides > 1 && slider.settings.mode == 'horizontal'){
				if(wrapWidth > slider.maxThreshold){
					// newElWidth = (wrapWidth - (slider.settings.slideMargin * (slider.settings.maxSlides - 1))) / slider.settings.maxSlides;
				}else if(wrapWidth < slider.minThreshold){
					newElWidth = (wrapWidth - (slider.settings.slideMargin * (slider.settings.minSlides - 1))) / slider.settings.minSlides;
				} else {
					newElWidth = (wrapWidth - (slider.settings.slideMargin * (slider.settings.maxSlides - 1))) / slider.settings.maxSlides;
				}		
			}
			return newElWidth;
		}
![capture decran 2013-06-05 a 18 34 30](https://f.cloud.github.com/assets/1971274/613266/d6ffc0c2-cdfd-11e2-9213-d93a14741d71.png)

**Comment by Tidal-Wave** [comment]
This current expected behavior but we are looking at requests to modify this for a future update. Closing for now.
