### ISSUE TITLE
Linked slides in auto mode not clickable on touch devices

### ISSUE THREAD

**Issue by imohkay** [stevenwanderski/bxslider-4#224]
Thanks for an amazing plugin. 
When the carousel is in auto mode, the thumbnails are not clickable on touch devices. Test case here: http://karenmenezes.com/platform2/
Click on the image icons in the header on a touch device. They don't go to the respective project page (works on desktop). I actually found out about your plugin, because Flexslider does not have an infinite loop option (which the client is insisting on). 
I'm using both bxslider and flexslider on the page, bxslider is for the header carousel. I commented out the flexslider code at some point, but the problem persists, so I uncommented it. For some reason, when in ticker mode, one is able to access the links in the header carousel on touch devices, but when auto is set to true, the links are no longer clickable, only on touch devices.

Tested on the ipad, ipod and android devices.

**Comment by Tidal-Wave** [comment]
Possibly related to https://github.com/stevenwanderski/bxslider-4/pull/596. Looking into improving touch events across the board. Closing due to duplication and housekeeping, but is on our radar.
