### ISSUE TITLE
Invert order call of appendControls() and appendPager()

### ISSUE THREAD

**Issue by Cedric-ruiu** [stevenwanderski/bxslider-4#226]
Hi,

In most web integration, we need to implement the "controls" first, the "pager" is below. So is it better to call appendControls() first? Html code is re-organized and is very easy to integrate thse elements in css.

jquery.bxslider.js line 251 simply becomes :

	// if controls are requested, add them
	if(slider.settings.controls) appendControls();
	// if pager is requested, add it
	if(slider.settings.pager) appendPager();

Cédric R.

**Comment by Tidal-Wave** [comment]
Hi, i've been added to this project to help with maintain it and provide updates. We will consider this issue for our next update.

**Comment by Tidal-Wave** [comment]
Fixed in 4.1.3
