### ISSUE TITLE
Adding a timer bar to bxSlider.

### ISSUE THREAD

**Issue by vmasto** [stevenwanderski/bxslider-4#230]
Hello, not really an issue but here goes,

Is there a surefire way to add a timer bar at the bottom of the slider (just a long bar which shows the animation progress) in bxSlider? Has anyone done it? Any out of your head solutions?

**Comment by Tidal-Wave** [comment]
Closing this issue for now and marking it as a feature request. We are in the process of updating bxslider and will consider a baked in progress timer in a future update, but we are focusing on immediate bug fix needs atm. 

The work around provided is fairly good, but the easing is what is probably causing issues with the syncing.

**Comment by jdmagic21** [comment]
You can add progressbar.js to the outside of your slider and make the progress bar position absolute. http://kimmobrunfeldt.github.io/progressbar.js/ Here are the settings that you would need to add: 

    var line = new ProgressBar.Line('#progress-line',{
     'duration': 3000,
      strokeWidth: .2,
        color: '#44697D'
      });

    $(document).ready(function(){
        $('.bxSlider').bxSlider({
       'responsive':true,
       'minSlides': 2,
       'maxSlides': 10,
       'speed': 3000,
       'pager': false,
       'auto':true,
       // show the bx slider after the page loads
       'onSliderLoad': function(){
          $('.bxSlider').css({'visibility':'visible'});
          line.set(1.0);
     },
     'onSlideAfter': function(){
        line.set(1.0);
     },
     'onSlideBefore': function(){
      line.set(0);
     line.animate(1.0);
     }
      });
    });
