### ISSUE TITLE
problem with goToSlide

### ISSUE THREAD

**Issue by pustovalov** [stevenwanderski/bxslider-4#235]
Slider stops working if use "goToSlide", if remove "goToSlide" slider start work.

initialization code:
```javascript
$(function() {

	var slider = $('.preview-pages').bxSlider({
	    slideWidth: 200,
	    minSlides: 1,
	    maxSlides: 4,
	    moveSlides: 4,
	    slideMargin: 10,
	    pager: false,
	    infiniteLoop: false
	  });
	slider.goToSlide(10);
});

```

[Example](http://goo.gl/SXJbT)

**Comment by Tidal-Wave** [comment]
Closing because op example is not live anymore. Please open a new issue with as much information as possible and an example of you have an issue.
