### ISSUE TITLE
Dynamic thumbnails slider markup

### ISSUE THREAD

**Issue by brgrz** [stevenwanderski/bxslider-4#237]
This page http://bxslider.com/examples/thumbnail-pager-2 shows how to generate slider with a random number of dynamic images and their thumbnails under it. I don't really get this example - is is actually required to have the wireups done in Javascript?

If so, that would require dynamic JS generation (for instance, when creating slider from data saved in datastore). This is something I try to avoid as much as possible.

Is there a way to make it work via data- attributes?

Instead of this

	$('.bxslider').bxSlider({
		buildPager: function(slideIndex){
			switch(slideIndex){
				case 0:
					return '<img src="/images/thumbs/tree_root.jpg">';
				case 1:
					return '<img src="/images/thumbs/houses.jpg">';
				case 2:
					return '<img src="/images/thumbs/hill_fence.jpg">';
			}
		}
	});

	<ul class="bxslider">
		<li><img src="/images/730_200/tree_root.jpg" /></li>
		<li><img src="/images/730_200/houses.jpg" /></li>
		<li><img src="/images/730_200/hill_fence.jpg" /></li>
	</ul>

we would have something like this:

	$('.bxslider').bxSlider();

	<ul class="bxslider" data-thumbPager="true">
		<li><img src="/images/730_200/tree_root.jpg" data-thumb="/images/thumbs/tree_root.jpg" /></li>
		<li><img src="/images/730_200/houses.jpg" data-thumb="/images/thumbs/houses.jpg"/></li>
		<li><img src="/images/730_200/hill_fence.jpg" data-thumb="/images/thumbs/hill_fence.jpg"/></li>
	</ul>

?

**Comment by Tidal-Wave** [comment]
Hey there, i've been added to this project to help maintain it and provide updates. I agree that a better method of doing thumbnails is probably needed. I am reviewing all the issues right now so that we can address urgent needs first, so I am going to close this for now, but will mark and assign this so that we can evaluate this for an update in the near future.
