### ISSUE TITLE
autoStart doesn't change anything at true or false

### ISSUE THREAD

**Issue by WulleBulle** [stevenwanderski/bxslider-4#24]
Hi,

just tried autoStart but it doesn't seem to change anything in the slider behavior.

$('.bxslider').bxSlider({
  mode: 'horizontal',
  autoStart: true,
  startSelector: 'start',
  autoControls: true,
  hideControlOnEnd: true
});

If I try it with the code above the slider doesn't start to transist. It only starts with "auto:true" while autoStart seems to do nothing. Looks like it takes no effect.

What am I doing wrong?
Thanx alot in advance.

Kind regards
Wulle

**Comment by llahnoraa** [comment]
Yeah, `auto: true` does work but it was nowhere mentioned in Options page :\
