### ISSUE TITLE
never show half images

### ISSUE THREAD

**Issue by fourroses666** [stevenwanderski/bxslider-4#241]
Very nice script! 
When I smallen my browser and it goes from 4 thumbs to 3 thumbs I can see 3,5 thumbs.
Is there a way to fix this? Directly go from 4 to 3 thumbs.

**Comment by Tidal-Wave** [comment]
Currently this is the default behavior, we are looking to improve the responsive aspects of the slider in a future update. You can achieve this effect with some js and 'reloadSlider()' by passing it new options.
