### ISSUE TITLE
bxSlider callback

### ISSUE THREAD

**Issue by Peter1976** [stevenwanderski/bxslider-4#242]
Hello everyone!

How to match a different callback function to each slide? For example, I'd like to call JQuery code no 1 after first slide, and then different code number 2 after second slide, and so on. Obviously, I saw an example on the website, but, I don't know how to write this. Could you write me an example? Many thanks in advance.

**Comment by Tidal-Wave** [comment]
Closing due question age and lack of issue. This could be achieved by using switch statements, functions, etc.
