### ISSUE TITLE
MozPerspective Does Not Work in version 4

### ISSUE THREAD

**Issue by hasanilingi** [stevenwanderski/bxslider-4#244]
I recognized that in version 4 when useCSS is true because of the props MozPerspective in Moziila Firefox version 21.0 the youtube videos with iframe Api does not show when i disabled transform or change it to none from firebug it shows the video, so for now i remove MozPerspective from props array.

**Comment by Tidal-Wave** [comment]
Closing due to lack of example and housekeeping. Will review at later date.
