### ISSUE TITLE
Don't load slider if image not found.

### ISSUE THREAD

**Issue by wellic** [stevenwanderski/bxslider-4#246]
Slider wasn't loaded slider if image not fount. (onSliderLoad event does't work too).

I localy modify your file.
I added to the function var loadElements = function(selector, callback)...
follow line:
   $(this).error(function(){ setTimeout(function(){ if(++count == total) callback();}, 0)});
before line:
   $(this).load(function(){ setTimeout(function(){ if(++count == total) callback();}, 0)});

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/560. Closing due to duplicate issue. We are aware of issues with images not loading, and are looking to address this soon in an update.
