### ISSUE TITLE
destroySlider(); bug on pagerCustom

### ISSUE THREAD

**Issue by tomasdev** [stevenwanderski/bxslider-4#250]
When using `pagerCustom`, the selector after running `.destroySlider();` gets deleted from DOM.

I'll do a pull request if you agree, to fix this one.

**Comment by Tidal-Wave** [comment]
Closing due to duplication of https://github.com/stevenwanderski/bxslider-4/pull/610. We will fix this in our next update. Sorry for the delay.

**Comment by wistala** [comment]
On line 1632;
find this => if (slider.pagerEl && slider.settings.controls && !slider.settings.pagerCustom) { slider.pagerEl.remove(); }

and change with this => if (slider.pagerEl && slider.settings.controls && !!!slider.settings.pagerCustom) { slider.pagerEl.remove(); }
