### ISSUE TITLE
Ticker Issues

### ISSUE THREAD

**Issue by fusiongt** [stevenwanderski/bxslider-4#252]
Hi, love the work on bxslider. I would like to request a few things for the ticker portion:

- tickerHover doesn't seem to work. I've tried a few variations of it what was in my slider and none would pause. In the ticker example on the site, adding tickerHover also does not work.

- Could there also be a tickerDelay similar to autoDelay? autoDelay unfortunately does not pause it when it's in ticker mode, so the ticker begins running immediately and there's no setting built in to stop that.

- An extra delay/pause setting for when the ticker goes from slide to slide would be good as well. I know we could use the built in auto-playing slide version and hide the controls so perhaps this isn't needed but something would be pretty useful I think.

Thanks!

**Comment by Tidal-Wave** [comment]
related to https://github.com/stevenwanderski/bxslider-4/pull/629 and https://github.com/stevenwanderski/bxslider-4/issues/669. 

Closing due to duplicate issues, but have we intend to address these issues in our update.
