### ISSUE TITLE
slider shakes the content on page when sliding

### ISSUE THREAD

**Issue by MoonDevilzzz** [stevenwanderski/bxslider-4#254]
Hi guys.great plugin. but i have some problem. on http://stroycom.miksart.ru/
when the big slider moves image, it shakes the text below the circles, but bottom ,small slider doesnt. Please help, i have that issue only in Chrome.

**Comment by Tidal-Wave** [comment]
This is a known webkit issue with font rendering. Not much can be done on our end currently.

**Comment by TokomNyori** [comment]
I'm having the same problem... My whole content is shaking when I scroll because of the CDN script tag I'm using for sliding the cards. Shakiness disappears when I remove the CDN script tags.
