### ISSUE TITLE
Preload of images fails if img tag has no src value

### ISSUE THREAD

**Issue by robvon** [stevenwanderski/bxslider-4#256]
When loading pure html, not just images, it may be that the img tag gets it's src attr set dynamically - such as after a camera action for a mobile app. 

In another case, the img tag may be hidden until required.

Either way, the callback for the function 'loadElements" will never fire as the jQuery.Load() will not return for the img with no src and ++count will NEVER be > total.

This can be fixed by checking the src attr for each img before doing the load and incrementing 'count' if it is missing.

**Comment by tomchiverton** [comment]
This also occurs if you use ng-src because the slider is in an Angular app. Incoming pull request...
