### ISSUE TITLE
2 slides - crash

### ISSUE THREAD

**Issue by TorstenE** [stevenwanderski/bxslider-4#259]
I have 2 slides on one page.
If you klick on a Thumbnail on slide 1, slide 2 'crash' .
You can klick "prev" or "next" on slide 2 it does nothing.
"slide 1" runs normaly.

(function($) {
	$('#bxslider1').bxSlider({
		pagerCustom: '#bx-pager1',
	});
})(jQuery);

(function($) {
	$('#bxslider2').bxSlider({
		pagerCustom: '#bx-pager1',
	});
})(jQuery);

**Comment by Tidal-Wave** [comment]
Closing due to lack of working example of issue and age. If you would like to pursue this issue please reopen with an example and more information.
