### ISSUE TITLE
Leftovers of wrapper- & viewport-divs after calling .sliderReload() / .destroySlider()

### ISSUE THREAD

**Issue by callmefunkeyescobar** [stevenwanderski/bxslider-4#261]
Hello there,

first of all thank you for sharing your sliderplugin.

i recognized an bug when calling the .sliderReload(-) / .destroySlider()- methods. 
After  .sliderReload() is executed, the divs with the classes ".bx-wrapper" and ".bx-viewport"  (they both are wrapping the ul-element containing ".bxslider") arent deleted. So after a few reload-calls there are as much of these div`s as you called the reload-function. 
The solution described here: http://stackoverflow.com/questions/16283955/window-resize-with-bxslider-destroyed-breaks-style
did not work for me, as i wanted to refresh the slider on window-resize, and not destroy it completely.
right now i have to copy the html of $('.bxslider'), remove the whole $('.bx-wrapper')-element from DOM, reattach $('.bxslider') and init the slider again.

Thanks for any help!
Cheers

**Comment by viktorbijlenga** [comment]
I’m closing this. If you still need help, feel free to open the issue again.
