### ISSUE TITLE
Ticker mode issue with IE<=9 when the slider is not in DOM anymore

### ISSUE THREAD

**Issue by pyMan** [stevenwanderski/bxslider-4#264]
I experienced a problem when using bxSlider in ticker mode with IE8/9.

The slider is working fine, but when a portion of the DOM (that includes the slider) is replaced with some other content (via ajax) after few seconds I get the following error

"Impossibile recuperare la proprietà 'left' di un riferimento nullo o non definito"

that is something like

"Impossible to get 'left' property of a null or not defined object"

Somehow the plugin is trying to work with the slider object (to animate it obviously) that doesn't exists anymore and IE8/9 complain about its not existence instead of failing silently like other browsers do.

Note that this doesn't happen if I manually remove the object before the ajax call using $("#bxslider_id").remove() but this is not a solution I can rely on because of the site's nature.

My solution was patching the "tickerLoop" function inserting the next istruction as the first one.

if (!jQuery("#" + el.attr("id")).length) return; //It checks if the original element still exists

It works, but I don't write JQuery plugins so I'm not sure this is the right way.

I'd like this problem fixed.

Thanks in advance

**Comment by viktorbijlenga** [comment]
I’m closing this. If this still is an issue, feel free to open the issue again.
