### ISSUE TITLE
Carousel Examples

### ISSUE THREAD

**Issue by richardpeng** [stevenwanderski/bxslider-4#266]
Looks like the carousels on your example page are starting on the wrong set in Chrome:
http://bxslider.com/examples/carousel-demystified

Is this an issue with all carousels?

**Comment by Tidal-Wave** [comment]
Hey guys, I've been added to the project to help upkeep and maintain it.  I'm sorry for a lack of communication. 

I'm closing this issue due to duplication of above mentioned issue. This bug is a top priority and I hope to address it with my first update.
