### ISSUE TITLE
Fade Mode Not Working

### ISSUE THREAD

**Issue by EricHamby** [stevenwanderski/bxslider-4#275]
$('.slider0').bxSlider({
             auto: true,
             autoControls: true,
	     controls: false,
	    mode: 'fade',
       });

Trying to get the fade mode working with this and its not wanting to. Should i be doing somehting else to activate this? 

Using this example (http://bxslider.com/examples/auto-show-start-stop-controls)

Thank you.

**Comment by Tidal-Wave** [comment]
Closing due to age of issue and lack of example. I have created a simple example [here] (http://jsfiddle.net/ewafford/qvL1cxvw/) that shows your options working. 

@lithiumlab - we are aware of this issue and have a fix in the queue.
