### ISSUE TITLE
Override Slider options

### ISSUE THREAD

**Issue by tubenhirn** [stevenwanderski/bxslider-4#277]
Hey there,

I was thinking about a way to "override" the options set to the slider.

For example:

var myslider = jQuery('.slider').bxSlider({
speed:300
});

before doing something....

Set new:
myslider.setNewSetting({
speed:50
});

do something.....

Set back to to old:
myslider.setNewSetting({
speed:300
});

I was looking through the source but couldn't find something that fits my use here.

best regards
tube

**Comment by Tidal-Wave** [comment]
This can be achieved by passing new options to `reloadSlider()`
