### ISSUE TITLE
1 slide auto

### ISSUE THREAD

**Issue by jonmann20** [stevenwanderski/bxslider-4#280]
if (slider.settings.auto && slider.settings.autoStart) initAuto();

should check if there is more than one slide 
e.g.
&& getPagerQty() > 1

same for the pager:
var populatePager = function(){ 

should check that the pagerQty is greater than 1.

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/712, https://github.com/stevenwanderski/bxslider-4/issues/295, https://github.com/stevenwanderski/bxslider-4/issues/675. Closing due to duplicate issue. Looking to address this in our next update.
