### ISSUE TITLE
Idomatic javascript and less comments more tests

### ISSUE THREAD

**Issue by andredublin** [stevenwanderski/bxslider-4#283]
It would be great to clean up the code so its easier on the eyes.
I'd rather see
```javascript
if (slider.settings.slideMargin > 0) {
  height += slider.settings.slideMargin * (slider.settings.minSlides - 1);
}
```

instead of 

```javascript
if(slider.settings.slideMargin > 0) height += slider.settings.slideMargin * (slider.settings.minSlides - 1);
```

[idomatic js](https://github.com/rwldrn/idiomatic.js)

And there are way too many comments used as documentation, tests should reveal the intention of the code.

**Comment by Tidal-Wave** [comment]
Hello, i've been added to this project to help maintain it and provide updates. 

I appreciate the request here and will review this for a future update. Our next update is trying to focus on immediate needs atm, but we appreciate clean code and documentation and have plans to improve this in bxslider. 

Closing for now.
