### ISSUE TITLE
Slider floats break when using a large margin

### ISSUE THREAD

**Issue by dantman** [stevenwanderski/bxslider-4#286]
When a large slideMargin is used the floats can be broken because the large width calculated by this code is not enough:
```javascript
width: slider.settings.mode == 'horizontal' ? (slider.children.length * 100 + 215) + '%' : 'auto',
```

This issue can be fixed by doubling the slideMargin setting and adding that to the width. i.e add `slider.settings.slideMargin * 2` to the calculation.

**Comment by Tidal-Wave** [comment]
Closing due to duplicate issue https://github.com/stevenwanderski/bxslider-4/pull/481. Will fix in update.
