### ISSUE TITLE
Thumbnail Slider Should Slide

### ISSUE THREAD

**Issue by EricHamby** [stevenwanderski/bxslider-4#287]
Seems like the thumbnail slider should slide has you use the navigation. Very limited has to the number of slides you can use at the moment.

**Comment by Tidal-Wave** [comment]
Hey there, I'm Eric and i've been added to this project to help maintain it and provide updates. We agree that thumbnail paging should be improved, and will consider it as a feature request. Currently we are gearing up to address some outstanding issues so I'm closing this for now, but have assigned myself to it for a later date.
