### ISSUE TITLE
Add captions (titles) to videos

### ISSUE THREAD

**Issue by pipischnabel** [stevenwanderski/bxslider-4#294]
Hello everybody! 
I hope somebody can help me out. I created a video and image slideshow with bxslider and everything works perfect except the video captions.

For the images it looks like this and it's working fine:

<>img src="image/6.jpg" title="test image"/>

For the video i tried something like this but nothing happens:

    <iframe title="test video" src="http:///www.youtube.com/embed/cLCGAjY7q2w?rel=0" 
    width="680" height="480" frameborder="0"  webkitAllowFullScreen mozallowfullscreen allowFullScreen &showinfo=0></iframe>
 

Can anyone please help?

**Comment by azzimuth** [comment]
@pipischnabel How exactly did you manage to make it work?

**Comment by pipischnabel** [comment]
This is the code, but it's been so long and i am not so much into coding....Can't really remember if I did something else.     

<li>
          <iframe id="video_5" class="yt_players" src="your youtube link" width="680" height="377" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen ></iframe>
          <p>
             your captions
             </p>
        </li>
