### ISSUE TITLE
Hide Pager when maxSlide is equal to total slides

### ISSUE THREAD

**Issue by katart** [stevenwanderski/bxslider-4#295]
Is it possible to Hide the Pager when the total number of slides is visible in the bxslider viewport?

**Comment by Tidal-Wave** [comment]
Looking to address this with an upcoming update. Closing due to [duplicate](https://github.com/stevenwanderski/bxslider-4/issues/712) issue, also closing this mentioned PR request because it is to specific and doesn't address the issue completely.
