### ISSUE TITLE
multiple sliders with same controls

### ISSUE THREAD

**Issue by vwasteels** [stevenwanderski/bxslider-4#308]
It seems that I can't declare multiple slider and assign them to the same custom controls, like this :

``` html
<!-- my custom controls -->
<div class="bxslider-controls">
  <a class="pull-left" href="#"></a>
  <a class="pull-right" href="#"></a>
</div>
```

``` javascript
// launch multiple bxslider
$('.bxslider').each(function(){
  $(this).bxSlider({
    controls: true,
    nextSelector: '.bxslider-controls .pull-right',
    prevSelector: '.bxslider-controls .pull-left'
  });
});
```

This will add controls for each sliders instead of binding my custom controls on every slider. What I'am trying to do is having one custom control that controls all sliders.

Do you have any idea on how to achieve this ?

**Comment by lethy** [comment]
Hello, I would like to do the same , but with a 'mode : slide " and the second " fashion : fade . " Do you have an idea please ?

**Comment by Tidal-Wave** [comment]
We currently don't naturally support changing modes because the js setup is different. Fade mode stacks absolutely and slide mode doesn't.

**Comment by vwasteels** [comment]
@lethy try this : http://jsfiddle.net/vwasteels/38y9yxdz/
I haded a **data-mode** to each bxslider elements, and detect it while instantiating the sliders

**Comment by Tidal-Wave** [comment]
Oh, Im sorry, I misunderstood the question. I thought @lethy was wanting to change the slide mode on the same slider per slide. Like first slide fades, second slide slides, etc.

**Comment by lethy** [comment]
Thank you very much !
I'll test this right now !

**Comment by Gardezi1** [comment]
Hello I want a feature like this in bx-slider. Is there any way to do it

http://flexslider.woothemes.com/thumbnail-slider.html

**Comment by iwtw-richb** [comment]
Big thanks from me!!
