### ISSUE TITLE
Plain text as first slide gets converted to bx-loading and entire slider stops working

### ISSUE THREAD

**Issue by cliffordp** [stevenwanderski/bxslider-4#310]
If a slide consists of HTML (e.g. iframe), it works just fine as the leading slide.
However, if the leading slide is plain text (e.g. "I am plain text."), the plain text is not displayed (only the bx-loading spinning image is viewable) and the entire slider stops working.
If this same plain text slide is not the leading slide, the plain text slide works as expected.

**Comment by viktorbijlenga** [comment]
I’m closing this. If this still is an issue, feel free to open the issue again.
