### ISSUE TITLE
Bug next and prev controls after call method goToSlide()

### ISSUE THREAD

**Issue by AdrienQ** [stevenwanderski/bxslider-4#315]
After a call to goToSlide() method the next and prev control not working

I noticed that slider.working keep to true value

The method do a return if slider.working is true
if(slider.working || slider.active.index == slideIndex) return; (line 1098)

At the end of the method I added slider.working = false;
And It's working !

Adrien

**Comment by viktorbijlenga** [comment]
I’m closing this. If this still is an issue, feel free to open the issue again.
