### ISSUE TITLE
Active pager for the wrong slide

### ISSUE THREAD

**Issue by KlaasvnA** [stevenwanderski/bxslider-4#317]
Hello,

I made a custom pager for my '4 slides'-slider and added the following css:

.bx-wrapper .bx-pager a.active {color: #fff;}

When the first and the third slide are showing, there is no active pager-item. When the second slide is showing the pager-item for the first slide is active and when the fourth slide is showing the pager-item for the second slide get's active?

How can I fix this?

**Comment by viktorbijlenga** [comment]
I’m closing this. If you still need help, feel free to open the issue again.
