### ISSUE TITLE
Problem with slider after resize

### ISSUE THREAD

**Issue by n0th1nk** [stevenwanderski/bxslider-4#326]
Hi to all. My english too bad. Sorry for this.

Have some problem with slider after resize or F5. Look at images. Can upload .zip with my work.

![1](https://f.cloud.github.com/assets/5477308/1156467/279017b8-1f88-11e3-9af3-33a10fdf737b.JPG)
![2](https://f.cloud.github.com/assets/5477308/1156466/278a76b4-1f88-11e3-9af9-6dace9bc3275.JPG)

**Comment by viktorbijlenga** [comment]
I’m closing this. If this still an issue for you, feel free to open the issue again.
