### ISSUE TITLE
Thumbnail pager not working

### ISSUE THREAD

**Issue by thepixelmonk** [stevenwanderski/bxslider-4#33]
Here's my HTML:

```
<ul class="bxslider">
    <li><img src="myimage.png"></li>
    <li><img src="myimage.png"></li>
    <li><img src="myimage.png"></li>
</ul>

<div id="bx-pager">
   <a data-slide-index="0" href=""><img src="myimage_thumb.png"></a>
   <a data-slide-index="1" href=""><img src="myimage_thumb.png"></a>
   <a data-slide-index="2" href=""><img src="myimage_thumb.png"></a>
</div>
```

I am calling bxslider via: `element.bxSlider({ pagerCustom: '#bx-pager' })`

Part of the thumbnail pagers is working... as you switch slides (via the normal method) the 'active' class will switch elements. But clicking on the thumbnails doesn't do anything.

Thoughts?

**Comment by Mayuresh7** [comment]
please remove  pagerCustom: '#bx-pager' line from your code. it will work for you.
