### ISSUE TITLE
conflict with joomla email-cloaking plugin

### ISSUE THREAD

**Issue by salzkrabbe** [stevenwanderski/bxslider-4#341]
Hi,

first of all thanks for all your work! A component which I am using in Joomla has switched to your bxslider and since the update I am experiencing several issues. First one was that timestamp were added to images, which were causing the items not to load at all. I can see that this has been fixed with an update of your slider.

I installed the update but now the whole page breaks. Reason for this is a conflict with the Joomla email cloaking pluging, which adds further javascript to the side. Have you ever heard of such an issue? Is there any workaround besides deactivating the email cloaking? It used to work in the slider version, where the timestamps are added.

Thanks for your help!

BR,

Salzkrabbe

**Comment by Tidal-Wave** [comment]
Closing due to lack information and example. There are various ways to cloak emails in joomla, and it looks like some have tons of compatibility issues.
