### ISSUE TITLE
Form input IDs being duplicated.

### ISSUE THREAD

**Issue by dustensalinas** [stevenwanderski/bxslider-4#342]
inputs are duplicated if within a carousel list item.

Similar to the issue of old: https://github.com/wandoledzep/bxslider/issues/33

The code has changed substantially from the previous version however and previous hacks do not work, will look into it when I get a chance as well.

**Comment by Tidal-Wave** [comment]
The current way infinite scroll works is with clones. You will need to disable it. We will reevaluate how we do infinite scroll in a later update.
