### ISSUE TITLE
Artefacting then animating

### ISSUE THREAD

**Issue by VaclovasV** [stevenwanderski/bxslider-4#343]
You should enable gpu acceleration on main wrapper of slider, because not all browsers do this by default (chrome, safari).
This causes issues like here:
https://github.com/wandoledzep/bxslider-4/issues/186
and performance will be slower.

Reproduce steps:
go to http://www.cosmosupplylab.com/, zoom out, to see more elements. Slide and in chrome and safari, you will see moving elements.

if are using compass, the simple fix would be:
.bx-viewport{
	@include translateZ(0);
}

this will enable gpu acceleration and prevent from artefacting.

Good luck!

**Comment by Tidal-Wave** [comment]
Closing. This has been fixed to a degree, but forcing this can also cause font render issues in webkit.
