### ISSUE TITLE
Strange responsive style behavior on iPhone

### ISSUE THREAD

**Issue by wichertandre** [stevenwanderski/bxslider-4#348]
Hi - first of all, I would like to congratulate for that great plugin.

I've implemented a demo for testing purposes with responsive styles <a target="_blank" href="http://wunschformat.de/kunden/bxslider_test/">here</a> - as you can see in your normal browser the styles for font-size are used correctly. The upper container is a reference for the size of the font.

If you view the same page on a <em>real</em> iPhone (Safari, Chrome, ...) the styles within the slider aren't displayed correctly. Am I the only one with this strange behavior?

Thank you for response.

**Comment by Tidal-Wave** [comment]
Closing as resolved but assigning it for review in update 4.3 when we redo css.

**Comment by WandileChamane** [comment]
Noted Thanks!.

On Tue, Jan 20, 2015 at 8:48 PM, Eric Wafford <notifications@github.com>
wrote:

> Closed #348 <https://github.com/stevenwanderski/bxslider-4/issues/348>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenwanderski/bxslider-4/issues/348#event-221806442>
> .
>



-- 
Wandile

**Comment by talhazahid** [comment]
@vicvinegar  thanks buddy you solved my problem (y)
