### ISSUE TITLE
Slider paging not working correctly in Ipad landscape mode

### ISSUE THREAD

**Issue by vadhul** [stevenwanderski/bxslider-4#349]
I was testing the slider recently using ipadpeek.com and I noticed that in the landscape mode, there is a paging issue (Note the page 2/1)  in the attached image. Also, note that the first item in the slide is getting clipped. i.e it does't get as much width as the other 2 items in the slide. Please let me know if there is a workaround for this. Here is the configuration I used for the slider.
$('.options').bxSlider({
                            slideWidth: 200,
                            minSlides: 1,
                            maxSlides: 4,
                            slideMargin: 5,
                            infiniteLoop: false,
                            pager:true,
                            pagerType: 'short',
                            controls: true
                        });

![slider](https://f.cloud.github.com/assets/3492325/1289744/756d474a-3026-11e3-8907-b3e5bbce7932.png)

**Comment by Tidal-Wave** [comment]
Closing due to lack of working example of issue. We cannot diagnose images. If you need help, please reopen with a working example of the issue.
