### ISSUE TITLE
Two finger pinch zoom not working when horizontal swiping is enabled.

### ISSUE THREAD

**Issue by emanuelsdlc** [stevenwanderski/bxslider-4#351]
When the horizontal swipe function is enabled for touch devices (touchEnabled = true) you can no longer use the two finger pinch to zoom gesture to zoom in or out. 

The pinch to zoom only works when the fingers are placed on an area that is not part of the slider. So for large sliders, which take up most of the screen this is a big problem because it basically makes it impossible to change the zoom.

Problem occured on iOS 6 as well as Android 4.3

**Comment by Tidal-Wave** [comment]
Currently no. We will evaluate this issue for a future release.

**Comment by Math3wC** [comment]
is anyone looking into the issue yet?
I'm using this plugin and have the same issue, can zoom in using iOS7&8. While can't zoom in for Android 4.4.2 with Android 5 devices.

**Comment by RobertoMantas** [comment]
Is there any solution for this issue?? Having the same problem here
