### ISSUE TITLE
problem with vertical slideshow on chrome and firefox

### ISSUE THREAD

**Issue by kingk110** [stevenwanderski/bxslider-4#352]
I am using the following code to create a autoslider that doesn't scroll:
http://pastebin.com/3M2JdXQa

but the images are shown as this in the link (this printscreen was not taken in the animation of the slider; I mean it is taken while the slider is not moving):
http://s23.postimg.org/uc3sbweff/slider.png

I tired to remove the div footer but it is ithe same, and I think that it must work with it normally.

in explorer it is working well.

**Comment by viktorbijlenga** [comment]
I’m closing this. If this still an issue for you, feel free to open the issue again.
