### ISSUE TITLE
display two rows

### ISSUE THREAD

**Issue by DivMaster** [stevenwanderski/bxslider-4#353]
Can we display two rows in one slider?
Thanks

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and age. You can put whatever you want in a slide for the most part. You can also wrap to slides together. You cannot make one slider stack slides 2 up.

**Comment by jayllellis** [comment]
Yes, it's possible, Just put 2 images (and display block) per slide. See here: https://codepen.io/cfaria/pen/vLVxvR
