### ISSUE TITLE
preloading stack if there a missing image

### ISSUE THREAD

**Issue by idanilt** [stevenwanderski/bxslider-4#357]
the  preloading get stacked if you have a missing picture
to fix this you need to change line 275 from 
$(this).one('load', function() {

to
$(this).one('load error', function() { 

this way if there is a missing picture it will still increase the counter

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/560. Closing due to duplicate issue. We are aware of issues with images not loading, and are looking to address this soon in an update.
