### ISSUE TITLE
windows phone 8

### ISSUE THREAD

**Issue by christian70** [stevenwanderski/bxslider-4#368]
did anybody find any issue with windows phone 8? on my site the slider is perfectly working on most browsers and devices (also ipad and other touch enabled devices) except on my nokia with windows phone 8. On it the slider is stuck to the first image, the swipe feature doesn't work and nor the pagination links does. any suggestion to fix it? is it an already known issue or just my fault? thanx.

**Comment by Tidal-Wave** [comment]
Sorry for any lack of communication, I have been added to this project to maintain it. We are looking to include fixes for this in our next update. Closing for housekeeping purposes. Related to https://github.com/stevenwanderski/bxslider-4/pull/596.

**Comment by timholz** [comment]
@PulkitRangwani 
Thank you for the solution. I tested nokia (930/925) devices on browserstack. Looks good.
All the best to you
theo
