### ISSUE TITLE
New fade style.

### ISSUE THREAD

**Issue by arczas89** [stevenwanderski/bxslider-4#369]
Now is something like that: 

actualpicture.fadeOut()
nextpicture.fadeIn()
 
in the same time. We see the background during animation.

	
proposition for new fade effect:

actualpicture - still visible
nextpicture.fadeIn()

in the same time.

when fadeIn done actualpicture.hide()

**Comment by Tidal-Wave** [comment]
Will consider adjustments to transitions in 4.3 update. Closing for now.
