### ISSUE TITLE
Allow CSS to control my slideWidth

### ISSUE THREAD

**Issue by timkelty** [stevenwanderski/bxslider-4#371]
I'm wondering if it is possible, or if there is any planned feature for being able to NOT set `slideWidth` property, and instead let my already defined css control the widths.

The reason being, I have several breakpoints along the way that may cause the slide to either need to scale down or up, so I want to be able to just do all my widths in css.

This is similar to how Filament Group's Responsive Carousel works:
http://filamentgroup.github.io/responsive-carousel/test/functional/responsive-containers.html

**Comment by Tidal-Wave** [comment]
We are looking to improve responsiveness in a future update.
