### ISSUE TITLE
Need to fix about last items position

### ISSUE THREAD

**Issue by eddstep** [stevenwanderski/bxslider-4#374]
The position of last items is wrong, when option 'infiniteLoop: false'

For example  config is 
 $('.bxslider').bxSlider({
    slideWidth: 98,    
    minSlides: 5,
    maxSlides: 5,
    moveSlides: 5,
    infiniteLoop: false,
    hideControlOnEnd: true,
    preloadImages: 'visible',
});

so each time, when sliding <ul> has attribute "width: 4215%; position: relative; -webkit-transition: 0s; transition: 0s; -webkit-transform: translate3d(0px, 0, 0)" where  translate3d(0px, 0, 0) gets -490px left each time, but when click last slide point, it gets 392px instead -3430px.

**Comment by Tidal-Wave** [comment]
Closing due to lack of working example of issue and improper markdown. Please provide examples and submit issues using proper markdown in order for use to help you.

**Comment by emmasax** [comment]
I am also having an issue that involves this particular problem with translate3d values.

I have a working demo of when it happens - https://jsfiddle.net/zLLk6Lgt/8/

Go to last slide and then reload the slider. The position of the last slide is now incorrect.
