### ISSUE TITLE
When auto: true, it always scrolls, even with only 1 page

### ISSUE THREAD

**Issue by johndubya** [stevenwanderski/bxslider-4#376]
Here is my call:

$('.bxslider').bxSlider({
    auto: true,
    maxSlides: 6,
    minSlides: 2,
    randomStart: true,
    slideMargin: 10,
    slideWidth: 100
});

When my slider only has, say, two items in it that are on one page, the slider will slide left, even though there are no other pages. There is only one page indicator also, so it knows there is only one page.

If any more information is needed from me, let me know please.

**Comment by Tidal-Wave** [comment]
Closing due to duplication of issue https://github.com/stevenwanderski/bxslider-4/issues/712. 
Fixing in upcoming update.
