### ISSUE TITLE
Not functioning for me

### ISSUE THREAD

**Issue by cableghost** [stevenwanderski/bxslider-4#378]
Couple issues...

1. Line items are leaving the icons/dots

2. Though it's working outside above, I feel there may be some type of conflict as I already have jquery loading via another source

source: /wp-includes/js/jquery/jquery.js?ver=1.10.2

Please see:

http://jensfitcenter.com/test/

Thanks, Scott

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and working example of issue. There should be no issues with either problem. Most likely user error.
