### ISSUE TITLE
Only show entire slides in slider

### ISSUE THREAD

**Issue by Akela2606** [stevenwanderski/bxslider-4#388]
Hi everybody,
I hope I'm posting this question in the right place...

I'd like to have the slider only showing entire slides (according to the width of the browser window). Can anybody tell me if this is possible and how?

Thank you very much for your help.

(sorry, I tried to mark the issue as question but I'm new to Github and didn't manage to do it...)

**Comment by Tidal-Wave** [comment]
This can be done with the `minSlides` and `maxSlides` set to 1.
