### ISSUE TITLE
Verticle Mode ignores maxSlides option

### ISSUE THREAD

**Issue by MikoLone** [stevenwanderski/bxslider-4#390]
I want use vertical mode as an alternative to scrolling. The problem I ran into was that when I added maxSlides:4 it ignores it and only displays 1 item. 

![verticalscrolling](https://f.cloud.github.com/assets/207042/1576349/938416fe-515b-11e3-8b92-60c2e0f243fd.png)

Sidenote: The other thing I wanted for vertical was to put the arrows on the top and bottom instead of the left and right side. With arrows going up and down. That doesn't bother me that much though because I know I can do that by just adding my own styles to the buttons.

**Comment by Tidal-Wave** [comment]
Closing due to age and lack of working example. We cannot diagnose images.
