### ISSUE TITLE
Custom pager disappears on destroy (reinitialize) slider

### ISSUE THREAD

**Issue by mrukavishnikov** [stevenwanderski/bxslider-4#394]
When using custom pager with slider ("pagerCustom" option). Custom pager disappears from page code together with slider on destroying slider. 

Steps to reproduce:
1. Create custom pager buttons
2. Init slider with pagerCustom option
3. Destroy slider

Result: custom pager buttons disappeared.

Expected result: If custom pager used, it should remain as it was, only embedded pager should be afected on destroying. 

This bug makes impossible to temporary destroy slider and reinitialize it again when using custom pager buttons.

**Comment by fxalvarezd** [comment]
Same here, custom pager gets removed from the dom.

**Comment by Tidal-Wave** [comment]
:+1:

**Comment by herbertgatchalian** [comment]
still having this issue with the latest release :( anyone help please :( i tried stokey's solution. not working :(
