### ISSUE TITLE
No-spinner in fade mode

### ISSUE THREAD

**Issue by stks** [stevenwanderski/bxslider-4#410]
I have a slider where I use really big images, long loading time. Everything works fine on horizontal and vertical mode, bxslider displays a spinner that shows that the slider is loading and maintains the height of first image. But if I use the slider in the fade mode the spinner is not there and the bx-loading element has no height, making the slider collapse.

I attached a screenshot:
http://awesomescreenshot.com/08223qiv1f

**Comment by Tidal-Wave** [comment]
Fade mode absolutely positions images on each other. This is what is causing your issue. Specify a height to fix the issue. We are looking to improve this at a later date.
