### ISSUE TITLE
Two sliders with one navigation

### ISSUE THREAD

**Issue by Matrinkoo** [stevenwanderski/bxslider-4#413]
Hello,

In my new project I need two sliders (or one slider conected with tabs).

Here is example
http://oi39.tinypic.com/2yyxxlx.jpg

When I click on the NEXT or PREV  (of the top slider) content ( in red box under the slider) must change to another content.

I need connection between two red boxes with one navigation. It must be synch.

Can you help me with it?

(sorry, my english is very bad)

**Comment by Tidal-Wave** [comment]
This can be achieved with javascript connected to a common selector to control both slides.
