### ISSUE TITLE
Touch is not working in window 8 Firefox, IE and Safari browser.

### ISSUE THREAD

**Issue by des2nakulsoft** [stevenwanderski/bxslider-4#417]
Touch is not working in window 8 Firefox, IE and Safari browser.
Please provide the solutions ASAP. We got stuck in our important project. Kindly help us.

**Comment by Tidal-Wave** [comment]
Closing due to duplicate issue https://github.com/stevenwanderski/bxslider-4/pull/596. Will address in update.
