### ISSUE TITLE
Custom pager

### ISSUE THREAD

**Issue by ARCITEX** [stevenwanderski/bxslider-4#419]
i used custom pager in my new project but have problem with that

this is my html code

< div class="slider">
    < div class="slider-pager">
        < a data-slide-index="0" href="">
            < div class="slider-entry">
                < p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing
                < /p>
            < /div>
            < div class="slider-btn">
                < ul>
                    < a href="#">
                        < li>GET STARTED
                        < /li>
                    < /a>
                    < a href="#">
                        < li class="active">READ MORE
                        < /li>
                    < /a>
                < /ul>
            < /div>
        < /a>
        < a data-slide-index="1" href="">
            < div class="slider-entry">
                < p>
                    Pellentesque habitant morbi
                < /p>
            < /div>
            < div class="slider-btn">
                < ol>
                    < a href="#">
                        < li>GET STARTED
                        < /li>
                    < /a>
                    < a href="#">
                        < li class="active">READ MORE
                        < /li>
                    < /a>
                < /ol>
            < /div>
        < /a>
    < /div>
< /div>
                    < div id="featured-slider">
                        < a href="">
                            < img src="./images/slide-show/slide1.jpg" class="img-responsive" title="Your Image Caption to Go Here" alt="alternative information">
                        < /a>
                        < a href="">
                            < img src="./images/slide-show/slide2.jpg" class="img-responsive" title="Your Image Caption to Go Here" alt="alternative information">
                        < /a>
                        < a href="">
                            < img src="./images/slide-show/slide3.jpg" class="img-responsive" title="Your Image Caption to Go Here" alt="alternative information">
                        < /a>
                    < /div>

and this is my js config:

// ================================================
// featured slider
// ================================================
$('#featured-slider').bxSlider({
    pagerCustom: ".slider-pager",
    controls: false,
    minSlides: 1,
    maxSlides: 1,
    auto: true,
    mode: "horizontal",
    controls: true,
    autoHover: true,
    preloadImages: "all",
    prevText: '< i class="icon-angle-left"></i>',
    nextText: '< i class="icon-angle-right"></i>',
    captions: true
});

the problem is , every 'a' inside < div class="slider-pager"> code take active class but i want just 2 'a' with data-slide-index have this class not every 'a' inside them.

**Comment by Tidal-Wave** [comment]
Closing due to unformatted example. Please post clean examples of issues using a service or proper markdown.
