### ISSUE TITLE
Issue when exiting full-screen mode in Firefox

### ISSUE THREAD

**Issue by nickpish** [stevenwanderski/bxslider-4#426]
I'm noticing a strange issue that occurs with the slider in Firefox when *exiting* from full-screen mode in the browser. I have a test page set up [here](http://nickpish.com/_dev/donati-bx)
![bxslider-issue](https://f.cloud.github.com/assets/4361220/1945074/92bbb6e8-7fc6-11e3-80f5-9bde881e100f.png)
 and I'm including an image that depicts the problem. The behavior can be replicated by clicking on the full screen icon in the image viewer above the slider. It almost seems like some kind of a re-draw problem in which the rendering of the slider breaks when exiting from full-screen mode. I've noticed that resizing the browser window "resets" the slider, making it render properly.

Any idea what's causing this? Note that I'm seeing this behavior *only* in Firefox (Chrome, Opera and IE don't seem to have the problem.)

Thanks for any insight here.

**Comment by Tidal-Wave** [comment]
Closing due to example being down.
