### ISSUE TITLE
infiniteLoop glitch when scrolling from first to last slide (with Fix)

### ISSUE THREAD

**Issue by thdoan** [stevenwanderski/bxslider-4#429]
There's a glitch where when you move from the first slide to the last slide, there is an unintended bounce effect when the last slide transitions into the viewport. In order to reproduce this, make sure the images inside the slider span 100% the width of the screen.

UPDATE

I have identified the issue: when you move from the first to the last slide, the following -webkit-transform animations are applied (assuming two 100% width images in the slider):

1. translate3d(0px, 0px, 0px);
2. translate3d(-2570px, 0px, 0px)

Animation 1 is causing the bounce effect as it indents the image.

PROBLEM

The problem is this condition will never be met for one-image sliders because slider.carousel would return false:

				}else if(slider.carousel && slider.active.last && direction == 'prev'){

FIX

I don't think the slider.carousel requirement is necessary in this context, so to fix this change line 1163 to this:

				}else if(slider.active.last && direction == 'prev'){

I just tested this and the bounce glitch is fixed for one-image carousels.

**Comment by robinjessome** [comment]
In case anyone stumbles on this like I did, and is using the minified version, you're looking for this, near the end:
`o.carousel&&o.active.last&&"prev"==i`

Thanks @thdoan for the workaround!

**Comment by Tidal-Wave** [comment]
Just so everyone know, this is in fact not the correct fix. I will be pushing the correct fix in 4.2.2 update.

**Comment by robinjessome** [comment]
@Tidal-Wave - awesome!

**Comment by Tidal-Wave** [comment]
Fixed in 4.2.2
