### ISSUE TITLE
Slider loads last image first (with Fix)

### ISSUE THREAD

**Issue by thdoan** [stevenwanderski/bxslider-4#432]
When infiniteLoop is enabled, the slider often loads showing the last image first on my system (if you can't reproduce it, try disabling browser cache and reloading using F5). Looking at the console, it seems that the slide is set to this initially:

`webkit-transform: translate3d(-40px, 0px, 0px)`

`-40px` points to the first cloned image, which is a cloned copy of the last image in the list (used in infinite scrolling). In this case, the setSlidePosition() function is not setting the correct initial position, possibly because it is somehow executing before the cloned elements are inserted by `el.append(sliceAppend).prepend(slicePrepend);`? I'm scratching my head...

UPDATE

After looking at the code, I understood what was happening -- setSlidePosition() is not yet aware of the infiniteLoop option. Here's the fix (beginning on line 494):

```javascript
// get the position of the first showing slide
var firstIndex = slider.active.index * getMoveBy(),
  position = slider.children.eq(firstIndex).position();
// check for last slide
if (slider.active.index == getPagerQty() - 1) slider.active.last = true;
// set the repective position
if (position != undefined){
  if (isVertical) {
    if (slider.settings.infiniteLoop) position.top = (slider.active.index + 1) * slider.children.eq(firstIndex).outerHeight(true);
    setPositionProperty(-position.top, 'reset', 0);
  } else {
    if (slider.settings.infiniteLoop) position.left = (slider.active.index + 1) * slider.children.eq(firstIndex).outerWidth(true);
    setPositionProperty(-position.left, 'reset', 0);
  }
}
```

**Comment by Tidal-Wave** [comment]
This issue should be addressed in 4.2.3, let me know if it isn't.
