### ISSUE TITLE
How to add a CSS class to the middle slide

### ISSUE THREAD

**Issue by reardestani** [stevenwanderski/bxslider-4#437]
Hi,

Look at this [page](http://bxslider.com/examples/carousel-demystified) example 4. 
How it is possible to add a CSS class (e.g. scale-animation) to the middle slide? By "middle slide", I mean the one that is at the center of carousel. Look below image.

![examples responsive jquery slider bxslider](https://f.cloud.github.com/assets/2968507/2001386/938aec06-85a7-11e3-82e0-0e488ab7f1af.jpeg)

Consider that the class should toggle when the middle item changes.

What I am going to do with this class:
Actually, I want to make the middle slide bigger and show its chaption under it. As other slides are smaller.

Can you give me any help?
Regards,

**Comment by CurtisBelt** [comment]
For people still searching for the answer to this question:

CSS nth-child will not work.

Use the `onSlideAfter` callback. From there, you are given `element`. Using `.next()` you can easily manipulate the 3 slides.

```
onSlideAfter: function ( element, oldIndex, newIndex ) {
	element.removeClass( 'center-slide' ); // First Slide
	element.next().addClass( 'center-slide' ); // Center Slide
	element.next().next().removeClass( 'center-slide' ); // Last Slide
}
```
