### ISSUE TITLE
jQuery 1.11 - sliding troubles with horizontal bxSlider and using useCSS

### ISSUE THREAD

**Issue by centi** [stevenwanderski/bxslider-4#440]
When I use a horizontal slider with `useCSS` set to `true`, and have the new release of jQuery (1.11.0), then the sliding does not work properly. When sliding to the second slide, the CSS `translate3d` property is removed from the slider, so the UI is rendered incorrectly.

I prepared a little test-case: http://jsfiddle.net/LUsgq/2/

When you click on the "next" button, the "Item 2" slide is appearing, but then it "jumps" to slide 4 (the clone of the last slide to be exact).

**Comment by Tidal-Wave** [comment]
Fixed in current version.
