### ISSUE TITLE
IE9 slider doesn't slide : Object doesn't support property or method 'easeInOutQuart'

### ISSUE THREAD

**Issue by yuvilio** [stevenwanderski/bxslider-4#441]
Ran into this issue. I uncovered it by running the slide click via jQuery: ```jQuery('#slider-next').click();```

I got this error:

```Object doesn't support property or method 'easeInOutQuart'```

Workaround was commenting the easing functionality. 

[SO answer](http://stackoverflow.com/a/21437936/462002)

**Comment by Tidal-Wave** [comment]
'easeInOutQuart' is not natively supported. Please review the [docs] (http://bxslider.com/options) for easing.
