### ISSUE TITLE
[Question] custom transition mode 

### ISSUE THREAD

**Issue by TineHorvat** [stevenwanderski/bxslider-4#443]
Hey everyone,
I'm trying to get a new transition effect for bxslider, but I'm not sure if this is the correct approach.
This is what I have so far: http://jsfiddle.net/wilfff/6KAFt/
What i'm trying to achieve is this effect: http://webstuffshare.com/demo/FlippingSlider/index.html
Any help will be appreciated!
Cheers! :)

**Comment by Tidal-Wave** [comment]
Currently we don't support adding transitions. We will consider this for a future update. 

What you are doing is going to be as close as you get atm.
