### ISSUE TITLE
Help .... Step 3: Call the bxSlider

### ISSUE THREAD

**Issue by studiomatter** [stevenwanderski/bxslider-4#449]
First of all, thanks so much for Bxslider. I would like to use this slider on my website. But, I am having hard time to figure out "Step 3" part. According to the introduction, "call must be made inside of a $(document).ready() call, " I do not understand where and how...I should put this part...  I tried to paste on <head> with <script> .....</script>. But it doesn't work either.  Could anybody kindly explain me...?  I would appreciate to see as an example.. ...   Thanks so much......  

"$(document).ready(function(){
  $('.bxslider').bxSlider();
});"

**Comment by viktorbijlenga** [comment]
This issue seems to be solved. I’m closing it.
