### ISSUE TITLE
Vertical Ticker Mode Speed Changing!

### ISSUE THREAD

**Issue by Waqass** [stevenwanderski/bxslider-4#450]
I have all things setup but only one problem is occuring. The slide loads ok everything is working fine ...i am using ticker mode with ticker hover to stop slide on hovering but after hover when the move is removed the speed of slide changes it slows down for some seconds and sometimes come back to the original speed. What is wrong here! i am using useCss false as to use ticker hover!

**Comment by hirakps** [comment]
Please use the following code at line 301:
if(o.settings.ticker == true){
	e = 30000; //set the user defined speed value
}

**Comment by Tidal-Wave** [comment]
sounds like it's having an issue calculating the timing to finish the loop on pause. Looking at this for the next sprint currently being done.

**Comment by Tidal-Wave** [comment]
This issue will be resolved in 4.2.4 which will be release shortly. Thanks for the report.
