### ISSUE TITLE
Leaks Memory

### ISSUE THREAD

**Issue by designcise** [stevenwanderski/bxslider-4#456]
1: Loader shows infinitely if images don't load or are broken.

2: If images are broken or not loaded, and browser window size is small (tried at width 480px), the browser leaks memory (tried in IE9 and Chrome).

Seems like it's already being discussed/worked on: https://github.com/wandoledzep/bxslider-4/issues/136

**Comment by Tidal-Wave** [comment]
Closing due to duplication.
