### ISSUE TITLE
FIX - Slider not going to first slide after last slide

### ISSUE THREAD

**Issue by MaxxAstral** [stevenwanderski/bxslider-4#458]
I was having this problem that the slider was not going to the first slide after the last slide, even infiniteLoop is set true.
To fix this i had to make this changes to  el.goToNextSlide 
```js
el.goToNextSlide = function() {
            // if infiniteLoop is false and last page is showing, disregard call
            if (!slider.settings.infiniteLoop && slider.active.last) {
                return;
            }
            var pagerIndex = parseInt(slider.active.index) + 1;

            if (slider.active.last && slider.settings.infiniteLoop) {
                
                el.goToSlide(0, 'prev');
            } else {
                el.goToSlide(pagerIndex, 'next');
            }
        }

```

Now it works but in the last slide , but the animation that shows is the previous slide transition effect.

**Comment by Tidal-Wave** [comment]
Closing due to possible duplicate issue https://github.com/stevenwanderski/bxslider-4/pull/481. Looking to fix infinite scroll in upcoming update.
