### ISSUE TITLE
Odd Image Sizing on Page Reload / Delayed Load of Background Image

### ISSUE THREAD

**Issue by emRae** [stevenwanderski/bxslider-4#469]
Hello,

First, thanks for all the hard work putting together this slideshow! I have been using it as a basic responsive slideshow for our CMS.

I'm a beginner with Javascript so please bear with me. I have added the slideshow here: http://dev.charisbiblecollege.infront.com/ and here: http://dev.charisbiblecollege.infront.com/extension-home-template-style-guide

The problem is that when you reload the page the background image is temporarily resized oddly. I've also seen it flash all the slides content in a list before the styling fixes everything.

Any ideas on how I can remedy these delays in styling/loading? I'll be looking into it more myself but would love a second eye.

Thanks!

**Comment by Tidal-Wave** [comment]
FOUC issues can be resolved by hiding slider until load. We are looking to better address this in a future update.
