### ISSUE TITLE
Images become bigger when page is reloaded

### ISSUE THREAD

**Issue by marcopanichi** [stevenwanderski/bxslider-4#471]
Hi to all,

i have created a website using Twitter Bootstrap. I'm using bxslider succesfully (thanks for this great plugin!) but when I reload the page the images become enourmous:

BEFORE (OK!)
![before](https://f.cloud.github.com/assets/4515225/2321093/fe4d1aca-a39b-11e3-9486-ffb54e9d1313.png)

AFTER (BAD!)
![after](https://f.cloud.github.com/assets/4515225/2321094/fe539710-a39b-11e3-8f7f-ffaddfbe209e.png)

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and working example. We cannot diagnose images. Please feel free to reopen with the above if you need help.
