### ISSUE TITLE
Carousel slide order breaks on certain versions of jQuery (1.11.0 and 2.1.0)

### ISSUE THREAD

**Issue by jameydeorio** [stevenwanderski/bxslider-4#482]
On certain versions of jQuery (2.1.0 and 1.11.0 from what I've seen), carousels quickly replace the second set of slides with the last set after transitioning, and then behavior with "previous" and "next" becomes strange, with "previous" moving forward and item positions seemingly moving around. Oddly, it works on jQuery 2.0.2 but breaks again on latest.

Fiddle: http://jsfiddle.net/zzGHj/4/

**Comment by Tidal-Wave** [comment]
https://github.com/stevenwanderski/bxslider-4/pull/472 fixed. Closing.
