### ISSUE TITLE
can I upgrade from 3.0 to 4.1.1?

### ISSUE THREAD

**Issue by tyunderwood** [stevenwanderski/bxslider-4#483]
I have a site currently running BxSlider 3.0, could I replace that script with the current version cleanly, or would I need to change its implementation as well? I am looking to add touch event functionality to the site's sliders.

**Comment by Tidal-Wave** [comment]
Please always test major updates on a development environment. before deploying to production sites. As a new maintainer I cannot speak to any changes from v3 to v4. Without more information and a link to your current install I cannot determine if there would be any issue.
