### ISSUE TITLE
Bx Slider makes other elements on the page moving (on Chrome)

### ISSUE THREAD

**Issue by jonathantsilva** [stevenwanderski/bxslider-4#485]
when a slide is running, some elements further in the page are moving at the same time. 

The solving for this problem, is adding this css to the ".bx-viewport" div.

.bx-viewport {
    -webkit-transform: translatez(0);
    -moz-transform: translatez(0);
    -ms-transform: translatez(0);
    -o-transform: translatez(0);
    transform: translatez(0);
}

I found that solving at:
http://stackoverflow.com/questions/16480829/bx-slider-makes-other-elements-on-the-page-moving-on-chrome

**Comment by Tidal-Wave** [comment]
Closing due to duplicate issue. There are some known issues with WebKit as it relates to text and transforms.
