### ISSUE TITLE
Carousels images 'chopping off' on certain tablet sizes

### ISSUE THREAD

**Issue by mossyboy** [stevenwanderski/bxslider-4#489]
Is it possible to have just whole images on all screen sizes and not have them chopping off at the side? I have tried playing around with various slide widths but it fixes one size but then affects another size. I would have thought the images would resize to fit screen sizes. Please see screenshot attached and the website is at www.blackpandadesign.co.uk

Thanks for any help.
![screen shot 2014-03-23 at 19 02 20](https://f.cloud.github.com/assets/1230806/2494267/1852fe68-b2be-11e3-913f-006242ec918b.png)

**Comment by Tidal-Wave** [comment]
This is currently intended behavior due to how responsiveness is dealt with. We will consider this enhancement at a later date.
