### ISSUE TITLE
BxSlider display always last slide after the first image

### ISSUE THREAD

**Issue by Pepozzo** [stevenwanderski/bxslider-4#504]
Hello!

I'm using BxSlider with jQuery jquery-1.11.0.min.js.

The slide display well, but using navigation button trying to see another image, bxslider starts to show only the last image (last li elemnt).

Here you can check a rapresentation: http://test.7it.it:81/arredamentisimonazzi/realizzazioni/realizzazione.html?real=Bar%20Erg

**Comment by watarumohawk** [comment]
I found the bug by using jquery 1.9.1, and then I used jquery 1.11.2. It seemed the bug was fixed at first, but it still happens. In my case, using jquery 1.11.2 is better than using jquery 1.9.1.

**Comment by watarumohawk** [comment]
For your information, this bug has been reported before. #432

**Comment by Tidal-Wave** [comment]
This issue should be addressed in 4.2.3, let me know if it isn't.
