### ISSUE TITLE
viewport height isn't calculated until first slide advances

### ISSUE THREAD

**Issue by melliotson** [stevenwanderski/bxslider-4#508]
Love the slider, but having issues with height calculations on the viewport.

Desktop Chrome and FF work great. Desktop Safari doesn't calculate proper height until the first slide advances.

iPad and iPhone (iOS7) Chrome and Safari don't calculate proper height until the first slide advances.

Test template here > http://www.markelliotson.com/projects/courier/

I cannot set a fixed height on the viewport in CSS b/c this needs to be responsive.

Not sure what I'm missing ... help would be immensely appreciated! Thanks!

**Comment by marcelbirrer** [comment]
Same issue over here: http://www.buero-b.ch/projekte/
Slider is working nicely in every desktop browser, but Safari on iOS 7 images are not shown. iOS 6 or 8 is working though... any help would be very appreciated!

**Comment by Tidal-Wave** [comment]
@marcelbirrer - In testing it seems your site is working properly in IOS7. Can you provide anymore information?

![screen shot 2015-03-27 at 2 49 22 pm](https://cloud.githubusercontent.com/assets/4382867/6875875/90f8d00a-d490-11e4-915b-0ac46ee1cdad.png)

**Comment by Tidal-Wave** [comment]
Removing from 4.2.4 milestone until more information can be provided.

**Comment by marcelbirrer** [comment]
Hello! Thanks for testing - just found a workaround yesterday by adding: «slider.goToSlide(0);» after the call and choosing «preloadImages: 'all'» as option.

jQuery(document).ready(function() {
	var slider = $('.bxslider').bxSlider({
		preloadImages: 'all',
  	pagerType: 'short',
  	pagerShortSeparator: '&nbsp;/&nbsp;',
  	prevText: '>',
  	nextText: '<',
  	onSliderLoad: function(index){
  		var count = 0;
			$('ul.bxslider li').each(function() {
				if (count == index) {
					if($( this ).hasClass("arrow_light")) {
						$(".bx-prev").addClass("light");
						$(".bx-next").addClass("light");
					}
				}
				count = count + 1;
			});
  	},
  	onSlideAfter: function(slideElement){
			if(slideElement.hasClass("arrow_light")) {
					$(".bx-prev").addClass("light")
					$(".bx-next").addClass("light")
			}
			else {
					$(".bx-prev").removeClass("light")
					$(".bx-next").removeClass("light")			
			}
  	}
	});
	slider.goToSlide(0);
});

**Comment by Tidal-Wave** [comment]
Closing then for the moment. Let me know if there is anything else.
