### ISSUE TITLE
BxSlider minSlide: 1 Issue

### ISSUE THREAD

**Issue by notflip** [stevenwanderski/bxslider-4#511]
When using minSlide: 1 and rescaling the browser to mobile, I can't use the next and previous buttons, Also the pager doesn't work, When there's 2 slides visible it is working

This is my code
```
$('.specialiteiten-slider').bxSlider(
{
	slideWidth: 500,
	minSlides: 1,
	maxSlides: 5,
	moveSlides: 1,
	slideMargin: 5
});
```

![bx](https://cloud.githubusercontent.com/assets/4146384/2705485/de5e45be-c47e-11e3-8ace-3568b7016a06.jpg)

**Comment by Tidal-Wave** [comment]
Closing due to lack of information or working example of issue. We cannot diagnose images. If you are still having an issue please reopen with more information and an example.
