### ISSUE TITLE
bx-slider freezes on ios. detailed description inside…

### ISSUE THREAD

**Issue by nicmare** [stevenwanderski/bxslider-4#515]
I am on latest ios. iphone4s and ipad4. no matter if using jquery 1.11 or 2.1, or one bxslider or three instances or which options i use. its allways the same problem. as long i touch them horizontal everything is fine. but if you have big pages, you scroll along vertical axis. and obviously bxslider does not like touched vertically and horizontal at one time. when i do it, it freezes. then nothing helps. even slider.goToNextSlide(); wont work. i even cant scroll the page anymore because the sliders are very big. seems that it prevents default swipes for x and y axis. i have to reload the page. i tested it several times. its allways the same. how can i help/assist you in fixing this?

**Comment by smohadjer** [comment]
I fixed this problem among some other in my fork: https://github.com/smohadjer/bxslider-4

**Comment by Tidal-Wave** [comment]
Thank you for your work @smohadjer, I will be reviewing it for our planned major point update.

**Comment by Tidal-Wave** [comment]
I believe that this is fixed in 4.2.2, if anyone finds issue, let me know.
