### ISSUE TITLE
Issue with image distortion for lower resolution.

### ISSUE THREAD

**Issue by hegdeashwin** [stevenwanderski/bxslider-4#516]
Hi,

I have 2 images with different resolutions as 200x200 & 400x400. Applied below code block.

Image with 400x400 looked fine as it should be. But 200x200 image got distortion. 
Now, the some reason i am not allowed to change the resolution of 200x200 to 400x400 and also don't need adaptiveHeight.

Is there any way to fix this ? Thanks

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and example of issue. Sounds like your 200x200 image is getting sized up by responsive css.
