### ISSUE TITLE
Thumbnail slider cont. scrolling with page buttons? HOWTO?

### ISSUE THREAD

**Issue by DonWolli51** [stevenwanderski/bxslider-4#520]
I have a slide and a row of thumbnails which is continously scrolling. On mouseover it stops, onmouseout it continues scrolling. So far so good. 
BUT: the customer wants page buttons to make the thumbnails jump forward (or backward) 5 slides.
Howto??
![skt](https://cloud.githubusercontent.com/assets/1679102/2775191/d60e73da-cac2-11e3-9693-b1b0aafe051b.jpg)

**Comment by Tidal-Wave** [comment]
In this scenario it would be best to make two sliders and control them together. We will look improving thumbnails in a future release.
