### ISSUE TITLE
BxSlider is calculating wrong width at first load

### ISSUE THREAD

**Issue by hegdeashwin** [stevenwanderski/bxslider-4#521]
I am using bxslider; The data which i am passing is dynamic via json and rendering it through Handlebars. I have used require.js as AMD lib for my project.

wheneven i try to load view/page. Bxslider within it does not loaded the image correctly for first time. As soon as i refresh the page it works fine.

At first time
```
element.style {
    float: left;
    list-style: none outside none;
    margin-right: 12px;
    position: relative;
    width: 28px;
}
```
After refresh
```
element.style {
    float: left;
    list-style: none outside none;
    margin-right: 12px;
    position: relative;
    width: 95px;
}
```
Initialize slider as:
```
$('.slider').bxSlider({
    minSlides: 3,
    maxSlides: 5,
    slideWidth: 95,
    slideMargin: 12,
    pager: false,
    infiniteLoop: false
});
```
BxSlider is calculating wrong width at first load. Did anyone faced such issues? Any rapid fixes that i needs to apply.

**Comment by Tidal-Wave** [comment]
closing due to possible duplication with https://github.com/stevenwanderski/bxslider-4/issues/560
Looking to address loading issues in update.

**Comment by devendra07** [comment]
please use below bx slider to load images on window resize 
http://bxslider.com/examples/reload-slider-settings
just replace click event by window resize function
Like this:
$(window).load(function() {
var slider = $('.bxslider').bxSlider({
  mode: 'vertical',
  hideControlOnEnd: true,
  infiniteLoop: false,
  pager:false,
  minSlides:1,
});

$(window).resize(function(e){
  e.preventDefault();
  slider.reloadSlider({
    
  mode: 'vertical',
  hideControlOnEnd: true,
  infiniteLoop: false,
  pager:false,
  minSlides:1,
  });
});
});
