### ISSUE TITLE
touching paggination button and then swipe during animation breaks bxslider

### ISSUE THREAD

**Issue by lhwparis** [stevenwanderski/bxslider-4#524]
maybe thats related to #506 

if you click a pagination button on a touch device and then try to swipe the slider during the transition animation completly breaks bxslider only option is to reload the whole page :(

**Comment by Tidal-Wave** [comment]
Closing due to duplicate issue and PR. We are aware of issue with mobile/swipe/pagers and are looking to fix them in our upcoming update.
