### ISSUE TITLE
BxSlider not working correctly here...

### ISSUE THREAD

**Issue by vaibhav011286** [stevenwanderski/bxslider-4#526]
I have installed BxSlider, its great, but I tired to change the code little bit to get it work with not infinite with back animation from last to first one.
This trick working on my localserver but not in my website, ie. http://www.rockdizmusic.com/ (Latest Videos)

Currently, I disabled the trick as its a live site. If anyone can find the problem plz reply me.

Thank you.

**Comment by Tidal-Wave** [comment]
This site seems to have been taken down by the government for illegal activity, so I will be closing this issue.
