### ISSUE TITLE
going at the top of the page when slided

### ISSUE THREAD

**Issue by Samdecor** [stevenwanderski/bxslider-4#531]
i have some slide very height so i have to scroll down to read all. When i slide to go to the next horizontal Slide, im still scrolled down . I would prefer that when i slide/swipe i arrive at the top of next slide and not at the same scrolling state i was at the previous slide.

hope you ll understand what i mean.

Have you a solution, is there an option to fix it?

thanks

**Comment by Tidal-Wave** [comment]
This can be achieved with some javascript and the `onSlideAfter` callback. ATM we have no plans on making this a feature.

**Comment by Tidal-Wave** [comment]
I would also like to point out that this is probably a bad UX idea and can frustrate a user.
