### ISSUE TITLE
Clicking "prev" first makes a small glitch

### ISSUE THREAD

**Issue by thekillerdev** [stevenwanderski/bxslider-4#536]
Hello,

First off you can see my slider working on this link:
http://pixelcriativo.com/test/

If you click on the "prev" button when is to change from the 1st to the 24th slide(last one), it makes a little glitching on the functions that are happening on the "onSlideBefore".
Does anyone know why? Also if you see the link, you will see i tweaked a bit the bxslider removing the overflow:hidden and working the style on it, but that's all i changed on the core, is there a way to keep all the slides on the screen? you see if you go one slide to the left, it will show only the 4th on the right side.

Thanks.

**Comment by romapad** [comment]
I have the same problem. Here is my example:
http://gps.wpso.ru/ostin-leto-2014-mart-2014/
if you go from first slide back to the last, then the transition appears without any animation. 
Any idea how to solve it?

**Comment by Tidal-Wave** [comment]
The original issue has been fixed, but I think you are seeing a different one @romapad. Your demonstration helped me identify what is happening so I will conduct a few tests and hopefully have a patch soon. Thanks.

**Comment by Tidal-Wave** [comment]
This issue will be fixed in 4.2.4, but if you need an immediate patch, please see my comment in #758
