### ISSUE TITLE
Not an issue, more so an addition.

### ISSUE THREAD

**Issue by neotropic2023** [stevenwanderski/bxslider-4#538]
Position controls 'Next/Prev' on top, middle or bottom. So say you are using content inside instead of images? Them arrows get in the way. Course, could just hide the controls. But hey, never know who wants what.

CALL
$('.slider1').bxSlider({
	controlsPos: 'bottom'
});
-----------------------------------------------------------------------------------
IN PLUGIN
s = {
	...
	controlsPos: 'middle', // top, middle, bottom
	...
};

CHANGED:
div class="bx-controls-direction"
TO
div class="bx-controls-direction '+o.settings.controlsPos+'"
-----------------------------------------------------------------------------------
CSS (adjust to match your CSS framework)
.bx-wrapper .bx-controls-direction a {
	position: absolute;
	outline: 0;
	width: 32px;
	height: 32px;
	text-indent: -9999px;
	z-index: 9999;
}
.bx-controls-direction.top a{top: 0;margin-top: 0;}
.bx-controls-direction.top .bx-prev {left: 10px;}
.bx-controls-direction.top .bx-next {right: 20px;}

.bx-controls-direction.middle a{top: 50%;margin-top: -16px;}
.bx-controls-direction.middle .bx-prev {left: 10px;}
.bx-controls-direction.middle .bx-next {right: 20px;}

.bx-controls-direction.bottom a{bottom: -25%;margin-top: 0;}
.bx-controls-direction.bottom .bx-prev {left: -6px;}
.bx-controls-direction.bottom .bx-next {right: 5px;}

Just an idea. 
And what I added for my usage.

**Comment by Tidal-Wave** [comment]
Hey thanks for this. I am closing this issue because it isn't a bug and isn't a PR that I can merge, but I get what you are saying and will mark this as a feature request for possible consideration.
