### ISSUE TITLE
bxSlider 4.1.2 freezes on touch devices

### ISSUE THREAD

**Issue by jwahler** [stevenwanderski/bxslider-4#540]
I have noticed a bug/strange behaviour with bxslider on touch devives (in my case iPad2, iOS 7.1).

The bug causes bxslider to freeze. (Tested with: http://bxslider.com/examples/manual-show-without-infinite-loop)

1. select a slide by tapping a dot
2. now swipe the current image (before the animation (Step 1.) starts)

I guess touch-events have to be disabled when an animation is running. slider.working = true is set too late.

**Comment by Tidal-Wave** [comment]
Closing due to duplicate issue and PR. We are aware of issue with mobile/swipe/pagers and are looking to fix them in our upcoming update.
