### ISSUE TITLE
bxSlider stops when you click on pager and or arrows?

### ISSUE THREAD

**Issue by oninross** [stevenwanderski/bxslider-4#541]
Just want to know if this is an issue or a feature.  Is there a way for the banner to scroll again when idle?

**Comment by eness** [comment]
I'm having the same issue here. I don't want to modify the original source ;(

**Comment by Tidal-Wave** [comment]
It's currently coded this way, but due to request i will be adding an option to switch this behavior.

**Comment by Tidal-Wave** [comment]
This will be added to 4.2.4 which I hope to have out shortly.
