### ISSUE TITLE
Full and minified version 4.1.2 are different

### ISSUE THREAD

**Issue by everyonesdesign** [stevenwanderski/bxslider-4#543]
Noticed an issue with carousel mode prev slide transition.
http://jsfiddle.net/gS8yF/1/ (bxSlider 4.1.2 min is used in the demo)
If you click prev, the new index value is 1.5 because number of slides divided by number of moved items doesn't give a whole number.
it's fixed in full version though can be reproduced with minified version. 
Please merge it to the minified version.

**Comment by Tidal-Wave** [comment]
Fixed in 4.1.3
