### ISSUE TITLE
Swipe is not working on iPad.

### ISSUE THREAD

**Issue by hegdeashwin** [stevenwanderski/bxslider-4#553]
Hi,

This issue is with iPad/Tablet.
I have used images within slider and its working great. Now, these images are clickable; Due to which i am not able to swipe the slider (because image click event is getting triggered). 

I am able to swipe through margin touch but not with image touch.

Following are the options which has been set:
```
$('.slider').bxSlider({
	minSlides: 3,
	maxSlides: 5,
	slideWidth: 95,
	slideMargin: 15,
	pager: false,
	infiniteLoop: false,
	onSliderLoad: function() {
		...
	}
});
```

**Comment by Tidal-Wave** [comment]
Closing due to lack of information or working example of issue. We are not aware of any issues with clicking atm. Touch and swipe should register as different inputs. If you have an issue please create a working example of the problem to assist us.
