### ISSUE TITLE
How can I use redrawSlider function?

### ISSUE THREAD

**Issue by parhumm** [stevenwanderski/bxslider-4#556]
Hi, 

When I use (Foundation Interchange Plugin)[foundation.zurb.com/docs/v/4.3.2/components/interchange.html] to load Images for different size, bxSlider calculate height of photos incorrectly and when I resize window that problem solved.

I see your codes and find a function for reflow, I think if I can call redrawSlider function can help me to solve my problem.

My question is how I can call your redrawSlider function from my codes?

Thanks,
Parhum :)

**Comment by navin09** [comment]
Hi @parhumm 

I had the same issue and have fixed it in my fork here: https://github.com/PowerStores/bxslider-4

You might need to use https://github.com/paulirish/matchMedia.js/ for IE support.

**Comment by parhumm** [comment]
@navin09 Thanks, I check it.
