### ISSUE TITLE
how can i get rid of top and left margines?

### ISSUE THREAD

**Issue by polskavaenk** [stevenwanderski/bxslider-4#557]
Hello ! 
I'm making my first own www page and i put sucsessfully the slider on it. But i cannot set my photos in the center of slider. There are bigger margines on the top and left of it (look at the photo). So my question is how can i get rid of them and move my photo to the center or extend the photo to the end of frame? EDIT: 
oh, i noticed that the text section is too low, so i have to lift my picture. Is there anything i can do with it? and how? 
![bxslider](https://cloud.githubusercontent.com/assets/7786457/3167380/31c04cf6-eb6d-11e3-881b-77176b9e66b1.png)

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and working example. We cannot diagnose images. This looks like user error on css but I have no way of knowing. If you want to pursue an issue, please reopen with more information and working example.
