### ISSUE TITLE
Change start slide with URL

### ISSUE THREAD

**Issue by isaacscheidt** [stevenwanderski/bxslider-4#558]
Is there a way to change the start slide through an a href link or through an onclick function? I have a site with 4 offices and they want to link to each one in the footer. I'd like to not build out 4 different contact pages so it'd be nice to have the address/location as a slider and link to the same page for all of them and just change the starting slide.

Thanks in advance for the help!

**Comment by Tidal-Wave** [comment]
You should be able to do this with JS and the public methods available, you will just need to parse the hash or link events and set start slide in config or with `reloadSlider()`.
