### ISSUE TITLE
bxslider sometimes not working 

### ISSUE THREAD

**Issue by fmmarmello** [stevenwanderski/bxslider-4#559]
Hello, I've been facing some strange issues. 
Sometimes, when I open the page, the slider simply doesn't load.(Infinite loading)

http://www.voceaprendemais.com.br || or || 
http://proab.voceaprendemais.com.br

onSliderLoad is not been triggered, so I was wondering if there's some onSliderNotLoaded feature or something like that, so I can use it to trigger the reloadSlider function.

If someone has any clue about what's happening I appreciate too ^ ^ 

Using $(document).ready() to call it

**Comment by Teranode** [comment]
this got worse in version 4.2.2.

However i fixed it by using some samples in 4.2.1 (They should have left that part in tact instead of breaking it more)

changed:

			preloadSelector.find('img:not([src=""]), iframe').first().one('load', function(){
				slider.viewport.height($(this).height());
				loadElements(preloadSelector, start);
			});
		};

		var loadElements = function(selector, callback){
			var total = selector.find('img:not([src=""]), iframe').length;
			if(total === 0){
				callback();
				return;
			}
			var count = 0;
			selector.find('img:not([src=""]), iframe').each(function(){
				$(this).one('load error', function(){
				  if(++count === total){ callback(); }
				}).each(function(){
				  if(this.complete){ $(this).load(); }
				});
			});
		};

to

	loadElements(preloadSelector, start);
		};

		var loadElements = function(selector, callback){
			var total = selector.find('img, iframe').length;
			if(total === 0){
				callback();
				return;
			}
			var count = 0;
			selector.find('img, iframe').each(function(){
				$(this).one('load error', function(){
				  if(++count === total){ callback(); }
				}).each(function(){
				  if(this.complete){ $(this).load(); }
				});
			});
		};

**Comment by Tidal-Wave** [comment]
addressed.
