### ISSUE TITLE
Viewport Calculate Wrongly

### ISSUE THREAD

**Issue by skycrew** [stevenwanderski/bxslider-4#562]
I got a responsive template for my website.

I initialize my bxslider on document.ready. When I use full reload (ctrl+shift+R) the viewport calculated correctly. You can find below screenshot
![full refresh](https://cloud.githubusercontent.com/assets/1005824/3266495/df6f688c-f2b1-11e3-8bac-6fe4c945a19a.png)

But when I use normal reload/refresh (ctrl+R). The viewport calculated wrongly. You can see screenshot below. The extra images is on second page.
![normal refresh](https://cloud.githubusercontent.com/assets/1005824/3266496/dfc517fa-f2b1-11e3-9336-55fd2ae5258a.png)

I tried to put in window.load but normal reload and full reload resulted with wrongly calculated viewport just like above screenshot.

Any help?

**Comment by Tidal-Wave** [comment]
Fixed in 4.2.2
