### ISSUE TITLE
Support extra control icon!!

### ISSUE THREAD

**Issue by petersontubini** [stevenwanderski/bxslider-4#569]
Hello,

I'm creating a new website like Hulu style... and I need to add a PLAY control button inside the 'li' item that will href with my own player at the page.
Another question: We can create pagination as well....

Please check the image below and you will understand better....

Please help me, I can pay a beer for you :dancer:  

PS: I tried to do it with CSS z-index but it's not good because isn't responsive.

![but](https://cloud.githubusercontent.com/assets/7456065/3311160/886b9b38-f6c0-11e3-97bd-766400b272a5.png)

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and working example of issue. We cannot diagnose images. If you would like help with an issue, please reopen with more information and examples.
