### ISSUE TITLE
adding show/hide function on slider

### ISSUE THREAD

**Issue by atalshrivastava** [stevenwanderski/bxslider-4#570]
i used multiple bxSlider in my page and i need to display them on click of a button, but it does not executed. like
$("#new").click(function(){
	$("#bxslider1").hide();
	$("#bxslider2").hide();
	$("#bxslider3").show();

}); 

same i tried for other two buttons, but the content of the slider always hidden, when i do inspect element they visible again.
thanks in advance

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and working example of issue. We are unable to diagnose this with the information provided. If you are still having an issue please create an example of the issue and reopen.
