### ISSUE TITLE
Dynamic Thumbnails

### ISSUE THREAD

**Issue by thejoshevans** [stevenwanderski/bxslider-4#572]
Hi, I'm using the slider to pull product images from a Wordpress plug in called WP Catalogue.

Using your example: http://bxslider.com/examples/thumbnail-pager-2

I am able to pull the images in to an array using:

var $arr = $('.wpc-product-link img').map(function() { return this.src; }).get();

and then use this code to display the thumbnails:

slider = $('.prod-slide').bxSlider({
  buildPager: function(slideIndex){  
	  switch(slideIndex){
      case 0:
        return  $arr[0];
      case 1:
        return $arr[1];
      case 2:
        return $arr[2];
	case 3:
        return $arr[3];
	case 4:
        return $arr[4];
	case 5:
        return $arr[5];
	case 6:
        return $arr[6];
      }

The products will have different numbers of images however so I can't set up the switch statement this way.

Is there a way to set up the slideIndex by looping through the array?

Thanks

**Comment by Tidal-Wave** [comment]
Switch is not the only way to write this type of function. Well crafted JS can loop through an array and build what is needed. Closing due to lack of information and examples to assist with .
