### ISSUE TITLE
Carousel is not acting responsive on my website

### ISSUE THREAD

**Issue by faridjame** [stevenwanderski/bxslider-4#573]
I've used your carousel on [my website](http://versacreative.com.php53-9.ord1-1.websitetestlink.com/), on the clients sections; however, as you can see, it's not responsive (the width doesn't change when you shrink the page). Any idea what I'm missing? I'v made sure none of my css are interfering and the container is a fluid container.

**Comment by Tidal-Wave** [comment]
The test site linked seems to function as expected atm. Closing. If you need assistance please reopen with more information or an isolated example of your issue.
