### ISSUE TITLE
Multiple images within slide not showing, after the first?

### ISSUE THREAD

**Issue by jezthomp** [stevenwanderski/bxslider-4#576]
I have slides set up which have numerous html elements per slide, as well as a main image and a small arrow image per slide.

The arrow image only appears on the first slide though then his hidden all the other slides, you can see it in the html but it doesn’t display.

All other html changes as it should...

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and  working example of issue. This could be so many things based on limited info provided.
