### ISSUE TITLE
Feature request: responsive breakpoints

### ISSUE THREAD

**Issue by milelazar** [stevenwanderski/bxslider-4#577]
First, thanks for the great slider. This is one of the best I have seen out there. 

But to make it even more perfect, it would be so nice if you could define responsive breakpoints. 
Sure, you can reinitialize the slider based on the screen size, but it would be great to have that option available without custom coding. This is not official obviously, but it is a great example of that functionality: http://rahisify.com/demos/plugins/bxslider/demo/index.html

**Comment by Tidal-Wave** [comment]
We are looking at responsive changes in a future release. Thanks.

**Comment by avradul** [comment]
It took almost 2 years... Still no breakpoints.
But there is a Owl carousel http://www.owlcarousel.owlgraphic.com/demos/responsive.html with real responsive options.
