### ISSUE TITLE
BxSlider's infinite loop doesn't work well with jquery scrollbars

### ISSUE THREAD

**Issue by cdweb** [stevenwanderski/bxslider-4#579]
Hi, I love BxSlider for its flexibility. But I've been trying to use it on the homepage of a site that also has other divs with jquery scrollbars. I'm using it with the pager and controls, and I do need a video to play within the slider (which is the reason I'm using the latest BxSlider). But when I set up infinite loop to true, or just leave the default of true, it doubles my slides, causing double pagers to be shown active, and it bounces the slides when it transitions by going back and forth. I've tried to change the scrollbar jqueries and it does it with every one. I'm currently using tinyscrollbar.js. So for now I just have it as infiniteloop: false, but I really need it to continue playing. Is there a way I can accomplish it without it going crazy on me.

Thanks

**Comment by Tidal-Wave** [comment]
Infinite loop uses a cloning technique currently. There is also a bug in how this is [done] (https://github.com/stevenwanderski/bxslider-4/pull/481). Until we revisit how we do infinite scroll and fix the issue linked I don't think you will be able do this. We are working to fix this ASAP. Closing for now.
