### ISSUE TITLE
Why is redrawSlider() is not listed under public methods in documentation?

### ISSUE THREAD

**Issue by smohadjer** [stevenwanderski/bxslider-4#581]
I noticed today that calling redrawSldier() method of bxslider fixed a resizing issue I was having with bxslider when browser window is resized too fast. How come this method is not listed in documentation of bxslider under public methods? Should I be concerned about using it in production code?

**Comment by Blatant** [comment]
Just to say thanks for the idea to fix my resize bug, smohadjer!

I had seen the redrawSlider method when i scanned the code, but instead found the docs on reloadSlider and went with that, but still had a bug where if I resized the window down the slides would sometimes bleed from the right. 

After your comment I tried using redrawSlider myself and it fixes the bleed really nicely! Thanks for at least writing this down!

As for your comment, I would like to upvote your suggestion, please document the redrawSlider method!! +1

And for your question, the only downside (afaik) is that you're effectively redrawing the slider twice, once before the OnSliderResize hook (also this event is missing from the docs too, seperate issue), and once again during/after, however as long as you don't blindly update your bxslider JS you should be safe to use in Prod. I see no other pitfalls.

**Comment by Tidal-Wave** [comment]
Resize issues should be fixed in latest version. My next area to tackle will be new docs so hang tight.

**Comment by Blatant** [comment]
Thanks Tidal-Wave! 

+1 to you for all your dedication and work  :D  We all appriciate all your effort!
