### ISSUE TITLE
images failing to load when having multiple sliders in different jquery-ui tabs

### ISSUE THREAD

**Issue by umbregachoong** [stevenwanderski/bxslider-4#585]
Hello:

I am having issues with the images failing to load when you click on the other jquery ui tabs. Strangely enough, on opera, chrome and firefox, the images will load if I open the developer tools console and when I move the console up or down.  The images in the other tabs totally fail in IE 11

Here is a live demo:

http://inetwebdesign.com/bxslider2/jquery-ui-tabs-accordion2.html

Any help would be greatly appreciated.

Thanks!

umbre gachoong

**Comment by Tidal-Wave** [comment]
There are currently some known issues (https://github.com/stevenwanderski/bxslider-4/issues/560) with the slider if images are not loaded correctly on initialization. As a workaround you can try reloading the slider on tab change.
