### ISSUE TITLE
How to stop slides from piling up on page load?

### ISSUE THREAD

**Issue by pilgrimish** [stevenwanderski/bxslider-4#586]
I've got a page that's utilizing multiple instances of bxslider. How do I prevent the slides from appearing on top of one another (sometimes resolving, sometimes remaining stuck on top of one another) upon page load?

The page is http://www.hudsonvalleycompass.com/scoops

The issue: 
![compass](https://cloud.githubusercontent.com/assets/638650/3579411/cb50aa02-0bbe-11e4-856b-58d64456e871.png)

**Comment by Tidal-Wave** [comment]
The page seems to be functional. Closing for housekeeping reasons. If you are still having an issue please reopen with more information and an example of the problem. We can't diagnose pictures.
