### ISSUE TITLE
Can see images only after resize page

### ISSUE THREAD

**Issue by Pernelhas** [stevenwanderski/bxslider-4#591]
Hi,

I'm using bxslider to show a few fotos, but when I open the page to see the images I can't see them until I resize the browser window. 

when I open the page this is what I get: 
![before](https://cloud.githubusercontent.com/assets/875059/3696666/721d5d5e-1393-11e4-99a6-ab793e6e51e8.png)

After the resize browser:
![after](https://cloud.githubusercontent.com/assets/875059/3696667/75943c96-1393-11e4-9c91-3c3cdcce921f.png)

Anyone knows why this is happening? 

Thanks in advance.

**Comment by Tidal-Wave** [comment]
Hello, I've been added to this project to maintain it. Im sorry for any issue you are having, but we cannot diagnose images. If you are having an issue please either: 

1. Create an isolated example of the issue using something like jsfiddle.
2. Provide a direct link to a website exhibiting this issue. 

Closing until one of those two can be provided.
