### ISSUE TITLE
bxslider for firefox problem

### ISSUE THREAD

**Issue by ying5320** [stevenwanderski/bxslider-4#593]
![bsslider_firefox](https://cloud.githubusercontent.com/assets/3016696/3713383/66320976-1565-11e4-9d3f-2c33423c4dac.png)
its use for firefox screen, for chrome and ie can work.
my setting

$(document).ready(function(){
    $(".bxslider").bxSlider({
        mode: "fade",
        captions: true,
        video: true,
        useCSS: false
    });
});

thanks help

**Comment by shikkaba** [comment]
Why was this closed? It's still an issue.
