### ISSUE TITLE
maintain auto display of slides after a manual selection

### ISSUE THREAD

**Issue by piperh** [stevenwanderski/bxslider-4#594]
Is there a way to maintain by default the auto display of slides after clicking a thumbnail or a control arrow (without using the stop/start controls) ?

**Comment by piperh** [comment]
djimmrtl, thanks for response but I can't find that line of code in  jquery.bxslider.js  v4.1.2

**Comment by djimmrtl** [comment]
Ok, ya it doesn't appear to be in the latest version. Not sure which
version I had made this adjustment to.

**Comment by dawncold** [comment]
@djimmrtl Is there a PR?

**Comment by Tidal-Wave** [comment]
I am sprinting on an update so let me see if I can add this in.

**Comment by Tidal-Wave** [comment]
This has been added to 4.2.4
