### ISSUE TITLE
Controls that appear on each slide

### ISSUE THREAD

**Issue by kevinorin** [stevenwanderski/bxslider-4#595]
I set control: true and I did not see any arrows appear on my slider.
I also tried using the outside controller but inside each slider and it only shows up on the first slide.

How can I get 1 or 2 sets of controls as shown in this mockup to appear (notice the first control is on left and right of the date...and the date is part of the slider HTML text which will change as well).

Is this possible?
![classes](https://cloud.githubusercontent.com/assets/1056402/3723640/7f453652-1675-11e4-83e7-ce42b5961635.png)

**Comment by Tidal-Wave** [comment]
To achieve this you would need to write extra javascript to control multiple sliders. This is currently out of scope of this project.
