### ISSUE TITLE
How to apply in ajax load content

### ISSUE THREAD

**Issue by CARocha** [stevenwanderski/bxslider-4#598]
Hi, i load data in ajax but my new content not apply the bxslider
i read in internet use .live() but i use jquery Query JavaScript Library v2.1.0 and zurb foundation, my new content see in the DOM when i control + shift + U only the first content
before click load more button,

any idea apply for working bxslider for ajax content????

**Comment by Tidal-Wave** [comment]
Closing due to duplicate issue. There are currently known issues with the slider when images aren't loaded at initial setup. 

Possible workaround is to reload slider after enduring content is loaded.
