### ISSUE TITLE
Resize Slider using "destroySlider" and "reloadSlider" not working, when "Pager" slider is linked to other slider  using "pagerCustom" property

### ISSUE THREAD

**Issue by aasthatuteja** [stevenwanderski/bxslider-4#599]
I have created 2 sliders using "BXSlider" pluggin.

First Slider has Thumbnails slider (Pager) and the other is the Image Slider. Each slider is placed inside a Splitter Panel.

For the Splitter, I'm using Kendo Splitter plugin.

 the ISSUE appears, if I keep the "BIG Image Slider's Splitter" collapsed by default, and after the page is loaded, when I open the "BIG Image Slider Splitter", the Slider does not appear. Reason: it does not update the **width of Slider.

The issue resolves when I resize the window "Manually".

So to resize slider I tried "destroySlider" and then "reloadSlider". But after adding this script, when I open the Splitter, the thumbnail slider (Pager) gets hidden/deleted.

I found the Issue is with "pagerCustom" property, when I remove this property the resize does work with "destroySlider" and "reloadSlider"

Here is the demo of my Image Slider 

http://jsfiddle.net/6QJt6/

Can you please suggest how to fix this issue?

Thanks

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/pull/610. Closing due to duplicate issue. Will fix in upcoming update.
