### ISSUE TITLE
Href doesn't work as soon bxslider is in use

### ISSUE THREAD

**Issue by dipiana** [stevenwanderski/bxslider-4#602]
Hi!
I have links which control bxslider but also need to use href.
In my case e.g. href="#2" which triggers a slideshow in the background, but as soon as I use the same link for bxslider, #2 isn't attached to the URL.

<li >< a id="home" href="#2">HOME</ a>< /li> doesn't work.

When I change the ID to some ID which isn't used by bxslider "#2" is attached to the URL as it should be.

How can I solve this issue?

Thanks!

**Comment by Tidal-Wave** [comment]
Closing to to lack of example. Please provide Moreno formation and an example of your issue. It sounds like implementation error.
