### ISSUE TITLE
jQuery Conflict: Bootstrap 3 and bxSlider

### ISSUE THREAD

**Issue by mattcdowning** [stevenwanderski/bxslider-4#605]
PROBLEM: bxSlider doesn't appear/work in Bootstrap 3. Firebug throws the following error in the console:

TypeError: $(...).bxSlider is not a function
http://localhost:9000/pictures.html
Line 69

HTML:

```
<link href="styles/bootstrap.css" rel="stylesheet">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="_/js/jquery.bxslider.js"></script>
<link href="styles/jquery.bxslider.css" rel="stylesheet" />
<link rel="stylesheet" href="styles/mystyles.css">
<script src="_/js/bootstrap.js"></script>
<script type="text/javascript"> $(document).ready(function(){ $('.bxslider').bxSlider({ }); }); </script>
```

HACKY-SOLUTION:

Adding jQuery.noConflict to the slider JS solves this for me.

```
<script type="text/javascript"> $(document).ready(function(){ var j = jQuery.noConflict(); $('.bxslider').bxSlider({ }); }); </script>
```

s/o to @KempfCreative for the workaround: http://stackoverflow.com/questions/3970656/my-jquery-slider-is-not-working-properly

QUESTION: Is there a better solution?

NOTE:
If I remove the BS javascript, jQuery.noConflict is not needed, so I imagine there must be some conflict between the BS and bxSlider JS.

Unfortunately, I could not replicate the issue in JSFiddle:
http://jsfiddle.net/mattcdowning/ATC7B/

Any help would be much appreciated!

**Comment by sharifghaderi** [comment]
Hi I'm using the bxslider for a custom project and not wordpress. I tried all the ways explained above but it's not working even when using the noConflict() function.
I'm wondering why the creator didn't solve a so important issue.!!

**Comment by mattcdowning** [comment]
The fact that you can't get it to work is not the fault of the creator. And complaining about it is not going to win you any friends. However, if you ask nicely, I'm sure someone here can help.
