### ISSUE TITLE
Slider refusing to scale down, only up

### ISSUE THREAD

**Issue by gnowland** [stevenwanderski/bxslider-4#611]
I am having an issue with browser resizing/responsiveness; on browser width increase everything scales as it should, but on decrease the `<li>` width is not being recalculated... see demo: [lc.westguardsolutions.com](http://lc.westguardsolutions.com)

Any help on this would be very much appreciated... I'll buy you a beer!!

Thanks,
GN

**Comment by gnowland** [comment]
Thank you for the fix, I will implement this in future projects using BX-Slider!

**Comment by Tidal-Wave** [comment]
adding this for review in our next update. Thanks for the work here guys.

**Comment by kellykarnetsky** [comment]
I didn't submit a pull request because I didn't know if they were being looked at. Do you want me to create them that addresses both these issues?

**Comment by Tidal-Wave** [comment]
Sure, if you have the time. I've been added to the project to assist in maintaining it and provide updates. Sorry for any lack of communication.

**Comment by kellykarnetsky** [comment]
Pull requests created.

**Comment by Tidal-Wave** [comment]
I have reopened this issue because the fix submitted by @kellykarnetsky obscures the loading gif as the slides load because it doesn't have any height. 

After carefully evaluating the issue here and in #487, I need to see a more concrete example. There is something that is missing here because I've setup several examples on locally and not experienced what is being generally described. I am not discounting anyone, but all I have to go on is a general description of a vague issue, fragments of code that don't generally help me, and some images.

**Comment by Tidal-Wave** [comment]
@gnowland - your general assumption of the slide width calculation is incorrect. Yes it does take a measurement of the parent, but the parent size is correct due the max-width applied to the whole container.  The if statements should not fail in `getSlideWidth` which is what is calculating the slide widths.

Also, Your original example link no longer uses bxslider, so I am unable to diagnose.

**Comment by gnowland** [comment]
@Tidal-Wave sorry, that site was moved from dev to production, new URL is lanciaconsulting.com with the fade effect applied to fix the scale-down issue because the project was over budget as it was :)

I'd love to assist at debugging this at some point, as soon as I get some free time :/

My guess is it has something to do with the css of the surrounding div(s) on that site as I've successfully used BX slider on other projects since with no issue. Unfortunately I inherited that codebase from another dev so it's not my proudest product!

Thanks for your hard work man.

**Comment by gnowland** [comment]
If it turns out there was a CSS override to BX that caused this I'm going to owe you a beer.

**Comment by Tidal-Wave** [comment]
hey no problem, I just want to put this bug to bed so I can get on to the more pressing issue of a major overhauls.

**Comment by Tidal-Wave** [comment]
Closing, I think this has been addressed and no other sample can be produced atm.

**Comment by Trost123** [comment]
This shit got me pulling my hair out!
Here is what caused it for me:
<div style="display:flex"><div style="display:block"><div class="bxslider"></div></div></div>
So, you wrap a slider inside a block, and then you wrap the block inside a flex. Then you proceed to enjoy your headache as you try to figure out why does the slider shrink only on page refresh, while it grows on browser resize.
