### ISSUE TITLE
Can someone help me using the wrapperClass

### ISSUE THREAD

**Issue by thaflo** [stevenwanderski/bxslider-4#614]
Hi, 

I want to implement two sliders with different background and margin colors.
So I thought to use the wrapperClass property, but I have no idea how to use it.

Can someone help me please explaining me how to get two sliders with different background color?
Thanks,
Florian

**Comment by Tidal-Wave** [comment]
Simply create two sliders with different ids and then call `bxslider()` on both. Then you can style them however you need.
