### ISSUE TITLE
Not possible to swipe vertical to bypass gallery?

### ISSUE THREAD

**Issue by Jayinthebay** [stevenwanderski/bxslider-4#616]
Hello, 

I am considering using bxslider for a project, but it appears that the slider disables vertical scrolling (e.g. if user wanted to navigate above or below the gallery on a mobile or table device).  I've also posted the issue on stackoverflow: 

http://stackoverflow.com/questions/25297836/bxslider-cant-scroll-up-down-past-the-gallery

It seems to be similar to issue #82 ...  odd that there has been no problems or reports of this in that thread for over a year, then 2 people encounter it within a couple weeks?

**Comment by Tidal-Wave** [comment]
This issue should be fixed with the above changes in https://github.com/stevenwanderski/bxslider-4/issues/82. Please feel free to create a simple example (without all the extra bootstrap stuff) and we can see if there is an issue.

**Comment by juanpasolano** [comment]
I am having the same issue: using 4.2.5 on safari on iphone 5s
