### ISSUE TITLE
Option "wrapperClass" not working in min version!

### ISSUE THREAD

**Issue by ngoncom** [stevenwanderski/bxslider-4#623]
Hi developer!

I've tested and seem "wrapperClass" not working in jquery.bxslider.min.js, it only works with jquery.bxslider.js, can you re-check this!

Thank!

**Comment by Tidal-Wave** [comment]
Duplicate of https://github.com/stevenwanderski/bxslider-4/issues/543. We will be improving work flow in an update to avoid this in the future.
