### ISSUE TITLE
destroySlider() function leaves css3 transitions and widths

### ISSUE THREAD

**Issue by piotrkulpinski** [stevenwanderski/bxslider-4#628]
Hi.
I've found a bug with destroySlider() callback which is not working as supposed. It leaves css3 transitions which are breaks the layout of the component:
https://www.dropbox.com/s/eqwb2o4i2hnwduv/Screenshot%202014-09-01%2014.14.10.png?dl=0

**Comment by Tidal-Wave** [comment]
Hi folks. Ive been added to maintain this project and provide updates. I apologize that the minified versions of bxslider have been out of sync. We will fixing this with improvements to build processes in the near future. For now please refer to the above solution.
