### ISSUE TITLE
Adding jQuery bound/clickable elements in slider does not fire

### ISSUE THREAD

**Issue by olivieragustin** [stevenwanderski/bxslider-4#631]
Hey Guys,

I'm trying to stop the auto slider when a html5 video is played but to no avail. If you have any ideas how, that would be great. However, I did figure out a workaround by putting an invisible overlay on the video tag and adding a click event on it to stop the slideshow and play the video. I haven't really done this since I'm testing it if it will work. I added a link on the slide with the video. This link should fire a click event that should do the stopping of the slider and playing of the video. Somehow, the click does not fire (currently it should play the video and adding text in the console). 

Any ideas how to do this? I'm really at my wits end.

Thanks. Great plugin BTW.

![2014-09-04_1522_001](https://cloud.githubusercontent.com/assets/1411499/4146021/7fe88b52-3404-11e4-90d5-33bffacebe85.png)
![2014-09-04_1522](https://cloud.githubusercontent.com/assets/1411499/4146023/7ffb41ac-3404-11e4-9d99-8ba36b8b601f.png)

**Comment by Tidal-Wave** [comment]
The slider uses `.clone()` to produce the infinite loop effect and it was not doing a deep copy. This should be fixed in 4.1.3.
