### ISSUE TITLE
Multiple sliders not visible

### ISSUE THREAD

**Issue by timersys** [stevenwanderski/bxslider-4#633]
I have multiple sliders, some of them not visible and when the window is resized and the slider is not visible the redrawSlider methods breaks them.

So I added to the beggining of redrawSlider function the following:

	if( ! slider.viewport.is(":visible") ){
		return;
	}

Then I just run the reloadSlider manually when needed. 

Thanks!

**Comment by Tidal-Wave** [comment]
Closing issue. This seems like it is partially how you implement the slider. We will evaluate how responsive is handled at a later date.
