### ISSUE TITLE
Safari, back button

### ISSUE THREAD

**Issue by buniden** [stevenwanderski/bxslider-4#636]
When using the back button to visit a previously viewed page in safari the slider doesn't show up.  This is happening for me with latest version of safari with demos from http://bxslider.com/examples as well as a site i'm working on.  

Does anyone know of a fix for this?

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/560. Closing due to duplicate issue and housekeeping. Will be addressing image load issues in our future update.
