### ISSUE TITLE
BxSlider width goes to 100px per slide.

### ISSUE THREAD

**Issue by Carlitta87** [stevenwanderski/bxslider-4#637]
Sometimes, when I use the newest version of BXSLIDER the LI goes to 100px automatically. Has anyone else had this issue. This doesn't only occur in IE but also Firefox as well. I will gladly provide any information you require to resolve this.... I have attached an image to let you see exactly what i am seeing...

I also provided how i called the element.

I should also note that I am using Foundation 5, with version jQuery JavaScript Library v2.1.0

if($('.openhouse_slider').length){
		$('.openhouse_slider').bxSlider({
			auto: true,
			autoHover: true,
			pager:false,
			nextSelector: '.rightbutton',
			prevSelector: '.leftbutton',
			nextText: 'NEXT',
			prevText: 'BACK'
		});	
	}

![screen shot 2014-09-18 at 4 22 43 pm](https://cloud.githubusercontent.com/assets/2539915/4327528/f63eaee6-3f79-11e4-8850-cff169262a56.png)

Thank you for your time. I'd really appreciate any assistance.

**Comment by flowerbread** [comment]
I got it !!!!

'sliderName'.reloadSlider();
