### ISSUE TITLE
Wrong positioning while load images

### ISSUE THREAD

**Issue by Freestylerrr** [stevenwanderski/bxslider-4#648]
I'm having problem while images are loading into slider. This will move with other text or images on my site. Problem is only in FF 32.0.3 (Chrome, IE are ok). 

Problem will disappear when i zoom in and zoom out my page, but it's kinda annoying. 

Problem is on this site: http://vitani-prvaku.cz (the partner section will move away from box :/ )

P.S. Alternatively fixed by adding .bxslider img widht and height, but on some pages it's problem, because images are loading in <li> and then will apply the display:block element, so text is mixed up until page is zoomed in or out. Don't know if it's browser problem or bxslider problem.

**Comment by Tidal-Wave** [comment]
Closing due to lack of example of issue. The partner section of the site linked currently doesn't use bx-slider.
