### ISSUE TITLE
Default parameter doesn't seem to work for IE7/8

### ISSUE THREAD

**Issue by helders** [stevenwanderski/bxslider-4#650]
I'm using bxslider following exactly the examples provided, everything seems to work fine except that when i change the default parameter IE7/8 throws some error and it won't work properly, if i remove the parameter the page loads fine and it all works well.

**Comment by Tidal-Wave** [comment]
I haven't tested IE7, but most everything works as expected in IE 8. Closing for now. If you would like to reopen this issue please provide more information, screenshots, examples, etc.
