### ISSUE TITLE
Go Back with browser's button

### ISSUE THREAD

**Issue by aculine** [stevenwanderski/bxslider-4#654]
Hi, I'm going crazy with this problem:
BXSlider is running well at first loading of the page, but if I go on other page and then come back by browser's button or a link, BXslider is not working. I have noted that bx-viewport is blocked in css-inline "height: 0px" and slide aren't visible.
Obviously if I manual refresh page, bxslider works.
The problem is not only on my page, but also in bxslider.com, all examples. 
If I use your example of reload bxslider (using .reloadSlider(); and a button) it works, but I cannot find a way to call it if page is re-called.
I find an issue to use bxslider4.1.1, but it doesn't works also.

Can u help me?

thank you, Luca.

**Comment by Tidal-Wave** [comment]
Closing due to lack of proper example of issue. Possibly related to https://github.com/stevenwanderski/bxslider-4/issues/560.
