### ISSUE TITLE
Options docs missing detail regarding fade mode

### ISSUE THREAD

**Issue by ifnull** [stevenwanderski/bxslider-4#655]
The mode `fade` does not appear to work properly until a height is set. I suggesting add this to the docs under `General -> mode`:

```
Note: `fade` mode requires height to be set on the selector the `bxslider()` is being called on.
```

**Comment by Tidal-Wave** [comment]
@ifnull - fade mode uses absolutely positioned images stacked on each other, so height is required. We will look at updating doc.

@jfostemedia - this issue is related to https://github.com/stevenwanderski/bxslider-4/pull/715. We will fix it soon.
