### ISSUE TITLE
Custom pager doesn't work in modal window

### ISSUE THREAD

**Issue by moldnixy** [stevenwanderski/bxslider-4#659]
Hi, use UIKit framework in my project. I use an modal window to load bxslider in it. The issue is that the custom pager doesn't show in modal. When i inspect the code the div with custom pager doesn't exist there even if there is such a div in my markup.

This is my markup: http://static.md/3979e17c6f62b3d3cc65dd0cc3e7b499.png
And this is what I have when insepct element: http://static.md/e982513b8ee1625b594823d2e6439fb6.png

**Comment by Tidal-Wave** [comment]
Closing due to lack of active example. If you would like to continue this issue please reopen with more information and an example.
