### ISSUE TITLE
hide slider based on bootstrap responsive classes

### ISSUE THREAD

**Issue by patrioticcow** [stevenwanderski/bxslider-4#662]
giving that i want to show 2 different sidebars, based on bootstrap hidden-* classes, right i don't see a way to do it.

for example:
```html
<ul class="bxslider hidden-xs hidden-sm">
	<li><img src="img/homepage-slider/slider2.jpg"/></li>
	<li><img src="img/homepage-slider/slider1.jpg"/></li>
</ul>

<ul class="bxslider hidden-md hidden-lg">
	<li><img src="img/homepage-slider/slider2_sm.jpg"/></li>
	<li><img src="img/homepage-slider/slider1_sm.jpg"/></li>
</ul>
```
the issue is that the controls for both sidebars will show.
one fix i had was to do

```javascript
var setup = function(){
    var getClass = el.attr('class');
    getClass = getClass.replace("bxslider", "");
    // wrap el in a wrapper
    el.wrap('<div class="bx-wrapper ' + getClass + '"><div class="bx-viewport"></div></div>');
```
would be nice to have a better solution

**Comment by Tidal-Wave** [comment]
We are reviewing how bxslider handles responsiveness  for a future update. Closing this issue for now. This can be achieved currently with some JS and `loadSlider()`.
