### ISSUE TITLE
Slides on more than one row

### ISSUE THREAD

**Issue by fsalimbeni** [stevenwanderski/bxslider-4#665]
Hi,

Your slider is great and fully customizable. My customer asked me to create a carousel with a fixed number of slides and to split them in 2 rows.

I haven't found any instruction on how is possible to do the second part.
Have you got any idea? Are you going to add this feature in the next release?

Regards

Fabio

**Comment by Tidal-Wave** [comment]
Currently there is no set way to achieve this, but the effect could be pulled off with two instances of the slider. If the request gets traction from others we will review it for inclusion. Thanks!
