### ISSUE TITLE
Double fade

### ISSUE THREAD

**Issue by hesteric** [stevenwanderski/bxslider-4#667]
The slideshows on my homepage have a double fade transition. The new slide appears, disappears and appears again. I don't see the cause of this.

See: http://www.rodericklloyd.com

A slide on another page with (in my opinion) the same settings doesn't has this issue:

http://www.rodericklloyd.com/nl/showroom/all-art-galleries

Any ideas?

**Comment by Tidal-Wave** [comment]
Hi, my name is Eric and I have been assigned to this project to assist in maintaining it. 

I have reviewed the linked pages and don't see any issues. Please feel free to reopen this issue with more information if you are still having an issue.
