### ISSUE TITLE
bx-loading won't go away for IE 11

### ISSUE THREAD

**Issue by allenchuang** [stevenwanderski/bxslider-4#668]
Hello,

Just noticed this issue while testing on various browsers. Seem to work for IE 9 & IE 10, but for IE 11, sometimes the bx-loading div just would not disappear. Sometimes a refresh does the trick, other times it remain there even when the images are done loading. 

My temporary solution is to disable it altogether by removing the background css for the bx-loading class, but would appreciate if it works from the box.

Any help would be be great.

Thanks,
Allen

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/560, closing due to duplicate. Hope to address in next update.
