### ISSUE TITLE
jQuery events unbinded once scrolled out of view

### ISSUE THREAD

**Issue by noupe** [stevenwanderski/bxslider-4#672]
Only happens when it's an infinite slider.
When an element goes out of view and comesback into view at the end of the loop, its binded events are lost.

**Comment by Tidal-Wave** [comment]
Infinite scroll uses a cloning method to achieve this effect. This is probably causing some confusion.

**Comment by Tidal-Wave** [comment]
possible fix here: https://github.com/stevenwanderski/bxslider-4/issues/346. Looking at incorporating it in next update.

**Comment by Tidal-Wave** [comment]
Fix pushed in 4.1.3
