### ISSUE TITLE
transform: translate3d will not work in bxslider.min.js

### ISSUE THREAD

**Issue by neralex** [stevenwanderski/bxslider-4#674]
Hey!

If i use the bxslider.min.js and useCSS with true and i try to resize a very small browser window then the viewport will not resized to the bigger size. In the other direction from big > small it works.

After some tests i have tried to use the bxslider.js and there is all fine.

It seems the minified file has not all required codelines for that. If i set useCSS to false then it works also with the minified file.

Cheers

**Comment by Tidal-Wave** [comment]
Related to https://github.com/stevenwanderski/bxslider-4/issues/543. Closing due to duplicate issue. Will address in upcoming update.
