### ISSUE TITLE
Fade mode when only 1 image in slider and 1 image showing at a time

### ISSUE THREAD

**Issue by tenold** [stevenwanderski/bxslider-4#675]
So I have an instance where my user may only add 1 image to their slider, and it's a slider that only shows 1 image at a time, and is in fade mode.

This results in the image flashing, as if it's going to fade to the next image, but doesn't.

I realize this may be more of a feature than a bug, but it would be nice if the code detected if there was only 1 image in the slider, and didn't attempt to transition/fade.

Otherwise I have to add some conditional to completely rewrite the markup of that area if there is only 1 image uploaded to the slider. Seems if there is only 1 item in the slider, transition shouldn't happen. Or it should be an option to not have it transition if there is only 1 item in the slider.

**Comment by Tidal-Wave** [comment]
Interesting solution. This is related to https://github.com/stevenwanderski/bxslider-4/issues/712, and we hope to fix it in a future update. 

I'm closing this due to duplication and housecleaning.
