### ISSUE TITLE
Clicking next button refreshes page

### ISSUE THREAD

**Issue by godhoomrohit** [stevenwanderski/bxslider-4#679]
Once we reach last slide and clicks next, the page refreshes(by giving js error  - top is null). I examined the source and divs were not getting cloned. i.e. bx-clone divs are missing. 
Urgent help needed. 

Thanks.

**Comment by Tidal-Wave** [comment]
Closing due to age and lack of examples to help address issue. If you would like to continue please reopen with more information.
