### ISSUE TITLE
Works only when i remove document.ready

### ISSUE THREAD

**Issue by ubiq1er** [stevenwanderski/bxslider-4#683]
Hi,

So i have this situation where my bxslider plugin only works properly when i remove the document.ready from the initialization code.
If i leave the usual code with the document.ready, i get an infinite loop on the bx-loading.

My page contains some ajax blocs but my bxslider div is not in one of them.

I'm not complaining too much here, beacause hey, it works after all, but i must admit that i'd like to understand.

Can't show you the page, working on it on my local server by now.

Thanks,

Regis

**Comment by Tidal-Wave** [comment]
Closing because of [possible duplicate] (https://github.com/stevenwanderski/bxslider-4/issues/560)
