### ISSUE TITLE
prevText and nextText buttons doesn't work if text is empty

### ISSUE THREAD

**Issue by BrodaNoel** [stevenwanderski/bxslider-4#684]
prevText and nextText buttons doesn't work if text is empty.

I have a DIV width a image inside, and it doesn't work on this way:

$('.miniSlider.categorias .bxslider').bxSlider({
				minSlides: 1,
				maxSlides: 4,
				slideMargin: 10,
				slideWidth: 240,
				prevSelector: '.miniSlider.categorias .sliderPrev',
				nextSelector: '.miniSlider.categorias .sliderNext',
				prevText: '',
				nextText: '',
				pager: false
			});

It just work if I do that:

$('.miniSlider.categorias .bxslider').bxSlider({
				minSlides: 1,
				maxSlides: 4,
				slideMargin: 10,
				slideWidth: 240,
				prevSelector: '.miniSlider.categorias .sliderPrev',
				nextSelector: '.miniSlider.categorias .sliderNext',
				prevText: '<',
				nextText: '>',
				pager: false
			});

**Comment by Tidal-Wave** [comment]
It inserts into the link whatever you put in `prevText` or `nextText`. if you want to style them as empty buttons you will need to give them dimension otherwise they will fold up and not be visible.
