### ISSUE TITLE
How to show caption in Carousels De-mystified slider

### ISSUE THREAD

**Issue by sahadat5021** [stevenwanderski/bxslider-4#687]
How to show caption in every image in Carousels De-mystified slider. There was an example http://bxslider.com/examples/carousel-demystified. It works fine. But when I set caption is ture then it will broke and dont work. I want to use this slider http://bxslider.com/examples/carousel-demystified with caption. Now what to do

**Comment by Tidal-Wave** [comment]
When using caption feature images must have a `title` attribute. We are exploring a more robust caption feature in future updates.
