### ISSUE TITLE
example of anchor tag in caption 

### ISSUE THREAD

**Issue by davehallowell** [stevenwanderski/bxslider-4#691]
Hello, just started working with bxslider v4.1.2 specifically.  I need to place anchor tags in my captions.  I see that this is something that was added recently.  I looked at several issues (#523, #434, #213, #193) but I haven't found an example that works for me.  This is what I currently have:
<li>
      <img src="images/EnGen.jpg" title="Caption 1" data-url="http://google.com" />
</li>

and then I have included these options:
captions: true, hyperlinks: true

The captions show on the slider, but it is not linked.

Do you have a working example I can see?

Thank you.

**Comment by Tidal-Wave** [comment]
Hi @davehallowell, my name is Eric, and i've been added to the project to help maintain it. 

What you linked to is from a fork, and currently isn't in the master branch. I am working to push some immediately needed updates, but will look at adding this type of feature asap.

**Comment by llahnoraa** [comment]
I am using 4.1.2 and does not work on carousel or slider.
