### ISSUE TITLE
Automatic adjustment of pager button vertical position

### ISSUE THREAD

**Issue by RayGX** [stevenwanderski/bxslider-4#692]
Although the vertical position of the pager buttons can be controlled with the css file, I have a web site with multiple slide shows which require anything from a single row to 5 rows of pager buttons due to the variable amount of slides on the respective pages.  A single css setting for pager button vertical position just doesn't work well in this situation.  An automated vertical position which would place the top row (of x rows) of pager buttons just below the slide image as the current css setting does for a single row would be great.

**Comment by Tidal-Wave** [comment]
Closing issue due to lack of example of the issue and vagueness of request.
