### ISSUE TITLE
Form error within last <li>-element

### ISSUE THREAD

**Issue by limehub** [stevenwanderski/bxslider-4#696]
If you use form inputs and associate the labels to be clicked on, it does not focus on the associated input when the label is clicked. Happens with both methods to associate a label to an input: for=id as well as input within the label-tag.
This only seem to happen within the last list-element.

**Comment by Tidal-Wave** [comment]
Closing due to lack of example of issue. If you would like to pursue this, please reopen with more information and an example of the issue.
