### ISSUE TITLE
After adding bx slider the images are getting cloned

### ISSUE THREAD

**Issue by doticonic9** [stevenwanderski/bxslider-4#697]
After adding bx slider the images are getting cloned, a class seems to appear name bx-clone. please solve this issue asap

**Comment by Tidal-Wave** [comment]
Clones are used to achieve the "infinite loop" effect. Unless I am missing something this is currently the expected behavior.

**Comment by doticonic9** [comment]
ok, but how did you achieve infinite loop without creating clones - slider which is on bxslider.com's homepage.

**Comment by Tidal-Wave** [comment]
The homepage slider is using fade so it doesn't need to visually loop the slides with transition, hence no clones. It's just fading a stack of images.

**Comment by doticonic9** [comment]
Can you please give the code for this ?






Sent from Windows Mail





From: Eric Wafford
Sent: ‎Monday‎, ‎January‎ ‎19‎, ‎2015 ‎7‎:‎05‎ ‎PM
To: stevenwanderski/bxslider-4
Cc: doticonic9





The homepage slider is using fade so it doesn't need to visually loop the slides with transition, hence no clones. It's just fading a stack of images.

**Comment by Tidal-Wave** [comment]
Use `mode: 'fade'` option as outlined in the [docs](http://bxslider.com/options).
