### ISSUE TITLE
Slider script changes all fonts on site and they start look bad, more problems with small size text

### ISSUE THREAD

**Issue by idem84** [stevenwanderski/bxslider-4#699]
Before:

![before](https://cloud.githubusercontent.com/assets/2977412/5410320/55128b8c-8204-11e4-987a-4a02cfeb4de8.jpg)

After script load:

![after](https://cloud.githubusercontent.com/assets/2977412/5410332/70ffd12e-8204-11e4-9d39-4f6223f83298.jpg)

Added some font blur. This happen in Google Chrome and Mazila, in IE all ok,

**Comment by Tidal-Wave** [comment]
This is a [browser font rendering issue when using transitions, typically seen in webkit browsers] (http://stackoverflow.com/questions/10218039/css3-transition-messing-up-fonts-in-webkit). You can try to fix using `-webkit-font-smoothing: subpixel-antialiasing` to see if that helps.
