### ISSUE TITLE
Slider stops auto advancing 

### ISSUE THREAD

**Issue by elixirgraphics** [stevenwanderski/bxslider-4#702]
If you have a slider set to auto advance, if you open a new tab in the browser, and then go back to the page with the slider, the slider's auto advance has stopped. If instead of opening a new tab you open a new window, the auto advancing of the slideshow continues to work. This problem seems to occur in Safari and Chrome, but not in FireFox.

**Comment by Tidal-Wave** [comment]
Hey guys, my name is Eric and I have been added to the project to help maintain it and provide updates. I am aware of this issue and will be adding to the update punch list. I hope to address this issue in the next minor update.

**Comment by Tidal-Wave** [comment]
Fixed in 4.2.2

**Comment by lodalo** [comment]
cool thanks for the fix!
