### ISSUE TITLE
BX Slider on Fade mode 'flashing'

### ISSUE THREAD

**Issue by BenComicGraphics** [stevenwanderski/bxslider-4#703]
aria.steadfastlight.com

Have BX Slider set to fade mode, but it 'flashes' on each transition.  Need help.

**Comment by NJWebDesign** [comment]
I'm not using display: flex and just cannot fix this issue, which is affecting Microsoft Edge browser.
I've tried various adjustments to the speed parameter, have tried useCSS: false.

Anything else I can try?

Example of this is available at www.tradmusic.com

Thank you.
NJ
