### ISSUE TITLE
Captions with bxslider

### ISSUE THREAD

**Issue by 8Sarit** [stevenwanderski/bxslider-4#706]
I am using the bxslider as my template. i have to display in each picture a caption at the bottom of the picture.

<ul class="bxslider">
                    <pictures:each bean="${bean}" companyType="${companyType }" pictureList="${pictureList }">
                        <g:if test = "${picture.getLargeImageURL() != null && picture.getThumbnailImageURL() != null}">
                            <li>
                                    <img style="height: 240px; width: 100%"  src="${picture.getLargeImageURL()}" alt="${picture.copyright.copyrightify()}" title="${picture.caption.linkify()}"/>
                            </li>
                        </g:if>
                        <g:elseif test="${largeFileName != null && thumbnailFileName != null }">
                            <li>
                                    <img src="${resource(dir:'imgService',file:largeFileName)}" style="height: 240px; width: 100%" alt="${picture.copyright.copyrightify()}" title="${picture.caption.linkify()}"/>
                            </li>
                        </g:elseif>
                    </pictures:each>
                </ul>

How can I display the caption?

**Comment by Tidal-Wave** [comment]
Currently bxSlider will [pull the caption from the image `title` attribute and append it into a span for the slide](https://github.com/stevenwanderski/bxslider-4/blob/master/jquery.bxslider.js#L695-L705) if you set the [`caption`] (https://github.com/stevenwanderski/bxslider-4/blob/master/jquery.bxslider.js#L27) option to `true`. We will look at improving the caption system in a future update.
