### ISSUE TITLE
Extra padding being added on mobile

### ISSUE THREAD

**Issue by Jakobud** [stevenwanderski/bxslider-4#717]
I have a bxslider at the top of this page here:

http://m.lifeproof.com/en/lifeactiv-accessories

View it in mobile (or use the mobile emulator in Chrome dev tools for example). The slider has some extra padding at the top and right side of it. The images should simply take up the full width and height of the container but they are not.

Is this a bug? I don't see any CSS that is attributing to the extra padding.

![image](https://cloud.githubusercontent.com/assets/87356/5842031/d487e992-a15e-11e4-981d-036daf326a96.png)

**Comment by Tidal-Wave** [comment]
a partial fix for this can be found here: https://github.com/stevenwanderski/bxslider-4/pull/517

We are in the process of merging this in for our 4.1.3 update now, so if you want to make the change manually feel free. This fixes the right side issue, as far as the top, It seems like something is forcing the height of the viewport slightly.

**Comment by Tidal-Wave** [comment]
I just pushed our 4.1.3 update which contains this fix among others. See if this helps. If you still have the upper issue let me know.
