### ISSUE TITLE
Restart after click?

### ISSUE THREAD

**Issue by curvedb** [stevenwanderski/bxslider-4#719]
Is there a way to continue slideshow after click on navigation and pager links?

**Comment by Tidal-Wave** [comment]
Currently the slider stops auto when those buttons are clicked. This can be seen [here] (https://github.com/stevenwanderski/bxslider-4/blob/master/jquery.bxslider.js#L713-L717) for example. 

We have on our list to adjust this with options in a future update, but for now a quick fix is to remove the `if (slider.settings.auto) el.stopAuto();` from the click bindings.

**Comment by Tidal-Wave** [comment]
Actually, after consideration, at this point it would be better to instead place `el.startAuto();` at the end of each click binding function because you might create odd behavior if the `el.goToNextSlide();` function executes at the same time.

**Comment by curvedb** [comment]
Thank you! Is there any callback for that? I am not very familiar with jquery :/

**Comment by Tidal-Wave** [comment]
you could try using the `onSlideAfter` callback to just call `el.startAuto()` but it would call it unnecessarily. There are currently no callbacks for the control clicks.
