### ISSUE TITLE
Page refresh brings me to the slider

### ISSUE THREAD

**Issue by fourroses666** [stevenwanderski/bxslider-4#721]
When I refresh my page it brings me to the slider (looks like the next prev buttons)
they have but when removing the href="" or use javascript:void(0) it still refreshes to that point.

Maybe a solution can be found for this?
Looking on google I came up to preventDefault.

http://api.jquery.com/event.preventDefault (offline now)

**Comment by Tidal-Wave** [comment]
Usually when a page jumps like this there is a issue with hashes in the url. 

The controls already use `preventDefault` to stop normal propagation and shouldn't do this. Are you using custom selectors? I'll need a redacted code demo of the issue if you need general help, but this shouldn't be an issue normally.

**Comment by fourroses666** [comment]
I don't know whats causing the jumping to. when I remove the slider the jumping stops so it has to be the banner. see here: http://tinyurl.com/k3ssxqd

	<script>
		$(document).ready(function(){
			$('.bxslider').bxSlider({
				mode: 'fade',
				speed: 600,
				randomStart: true,
				infiniteLoop: true,
				useCSS: true,
				touchEnabled: true,
				pager: false,
				controls: true,
				auto: true,
				captions: true,
				pause: 7000,
				responsive: true
			});
		});
	</script>

**Comment by Tidal-Wave** [comment]
Im not experiencing this issue on latest version of chrome, safari, or firefox. In fact, the navigation controls don't even use hashes, so this can't be your issue. Im not sure I even get the problem in general. I've scrolled down to the bottom of your page and hit refresh and (the latest versions) of all browser return to the same general position I was at before refreshing the page. 

What browser are you using?

**Comment by fourroses666** [comment]
correct, it only happens on firefox on my pc win7. still a bit weird, has to do with the banner.

**Comment by Tidal-Wave** [comment]
So in doing a little research I don't know if this is an edge case that we can deal with at the moment:

https://github.com/Modernizr/Modernizr/issues/720

There seems to be an issue with FF and `overflow:hidden` in general, as seen by this issue that is currently in modernizr too. 

I will try to track the issue and the changes, but for now I would just chalk it up to browser incompatibility.

**Comment by fourroses666** [comment]
thanks for looking for a solution. hope FF will kill this little bug
