### ISSUE TITLE
v 4.1.3 breaks bxloader.gif

### ISSUE THREAD

**Issue by DanFernandez-IT** [stevenwanderski/bxslider-4#722]
Completely unmodified bxSlider version 4.1.3 does not load the loading .gif upon page load. Controls (L/R arrow) show up where the slider should be, but the controls do not go into place until the images that the slider is supposed to load actually loads for the client device. Had to revert to 4.1.2 for the loader gif to function.

**Comment by Tidal-Wave** [comment]
4.1.3 made no changes to `slider.loader`, could you be a little more specific?

**Comment by DanFernandez-IT** [comment]
v 4.1.3, completely unmodified, is up on http://www.staging.santasusana.org/. Notice that the loader does not appear and the controls are out of place until the slider images load. http://www.santasusana.org/ is v 4.1.2, and the loader gif displays as expected.

**Comment by Tidal-Wave** [comment]
Thank you for this. It seems that the loading gift is there, but because of a change in the last update the slider doesn't have any height until the images load. I'll try to push update to fix this as soon as possible

**Comment by DanFernandez-IT** [comment]
Problem is in jquery.bxslider.min.js

I tried out reverting all changes from v4.1.3 to 4.1.2 for the .css and the main .js file, and that had no effect.

I then reverted to v4.1.2 for the min.js file, and the loader started working again.

**Comment by Tidal-Wave** [comment]
good to know. When I took over the project there where some documented issues with differences with 4.1.2 `jquery.bxslider.js` and `jquery.bxslider.min.js` so it must have been some difference there because I compiled 4.1.3 with gulp so the min and regular files should be identical. I will comb through the 4.1.2 min file and commits and try to identify the differences with the main js file. Sorry for the confusion, I walked into taking over this project kind of suddenly so I'm getting bearings on the issues at hand.

**Comment by DanFernandez-IT** [comment]
I submitted a pull request that fixes this issue (#723).

**Comment by DanFernandez-IT** [comment]
Bingo, found the commit that breaks the loader.gif: #714.

**Comment by DanFernandez-IT** [comment]
v4.1.3 is completely fine, except for line 196 in the .js file, which changed position: 'relative' to position: 'absolute' ... changing the 4.1.3 js to position: 'relative' fixes this entire issue.

**Comment by DanFernandez-IT** [comment]
I submitted a pull request that fixes this issue (#724).

**Comment by Tidal-Wave** [comment]
@DanFernandez-IT This should be available in 4.2.0, thanks for looking into it for me. Because I was in the middle of the update I didn't merge your PR, but did revert the change made.
