### ISSUE TITLE
Auto start carousel

### ISSUE THREAD

**Issue by alexanderkenney** [stevenwanderski/bxslider-4#725]
There seems to be a bug in the minified version of the bxslider javascript. 

Use Case:
Set a carousel to auto: true and use the jquery.bxslider.min.js file. The selected slide is shown, but the dot underneath is not selected and the carousel does not auto start.

Switch to jquery.bxslider.js and everything works fine.

**Comment by Tidal-Wave** [comment]
I will need to you create an isolated example if you want help. I setup a [fiddle](http://jsfiddle.net/ewafford/rLavm1qh/) that uses the latest `jquery.bxslider.min.js` and uses `auto: true` and the issue you are describing doesn't happen.

**Comment by alexanderkenney** [comment]
Hi Steven,

It looks like your jsfiddle uses the full JS. I don’t have the problem with the full JS, only the -min.js. I updated the bxslider init code with what I was using on the jsfiddle example and it worked just fine! It must have been something I had in my code. Sorry. If I come across it again, I will let you know.

Best Regards,

Alexander Kenney


Please consider the environment before printing this email

**Comment by Tidal-Wave** [comment]
Sorry, I forgot to save the fiddle that I revved for this issue. It should be using the min.js version now with no issue. Glad you got it working. 

PS - My name is actually Eric, I am now helping steven maintain this project.   ;)

**Comment by alexanderkenney** [comment]
Thanks Eric. Really nice carousel by the way. Keep up the good work!




Best Regards,

Alexander Kenney

Founder, UBQO Limited
+44 (0) 77 7557 8801

Please consider the environment before printing this email

**Comment by Tidal-Wave** [comment]
Hey thanks! We are going to be pushing a big update soon so keep an eye out. I specialize in modern front-end stacks so we will be introducing gulp build script, less, linting, JSCS, UMD support, etc. Once we modernize the stack we will begin working on creating a plugin system and custom transitions along with some other things and bug squashing.
