### ISSUE TITLE
Caption not rendering

### ISSUE THREAD

**Issue by BHWD** [stevenwanderski/bxslider-4#726]
I am trying to include a caption with a link however i cannot get the caption to come up. The link is not vital at the moment but the caption is. The code i have is below. Any suggestions?

    <div class="col-md-12">
    

        
        <ul class="bxslider">
          <li><img  title="Funky roots" data-url="http://your-url1.com" src="<?php echo get_template_directory_uri(); ?>/img/jet-slide.png" /></li>
          <li><img src="<?php echo get_template_directory_uri(); ?>/img/rv-slide.png" title="Automatically generated caption"></li>
        </ul>
        

      </div>
      

       <script>
        jQuery(document).ready(function($) {
          
         $('.bxslider').bxSlider()({
			   captions: true,
		 });
          
        });
      </script>

**Comment by Tidal-Wave** [comment]
Here is a basic example of using the current version: http://jsfiddle.net/ewafford/rLavm1qh/

Nothing about the code you posted really pops out to me as wrong... I would need to see more to determine if maybe something in your css is conflicting with bxslider. If you can't create an isolated demo, maybe paste in your DOM here so I can see it? There should be a `bx-caption` div in every slide if its working correctly.

**Comment by Tidal-Wave** [comment]
Also, as far as links in the captions go, another option is to generate your captions manually in your `li` and style it appropriately. Currently bxslider's caption system is pretty basic. We plan on revamping it in a future update.

**Comment by BHWD** [comment]
Hi @Tidal-Wave, 

I am using this with wordpress and have the slider working but without the caption. No span is being generated upon page load and there are no console errors either. It works if I manually add the caption within the LI so that is good enough for me to be honest.

thank you for your help.

**Comment by BHWD** [comment]
Okay Actually, if i put any option in there it doesnt work. The slider controls work but if i put auto:true nothing happens.

**Comment by Tidal-Wave** [comment]
That is really odd. I just tested multiple options combined with captions and everything seems to be working fine. If you are satisfied with manual caption design I will close the issue, but the behavior your describing doesn't happen in isolation, so just be aware that there might be other issues going on with whatever you are working on.

**Comment by aderchox** [comment]
I have the same problem. Also I'm testing it in a bare html css example without any styling other than the stylesheet of the bxslider itself(jquery.bxslider.css). The slider and its transitions are working just fine but the captions:true doesn't do what it's supposed to do(show the captions derived from the title attribute of img tags.
