### ISSUE TITLE
Broken Release 4.1.3

### ISSUE THREAD

**Issue by samstoller** [stevenwanderski/bxslider-4#729]
The latest release, tagged 4.1.3, contains a serious bug with the thumbnail pager. A fix for that bug has been committed (SHA: 1e6b1e7ae8bfa0b104daf95bef6ca0256a558ad5) but not tagged with a new version.

This means that dependency and package managers specifying 4.1.3 will pull the broken version instead of the latest commit on the master branch.

Can we get a new tagged version to solve this issue? Thanks.

**Comment by Tidal-Wave** [comment]
We just pushed 4.2.0 with a new tag. Sorry for any issues.

**Comment by samstoller** [comment]
Np. Appreciate the quick update.

**Comment by Tidal-Wave** [comment]
My pleasure guys. Once again, my bad. I blame working late. 

As a note: If you are familiar with the new build processes mechanisms, you can rebuild the `dist` yourself now by running `gulp` or `gulp scripts`.
