### ISSUE TITLE
Dist file has merging conflicts

### ISSUE THREAD

**Issue by easingthemes** [stevenwanderski/bxslider-4#731]
File: `dist/jquery.bxslider.js` has merging conflicts.
File `src/jquery.bxslider.js` is ok.

Bower use this file as main.

Since I saw changes few hours ago, I'm not going to create pull request, hoping that you'll see this.

Thanks,
Dragan

**Comment by Tidal-Wave** [comment]
This has been fixed. Sorry that snuck past me when I pushed.

**Comment by easingthemes** [comment]
Thanks for quick response.

**Comment by Tidal-Wave** [comment]
My pleasure guys. Once again, my bad. I blame working late. 

As a note: If you are familiar with the new build processes mechanisms, you can rebuild the `dist` yourself now by running `gulp` or `gulp scripts`.
