### ISSUE TITLE
Multiple Sliders, Multiple CSS

### ISSUE THREAD

**Issue by zuhloobie** [stevenwanderski/bxslider-4#732]
Using a few BXSLIDERS on a page and they work great, but how can one override the default CSS so that each can look different? For instance, 1st would be the standard slider, 2nd would have no border and different background, and 3rd would have a transparent background with no border.

Possible?

**Comment by Tidal-Wave** [comment]
Assuming you give each slider a unique ID you should be able to target them individually and override the theme css for each slider. The theme css portions are optional. You can even remove those portions or modify them. 

If you are familiar with LESS, there is now a LESS file that you can use and compile against too.

**Comment by zuhloobie** [comment]
Yes, each slider has a unique ID, but they all feed off the default CSS as I'm unaware how to override it. If you have a link to a resource so I can learn, I'd be grateful. No, not familiar with LESS.

**Comment by Tidal-Wave** [comment]
Overriding CSS is a fairly basic concept. The important part is order. Any CSS that you write just needs to come after bxsliders CSS. What that means is that if you write something your own stylesheet just include it after bxsliders CSS. Then target the ID for the slider and write the CSS needed to style the slider how you want. If you don't have a basic understanding of CSS then LESS will do you no good.

**Comment by zuhloobie** [comment]
Yeah, I haven't had problems in the past with CSS or overriding it and knowing it is something basic that I'm missing is aggravating. I also haven't tried to override with 3 separate instances before. I have my CSS being sourced after bxslider's CSS as you stated, but it still isn't overriding it. I will keep pecking at it, thanks.

**Comment by Tidal-Wave** [comment]
If you have a demo or link I can look at it for you but it should be fairly straight forward.

Setup a fiddle, show me your css, but in general it really should be no different.

**Comment by zuhloobie** [comment]
I'll keep pecking and get back to you if I need assistance - hate asking for help over something silly. Thanks again.
