### ISSUE TITLE
bx-slider trimming right border off?

### ISSUE THREAD

**Issue by NJWebDesign** [stevenwanderski/bxslider-4#734]
I have a page that displays lists of properties for a real estate company:
http://1080422389.n303457.test.prositehosting.co.uk/index.php

These display nicely, with a 1px border on both sides.  However if you view a page that doesn't have a large list of properties:
http://1080422389.n303457.test.prositehosting.co.uk/Cairnryan-property-for-sale.php

...the border is trimmed off the far right box.  It's driving me mental!

The HTML:

     <div class="slider">
	<div class="slide">
	<a href="#"><img src="http://1080422389.n303457.test.prositehosting.co.uk/property-for-sale/11HanoverSquareStranraer.jpg" width="400" height="300"></a>
	<div class="slidecontenttop">
		<p class="price">&pound;100000</p>
	</div>

	<div class="slidecontentmid">
		<p>Summmary Text</p>
	</div>

	<div class="slidecontentbtm">
		<div class="slidecontentbtmleft">
			<p><strong>Town</strong></p>
		</div>
		
		<div class="slidecontentbtmright">
			<p><a href="#"><span class="glyphicon glyphicon-search"></span> View</a></p>
		</div>
	</div>
	</div>
    </div>

The custom.js:

    $(document).ready(function(){
    $('.slider').bxSlider({
    slideWidth: 400,
    minSlides: 2,
    maxSlides: 12,
    moveSlides: 2,
    slideMargin: 10,
	ticker: false,
	speed: 1000,
	nextSelector: '#slider-next',
  	prevSelector: '#slider-prev',
  	nextText: '<button type="button" class="btn btn-sm btn-default">Next &nbsp;&raquo;</button>',
  	prevText: '<button type="button" class="btn btn-sm btn-default">&laquo;&nbsp; Previous</button>'
    });
    });

The important bits of the CSS:

    .bx-wrapper {
	position: relative;
	margin: 0 auto 60px;
	padding: 0;
	*zoom: 1;
    }

    .bx-wrapper img {
	max-width: 100%;
	display: block;
    }

    .bx-wrapper .bx-viewport {
	left: 0;
	right: 0;
	bottom: 0;
	background: rgba(235,235,235,0.9);
	width: auto;
	
	/*fix other elements on the page moving (on Chrome)*/
	-webkit-transform: translatez(0);
	-moz-transform: translatez(0);
    	-ms-transform: translatez(0);
    	-o-transform: translatez(0);
    	transform: translatez(0);
    }

    .slide {
	font-family: "open-sans";
	background-color: #fff;	
	border: 1px solid #6F9258;
	height: 480px;
    }

Hoping someone can help.  Thank you.
NJ

**Comment by Tidal-Wave** [comment]
Your slides are actually 402px because of the borders. This is a box-sizing issue. There are a few ways to solve this. One option is to try `box-sizing: border-box` on the slides.

**Comment by NJWebDesign** [comment]
Changed my CSS to:

    .slide {
	font-family: "open-sans";
	background-color: #fff;
	box-sizing: border-box;	
	border: 1px solid #6F9258;
	height: 480px;
    }

It didn't work. :(
NJ

**Comment by Tidal-Wave** [comment]
Looks like your initialization changed too... 
```
$(document).ready(function(){
  $('.slider').bxSlider({
    slideWidth: 398,
    minSlides: 2,
    maxSlides: 12,
    moveSlides: 2,
    slideMargin: 10,
	ticker: false,
	speed: 1000,
	nextSelector: '#slider-next',
  	prevSelector: '#slider-prev',
  	nextText: '<button type="button" class="btn btn-sm btn-default">Next &nbsp;&raquo;</button>',
  	prevText: '<button type="button" class="btn btn-sm btn-default">&laquo;&nbsp; Previous</button>'
  });
});

```

`slideWidth` needs to be 400.

**Comment by NJWebDesign** [comment]
I changed the initialization because box-sizing didn't work.  I've put slideWidth back to 400 and the border is still missing.  Weird thing is, in Firebug I can see the border when I highlight the <div class="slide" style="float: left; list-style: outside none none; position: relative; width: 402px; margin-right: 10px;"> tag (the slide that's missing the border).  Appreciate the help, thank you.  Hopefully we'll find a solution.

**Comment by Tidal-Wave** [comment]
I'm getting gateway errors on your links now. If you can get that up again I can take a look.

**Comment by Tidal-Wave** [comment]
Was able to access it and there are a couple of things I think here. I made a simplified fiddle.
http://jsfiddle.net/ewafford/aym8erof/

First, please start by updating bxslider. It looks like you are running an old version. The fiddle above is pulling the latest version off github.
Once you change that, look at my js in the fiddle, I've made a few changes to it.
The CSS I pulled straight from your style css. (I added an override to bx-wrapper border and shadow)

This works for me. Let me know if that helps.

**Comment by NJWebDesign** [comment]
You've restricted the max slides to 1 yet I need the slides to work full width if there are enough corresponding records:
http://1080422389.n303457.test.prositehosting.co.uk/

Also, I updated BX Slider and now I have carousel type circle navigation, is it called a pager, underneath the image?  How do I remove that?

Your example works on GitHub, but not on our site (I've copied your GitHub example and implemented it on our site):
http://1080422389.n303457.test.prositehosting.co.uk/Cairnryan-property-for-sale.php

This was pretty much how it was working before - the only discernable difference I can see is that you've restricted the max slides to 1 and removed the $(document).ready(function() from the JS.  But it has not resolved it on our domain.

This is proving to be a tricky one - which I'm kind of relived about because I thought I was going mad earlier today!  Appreciate the help.  Thank you.
NJ

**Comment by Tidal-Wave** [comment]
I restricted it to one because I thought thats what you where trying to do. Feel free to put your settings back concerning min/max. 

The pager can be removed by adding `pager:false` to your init settings. 

The `$document.ready` call isn't in the fiddle because it's assumed in fiddle. You need it and should put it back. This might help.

When I removed the default theme styles off `bx-wrapper` (box-shadow, 5px border, background), it worked out just fine on my end.

**Comment by NJWebDesign** [comment]
Thank you Tidal-Wave.  Removing the default theme styles from bx-wrapper seemed to do it.  Really appreciate it, thank you.

**Comment by Tidal-Wave** [comment]
No problem.
