### ISSUE TITLE
How to make BX Slider responsive?

### ISSUE THREAD

**Issue by NJWebDesign** [stevenwanderski/bxslider-4#735]
I have a list of properties for a real estate company that uses BX Slider for the display and it works really neatly in tablet/desktop view:
http://www.jb-graham.co.uk/index.php

Our slider width is specified in our custom.js file:

    $(document).ready(function(){
    $('.slider').bxSlider({
    slideWidth: 400,
    minSlides: 1,
    maxSlides: 7,
    moveSlides: 2,
    slideMargin: 10,
	ticker: false,
	speed: 1000,
	pager: false,  
	nextSelector: '#slider-next',
  	prevSelector: '#slider-prev',
  	nextText: '<button type="button" class="btn btn-sm btn-default">Next &nbsp;&raquo;</button>',
  	prevText: '<button type="button" class="btn btn-sm btn-default">&laquo;&nbsp; Previous</button>'
    });
    });

We use media queries for most of our static HTML stuff to respond to mobile devices but is there a way to have a different custom.js file load if the device is a mobile?

At the moment, when viewed in a mobile device, it's still displayed at 400 width.
Thank you.
NJ

**Comment by Tidal-Wave** [comment]
![screen shot 2015-02-10 at 10 36 17 am](https://cloud.githubusercontent.com/assets/4382867/6131339/c0e4bf3e-b110-11e4-975a-cb030880a03a.png)

It's responding on it's own. There are other things like your logo that are pushing your body bigger then your viewport, but the slider seems to be working as expected. 

One thing to note: you enforce a numeric height on your images, this will cause it to distort at smaller viewports because the width changes but the height can't. I would set those to `height: auto; max-height: 300px`

**Comment by NJWebDesign** [comment]
The slider is the same size in mobile view as it is in desktop view.  It's always 400px wide.

What I meant was, is it possible to shrink the slider to be 200px wide in mobile view?
As you can see from your example above the slider ends up occupying almost all of the view and only one property is displayed at one time.

I have the height and width forced because I am using an Image Resizer extension that requires it.  The client uploads photographs at any size and the extension creates a thumbnail on the fly, cropping the image from center.

Really appreciate the help, thank you.
NJ

**Comment by Tidal-Wave** [comment]
You can reload the slider with a new configuration. Check out this for one example: https://github.com/stevenwanderski/bxslider-4/issues/736#issuecomment-73825729

**Comment by NJWebDesign** [comment]
Hi.  I changed what I already had in custom.js (above) to this:

    $(document).ready(function(){
    $('.slider').bxSlider({
    var widthMatch = matchMedia("all and (max-width: 767px)");
    var widthHandler = function(matchList) {
    if (matchList.matches) {
        slider.reloadSlider({
            minSlides: 1,
            maxSlides: 1,
            slideWidth: 500,
            slideMargin: 10
        })
     } else {
        slider.reloadSlider({
            minSlides: 4,
            maxSlides: 4,
            slideWidth: 500,
            slideMargin: 10
        })
      }
     };
    moveSlides: 2,
    ticker: false,
    speed: 1000,
    pager: false,  
    nextSelector: '#slider-next',
    prevSelector: '#slider-prev',
    nextText: '<button type="button" class="btn btn-sm btn-default">Next &nbsp;&raquo;</button>',
    prevText: '<button type="button" class="btn btn-sm btn-default">&laquo;&nbsp; Previous</button>'
    });
    });

But I'm getting syntax errors all over the place.  Please excuse my ignorance, and my lack of knowledge, but I don't have JS experience and whilst I can make sense of some things my lack of basic knowledge causes me problems.  Hope you can point me in the right direction.  Thank you.
NJ

**Comment by Tidal-Wave** [comment]
You are loading in the mediaMatch calls into the options of bxslider. Try something more like this:

```
$(document).ready(function(){
    var slider = $('.slider').bxSlider();
    var widthMatch = matchMedia("all and (max-width: 767px)");
    var widthHandler = function(matchList) {
        if (matchList.matches) {
            slider.reloadSlider({
                minSlides: 1,
                maxSlides: 1,
                slideWidth: 500,
                slideMargin: 10,
                moveSlides: 1,
                pager: false,  
                nextSelector: '#slider-next',
                prevSelector: '#slider-prev',
                nextText: '<button type="button" class="btn btn-sm btn-default">Next &nbsp;&raquo;</button>',
                prevText: '<button type="button" class="btn btn-sm btn-default">&laquo;&nbsp; Previous</button>'
            })
        } else {
            slider.reloadSlider({
                minSlides: 4,
                maxSlides: 4,
                slideWidth: 500,
                slideMargin: 10,
                moveSlides: 1,
                pager: false,  
                nextSelector: '#slider-next',
                prevSelector: '#slider-prev',
                nextText: '<button type="button" class="btn btn-sm btn-default">Next &nbsp;&raquo;</button>',
                prevText: '<button type="button" class="btn btn-sm btn-default">&laquo;&nbsp; Previous</button>'
            })
        }
    };
});
```

The idea:

Generically initialize the slider and store it in `slider`, then setup MediaMatch to determine the exact settings based on screen size and reload it as needed. 

Also note: this technique will require you to include a [polyfill] (https://github.com/paulirish/matchMedia.js/) for full browser support. It's also not the only way to do this, feel free to research respond.js or other conditional js methods.
