### ISSUE TITLE
Can't get it set for devices...

### ISSUE THREAD

**Issue by NetworkGreenhouse** [stevenwanderski/bxslider-4#736]
I can't seem to strike a balance between desktop and devices. I don;t understand why I need to set an image width. I'd like to display 4 images wide on everything dfown to about mobile resolution... then only one, swipable on mobile.

I've looked through your documentation and cannot get it. It seems like the slide width in the carousel needs to be set, which makes it impossible to achieve both full width 4 slides on desktop, and 1 slide on mobile.

Can someone help with some code?

Thank you!!

**Comment by Tidal-Wave** [comment]
The slider needs to know width to do initial calculations. If you would like to stick to doing 4 images all the way down to mobile then switch to 1 image one way of doing this is combining it with something like matchMedia or any other conditional js method.

So your initial settings would be something like 

```
var slider = $('.bxslider').bxSlider();
```

Then, using matchMedia you can attach an event on your slider to reload it

```
var widthMatch = matchMedia("all and (max-width: 767px)");
var widthHandler = function(matchList) {
    if (matchList.matches) {
        slider.reloadSlider({
            minSlides: 1,
            maxSlides: 1,
            slideWidth: 500,
            slideMargin: 10
        })
    } else {
        slider.reloadSlider({
            minSlides: 4,
            maxSlides: 4,
            slideWidth: 500,
            slideMargin: 10
        })
    }
};
```

I've made a [fiddle](http://jsfiddle.net/ewafford/23dheegp/) that demos this. Please keep in mind that mediaMatch requires a [polyfill](https://github.com/paulirish/matchMedia.js/) if you need support for older browsers, and it's also not the only why you can achieve this type of thing.

**Comment by NetworkGreenhouse** [comment]
Works great... thanks so much...

**Comment by Tidal-Wave** [comment]
Np
