### ISSUE TITLE
Tickermode transitionend event bubbling

### ISSUE THREAD

**Issue by Mathiu** [stevenwanderski/bxslider-4#737]
Hi,

There is a "bug" that causes slider to reset on "transitionend" event when any element inside slider has css transition property. I believe its due to the event bubbling which causes child element event to trigger on parent.

Here's an example: http://jsfiddle.net/1jdqnhs1/ when you hover over image its reseting slider to the starting point.

I have also found a workaround or possible fix for it. After line 558 add this code:
```javascript
if(!$(e.target).is(el)) return;
```

Thanks for the amazing work!

**Comment by Tidal-Wave** [comment]
Thanks for the report, I'll take a look at this asap.

**Comment by Tidal-Wave** [comment]
Will be fixed in 4.2.4 update coming shortly, thanks for the report.
