### ISSUE TITLE
Initializing slider.initialized

### ISSUE THREAD

**Issue by waganse** [stevenwanderski/bxslider-4#748]
The obj "slider.initialized" is initialized in start(), but where is it called?
The destroySlider() does not work cuz it is undefined.

** slider.destroySlider() **
// don't do anything if slider has already been destroyed
if(!slider.initialized){ return; }

Thanks in advance.

**Comment by pushkeryadav** [comment]
before calling to initialize slider if you call destroy slider than it will break.

**Comment by Tidal-Wave** [comment]
Changed checks to use .data() so as to avoid this, and fixed the check for initialize before destroy. Coming in 4.2.4

**Comment by daviDGreshake** [comment]
For me worked this, because my Images could not be laoded:

var loadElements = function (selector, callback) {
			var total = selector.find('img, iframe').length;
			if (total == 0) {
				callback();
				return;
			}
			var count = 0;
			selector.find('img, iframe').each(function () {
                ++count;
				$(this).one('load', function () {
					if (count == total) callback();
				}).each(function () {
					if (this.complete) $(this).load();
				});
			});
		}

Just increase the iteration (++count) outside of the one()-method.
