### ISSUE TITLE
Bxslider in overlay only shows on window resize

### ISSUE THREAD

**Issue by shortwoodBE** [stevenwanderski/bxslider-4#749]
Hi,

I use the BxSlider on the startpage and in a overlay.
Only, the slider doesn't show in the overlay until I resize my browser window.
I can see the navigation but the images won't show... (unless I resize the window).

I'm not very good with JS so I'm kinda lost here.

http://makemakes.be/dev/RN

When I click, for instance, on "Studio 01". The overlay fades in... not showing the slider.
Is there any way I can make JS "emulate" a resize window?
I read about the redrawSlider? But don't know how to implement this...

Thx in advance.

**Comment by Tidal-Wave** [comment]
This page seems to work for me, and you seemed to have switched to using cycle for the overlay. Since there doesn't seem to be an issue I will close.
