### ISSUE TITLE
v4.2.3 via bower

### ISSUE THREAD

**Issue by ryanburnette** [stevenwanderski/bxslider-4#750]
I use bower to manage bxslider-4 as a dependency on many projects. For me at least, v4.2.2 doesn't function properly. Right now I'm having to manually grab v4.2.3 manually. I'm not sure if you intended to release it to Bower yet, but without a tag for v4.2.3 this version isn't available.

**Comment by Tidal-Wave** [comment]
My apologizes, I'm not sure why my tag disappeared. I pushed it back up.

**Comment by ryanburnette** [comment]
👏❤️
