### ISSUE TITLE
Adjust CSS of current slide

### ISSUE THREAD

**Issue by synergies** [stevenwanderski/bxslider-4#753]
I have a list of li elements that with mode: vertical so it scrolls up/down.  I am showing two elements at a time using minSlides: 2.  Using CSS I have setup a border between each element (except the first one) so it shows a break between the two elements.  The problem is when you go to next slide it shows  border of the top element as well as between both to and bottom elements.  I was hoping to use onSlideAfter to get the current slide and adjust the CSS to remove the border of the top slide.  However, I am not sure where to begin.  Any help would be greatly appreciated!

**Comment by Tidal-Wave** [comment]
Be happy to help. If I can start by asking: Is there a reason you don't use the margin option?

http://bxslider.com/examples/vertical-slideshow

If this isn't what you are trying to achieve then if you could setup a simple example on jsfiddle I will be happy to work through the issue with you.

**Comment by synergies** [comment]
Thanks for the update.  The slidemargin would work, but we decided to not use the vertical slide.
