### ISSUE TITLE
fading in Firefox shows image errors

### ISSUE THREAD

**Issue by lmachens** [stevenwanderski/bxslider-4#754]
Hi,
sometimes fading is not working correctly if I use it in Firefox (35.0.1).
Please take a look at and wait for 4-5 slides:
http://jsfiddle.net/lmachens/mz5cqhax/

Here is a screenshot of the behavior:
![image](https://cloud.githubusercontent.com/assets/10058950/6350362/835417b8-bc33-11e4-8b9c-4fe707790793.png)

I tried to use custom easing to avoid the problem but I can't make it work with fade-mode.

Thank you,

Leon

**Comment by Tidal-Wave** [comment]
I tested the latest version (36.0.0) mac and I see no issue. Unfortunately atm I don't have a way to test older versions. I will see if I can find a way. 

You are also pointing to an older version of the library from the main site. I suggest you rawgit or equivalent.

Im going to close for now but assign it to my "investigation" list.

**Comment by lmachens** [comment]
Thank you.

I updated to 36.0 and I see no issue too.
But the latest bxslider with 35.0.1 has the issue.
