### ISSUE TITLE
reload on multiple sliders doesn't work?

### ISSUE THREAD

**Issue by Cutlefish** [stevenwanderski/bxslider-4#755]
I have a page with multiple BXSlider and, when the user clicks a button, every slider needs to be reloaded with new images. Everything works fine when I have a single slider, but it stops working with more than one slider. When the reloadSlider() method is called I get a "$(...).reloadSlider is not a function" error.

Since the sliders are dinamically created (I don't know how many of them I'll have on the page), I can't create every single slider on his own like this:

var slider1 = $('#slider1').bxSlider();

var slider2 = $('#slider2').bxSlider(); ...

But I need to create them all at once with:

$('.slider').bxSlider();

But when I try to call $('.slider').reloadSlider(), I get the error above.

Can someone help me? Thank you.

**Comment by Tidal-Wave** [comment]
You need to call reloadSlider on the returned element, in your example that would be `slider1.reloadSlider()`.

The slider should be capable of setting up multiple returned selectors, assuming they all get the same options setup. So you could do `var sliders = $('#slider1, #slider2').bxSlider();` and then call reload on the stored object. 

I plan on an enhancement that would store the references back to the elements in a future update.

HTH

**Comment by Cutlefish** [comment]
Thank you for your reply.
I can't do what you say (var sliders = $('#slider1, #slider2').bxSlider()) because I don't know how may sliders I have. Each slider is generated from elements inside a database: some products may have 2 sliders, while other may have three.
This is the reason why I need to call $('.slider').bxSlider() and generate them according to the class .slider, and not by single ids.
I don't if this is a bug, but when calling sliders = $('.slider').bxSlider() on multiple sliders, the generated sliders object is a generic object, and not a bxslider object (thus, it doesn't have the reloadSlider method).

**Comment by Tidal-Wave** [comment]
I'll add this to my next sprint and see what I can do to push the enhancement along faster.

**Comment by Cutlefish** [comment]
Great! Thank you for your support.

**Comment by rodrigoruiz** [comment]
Did you manage to solve this problem? I'm running into a bug that requires this, or a bug fix https://github.com/stevenwanderski/bxslider-4/issues/807.

**Comment by Tidal-Wave** [comment]
Im working on pushing an update that will fix this by storing a reference with `.data()`, which should allow you to call methods on your selectors.

**Comment by Tidal-Wave** [comment]
I just pushed this update to development, and will move to master shortly. Feel free to try it out if you'd like. It should work as so:

`element.data('bxSlider').publicMethod()`
