### ISSUE TITLE
Feature Request: Call "refresh" slider as public method

### ISSUE THREAD

**Issue by noxbriones** [stevenwanderski/bxslider-4#759]
Is there a way to call a "refresh" function which is useful when calling the slider while their container is hidden ('dispaly:none'). One example, in a modal, I need to use a setTimeout to delay when a modal is called or else the slides are not calculated properly. Another example is, on an active/current slide, the height of the content changes, thus, I want to call a "refresh" to accommodate the new height of content.

There is already "resizeWindow", maybe this can be made public?
```javascript
$(window).bind('resize', resizeWindow);
```

This slider is awesome! Great job!

**Additionally, I am resizing the slider's container (not the window) and want it still to be responsive, thus, a call for a "refresh" would be helpful.

**Comment by Tidal-Wave** [comment]
On the second example concerning content height, have you tried the adaptiveHeight Setting?

I am sprinting on the next update so I will take a look at this.

**Comment by noxbriones** [comment]
Yes, adaptiveHeight is working great on "normal" use. The problem only occurs when you are on current slide, say slide1, which has an e.g., tabs. So when you are on slide1 and clicking on 2nd tab which has longer content than 1st tab, the content is cut-off. I think this could be easily fixed if we can call a "refresh". Awesome work, Thanks!

**Comment by Tidal-Wave** [comment]
Sorry for the delay, `redrawSlider()` should work for this.

**Comment by noxbriones** [comment]
Awesome! This is worth to be mention on the _options_ on documentation. Cheers!

**Comment by mh-nichts** [comment]
I would like to use this function, but it seems it doesn't exist anymore.
I tried it this way :

```javascript
mySlider.redrawSlider()
```
And I got an error : 
```
TypeError: mySlider.redrawSlider is not a function
```

Can you tell me if something is wrong ?

**Comment by mh-nichts** [comment]
My bad, I wasn't using the last version of bxSlider : it seems in v4.0 the redrawSlider() function didn't exist yet.
So now that I've installed v4.1.2, everything works like a charm.
I hope my comment can help someone facing the same issue.
