### ISSUE TITLE
Duplicate wrapper

### ISSUE THREAD

**Issue by lihao6485** [stevenwanderski/bxslider-4#762]
![screen shot 2015-03-05 at 9 50 23 am](https://cloud.githubusercontent.com/assets/3205345/6497623/2f492096-c31d-11e4-9209-71c29ddebdac.png)

Inside my bx-viewport, it has another bx-wrapper and bx-viewport, it makes like I have two slider on the same place.

**Comment by Tidal-Wave** [comment]
can I see your initialization code?

**Comment by lihao6485** [comment]
var slider;

if ($(window).width() > MIN_WIDTH) {
        slider = $('.testimonialsSlider').bxSlider({
            slideWidth: 300,
            minSlides: 3,
            maxSlides: 3,
            slideMargin: 50
        });
    } else {
        slider = $('.testimonialsSlider').bxSlider({
            slideWidth: $(window).width() * 0.7,
            minSlides: 1,
            maxSlides: 1,
            slideMargin: 50
        });
    }

when the browser is resize I will reload the slider base on MIN_WIDTH
slider.reloadSlider({
        slideWidth: $(window).width() * 0.7,
        minSlides: 1,
        maxSlides: 1,
        slideMargin: 50
    });

or

slider.reloadSlider({
        slideWidth: 300,
        minSlides: 3,
        maxSlides: 3,
        slideMargin: 50
    });

**Comment by Tidal-Wave** [comment]
This usually happens when the `.bxSlider()` is called on the same element more than once. Is there anyway that the code could be called twice somewhere?

**Comment by lihao6485** [comment]
I found that the problem is occurred when I calling the ``` .reloadSlider ``` after ``` .bxSlider() ``` on
```
$(document).on('ready', function () {

})
```
I removed the reload function and only check and reload the slider when windows is resized, the problem solved. But I still confusing why the problem doesn't occurred on my local machine but only production server.

Thanks for your help @Tidal-Wave .
