### ISSUE TITLE
4.2.3 doesn't work while 4.1.2 does

### ISSUE THREAD

**Issue by 01Kuzma** [stevenwanderski/bxslider-4#764]
Hi!
I've read the change-log, but haven't found any reference regarding major changes in init methods
The problem is that the 4.1.2 version works on web page while the 4.2.3 doesn't - it's hidden behind the background.
Here is the demo page: http://tedxmru.com/
By default the 4.1.2 is loaded, but if I change the 
<script src="js/jquery.bxslider.js"></script> 
to
<script src="js/jquery.bxslider.min.js"></script> loading the 4.2.3 - causes the problem.
The console is empty - no any errors

UPD. After some rework in order to force the slider to take full width & height of viewport the minified last version works. But there are two strange bugs:
With not minified version. Once I load the page then resize it to browser's minimal width and hit refresh button - the slider disappears.
With minified. Once I unresize window the slider appears but slides are overlapped and slider is stopped(non minified also doesn't play slides
![err](https://cloud.githubusercontent.com/assets/569504/6542767/a690ad68-c50c-11e4-837c-c98ed8b956c8.jpg)
).

**Comment by Tidal-Wave** [comment]
I am sprinting on the next update so I will take a look at this.

**Comment by Tidal-Wave** [comment]
It seems the demo is not longer using bxslider. Sorry if any delay caused you to change course. I would be happy to look at this further if you decide to use bxslider. Closing for now. 

As a note, I am fixing a small bug with slides that only contained text and a handful of IE issues for the 4.2.4, but Im unsure if that would have helped your issue.

**Comment by 01Kuzma** [comment]
Hi!
The demo has just moved to http://tedxmru.com/ from http://tedxmru.com/ted-mob it still uses the bxslider

**Comment by Tidal-Wave** [comment]
Oh sorry bout that.

**Comment by 01Kuzma** [comment]
No problem :+1: 
It seems that one part of  CSS code, especially this:
.bxslider, .bxslider li{
    height: 100% !important;;
}
fails on resize and refresh actions

**Comment by Tidal-Wave** [comment]
sorry, hit enter to soon, see above.

**Comment by 01Kuzma** [comment]
Yes, there is a problem with this library. I haven't found a 100% solution how to fix those errors. But if I locally comment this script(fully disable it) with it's all calls - the situation is the same.
Just try to resize the window rapidly, defining the different width and hit refresh once it will be less that a 767px

**Comment by Tidal-Wave** [comment]
Ok well lets start with the > 768 bug first then because I have seen this before. Basically the slider is unable to determine it's initial height because there are no images loaded so it gets set to 0, and this remains as an inline style so the `height: 100% !important` doesn't do anything. Once you resize over 768 you refresh the slider it looks like, so the height gets recalculated. The easy solution in this case is to wait until you know the images are loaded to initialize the slider.

**Comment by 01Kuzma** [comment]
Hm, and how I can solve it?
I have added a preloader - 'imagesLoaded' lib. As I understand - it should do this work...
The html preloader's part has images from the slider:
       	<div id="preload">
            <img src="img/bcg-news.jpg">
            <img src="images/slider/slide-1.jpg"> 
            <img src="images/slider/slide-2.jpg"> 
            <img src="css/img/sample.jpg">            
            <img src="images/speakers_bg.jpg">            
       	</div>

**Comment by Tidal-Wave** [comment]
if you are using imagesLoaded, you can place bxSlider init code in its callback in order to insure that the images are available. I can try to whip up an example shortly, but I'm trying to get 4.2.4 ready so bare with me. 

I was unable to get the overlapping slider issue to happen (Mac Safari Version 7.1.3) but I noticed you switched to 4.1.2 so maybe thats why.

**Comment by 01Kuzma** [comment]
Ok, it would be great if you post an example.
Thank you!

**Comment by 01Kuzma** [comment]
Also I've just opened the page with a Safari from another PC, so once the breakpoint is reached (the top nav disappears), the slider halts and doesn't play. Restoring the original width doesn't solve.

**Comment by Tidal-Wave** [comment]
start by moving your init code:

```
$('.bxslider').bxSlider({
        auto: true,
        easining: 'ease',
        controls: false,
        pager: false 
    });
```
into the callback for `imagesLoaded` like so: 

```
$body.imagesLoaded( function() {
        setTimeout(function() {

              // Resize sections
              adjustWindow();

              // Fade in sections
              $body.removeClass('loading').addClass('loaded');

        }, 800);
        $('.bxslider').bxSlider({
            auto: true,
            easing: 'ease',
            controls: false,
            pager: false 
        });
    });

```

Also note: you misspelled `easing`, not that that should matter, but the easing is not applied due to this. 

Im not seeing any issues with safari, are you speaking of Safari on Windows? That browser hasn't been supported for a while now, and I don't have access to test it at the moment. It's EOL was roughly 2012, so it very well may have some issues that just aren't fixable.

**Comment by 01Kuzma** [comment]
Hi!
Thank you for you code!
I've tested on Safari for Mac, but once I reuploaded the script with your code, it seems that it's working.

As I see there has left only two problems, one major:
the slider still hides beyond the breakpoint
and minor:
it seems that resized slides beyond the breakpoint are a bit disproportional, they don't fit to a viewport

**Comment by 01Kuzma** [comment]
any thoughts?

**Comment by Tidal-Wave** [comment]
What code are you using for the black preloader? The slider needs to fire a reload once that's done. 

As far as the slides proportion, correct me if I'm wrong but it looks like you switched to using your images as background-image with a cover effect. This happens with set heights and background position set to cover and isn't really a slider issue. I would suggest using actual images in your case as they will always resize proportionately.

**Comment by 01Kuzma** [comment]
Hi,
the body has this class:
```
.loading {
	background: url('../img/ico_loading.gif') no-repeat center center;    
}
```

and once everything is loaded it's removed:

```
( function( $ ) {
	
	// Setup variables
	$window = $(window);
	$slide = $('.homeSlide');
	$body = $('body');
	
    //FadeIn all sections   
	$body.imagesLoaded( function() {
		setTimeout(function() {
		      
		      // Resize sections
		      adjustWindow();
		      
		      // Fade in sections
			  $body.removeClass('loading').addClass('loaded');
			  
		}, 800);
        
        $('.bxslider').bxSlider({
            auto: true,
            easing: 'ease',
            controls: false,
            pager: false 
        });        
        
	});
	
	function adjustWindow(){

	    // Get window size
	    winH = $window.height();
	    winW = $window.width();

	    // Keep minimum height 550
	    if(winH <= 550) {
	        winH = 550;
	    }

	    // Init Skrollr for 768 and up
	    if( winW >= 768) {

	        // Init Skrollr
	        var s = skrollr.init({
	            forceHeight: false
	        });

	        // Resize our slides
	        $slide.height(winH);

	        s.refresh($('.homeSlide'));

	    } else {

	        // Init Skrollr
	        var s = skrollr.init();
	        s.destroy();
	    }
	
		// Check for touch
	   	if(Modernizr.touch) {

			// Init Skrollr
			var s = skrollr.init();
			s.destroy();
	   	}

	}
	
	function initAdjustWindow() {
	    return {
	        match : function() {
	            adjustWindow();
	        },
	        unmatch : function() {
	            adjustWindow();
	        }
	    };
	}

	enquire.register("screen and (min-width : 768px)", initAdjustWindow(), false)
	        .listen(100);
		
} )( jQuery );
```


Regarding proportions: you suggest to remove all this CSS and place images in ul->li elements as it's made in default demo? But in such way how to show them on full viewport(full height and full width)?

Thank you!

**Comment by 01Kuzma** [comment]
bump

**Comment by 01Kuzma** [comment]
bump

**Comment by Tidal-Wave** [comment]
Can you try this:
```
    $body.imagesLoaded( function() {
        setTimeout(function() {

              // Resize sections
              adjustWindow();

              // Fade in sections
              $body.removeClass('loading').addClass('loaded');
              $('.bxslider').bxSlider({
                  auto: true,
                  easing: 'ease',
                  controls: false,
                  pager: false 
              });      
        }, 800);
    });
```

I think the `setTimeout()` is causing the breakpoint issue. 

As far full viewport images vs proportional images, those are two different things. Viewports don't have to be proportional, you can't have it both ways. For example a iPhone held in landscape vs portrait. You have to decide which fits your design needs better and stick with one. If you want it to be full screen there will always be parts of the image that will get cut off as your viewport gets smaller.

**Comment by 01Kuzma** [comment]
Hi!
Just checked it - no results :(
Now the full JS code looks like this:
`( function( $ ) {
	
	// Setup variables
	$window = $(window);
	$slide = $('.homeSlide');
	$body = $('body');
	
    //FadeIn all sections   
	$body.imagesLoaded( function() {
		setTimeout(function() {
		      
		      // Resize sections
		      adjustWindow();
		      
		      // Fade in sections
			  $body.removeClass('loading').addClass('loaded');
			  
		}, 800);
        
        $('.bxslider').bxSlider({
            auto: true,
            easing: 'ease',
            controls: false,
            pager: false 
        });   
        
        $('.logos').bxSlider({
          minSlides: 2,
          maxSlides: 5,
          slideWidth: 250,
          slideMargin: 10,
          moveSlides: 3,
          ticker: true,
          speed: 10000
        });        
        
	});
	
	function adjustWindow(){

	    // Get window size
	    winH = $window.height();
	    winW = $window.width();

	    // Keep minimum height 550
	    if(winH <= 550) {
	        winH = 550;
	    }

	    // Init Skrollr for 768 and up
	    if( winW >= 768) {

	        // Init Skrollr
	        var s = skrollr.init({
	            forceHeight: false
	        });

	        // Resize our slides
	        $slide.height(winH);

	        s.refresh($('.homeSlide'));

	    } else {

	        // Init Skrollr
	        var s = skrollr.init();
	        s.destroy();
	    }
	
		// Check for touch
	   	if(Modernizr.touch) {

			// Init Skrollr
			var s = skrollr.init();
			s.destroy();
	   	}

	}
	
	function initAdjustWindow() {
	    return {
	        match : function() {
	            adjustWindow();
	        },
	        unmatch : function() {
	            adjustWindow();
	        }
	    };
	}

	enquire.register("screen and (min-width : 768px)", initAdjustWindow(), false).listen(100);
		
} )( jQuery );`

**Comment by Tidal-Wave** [comment]
you didn't do it right. Look at my code. I put the bxslider init code IN your `setTimeout()` function. The timeout function is delaying the removal of your loading by 800 ms, but it doesn't stop execution of code AFTER it. So your init code for bxSlider is still getting called before the loader is removed.

**Comment by 01Kuzma** [comment]
Pardon me, I've updated the code above. But it's the same situation :(

**Comment by 01Kuzma** [comment]
Also I've some off-topic question. I've updated this JS code on live web site and added the second slider - logo ticker. It has a problem - the logo's doesn't stop on hover, they continue to move. Also once I hover the logo, the animation start over with a push. Is it a bug?
Please take a look here: http://tedxmru.com/#partners
Thank you!

**Comment by Tidal-Wave** [comment]
Can you try this:

```
( function( $ ) {

    // Setup variables
    $window = $(window);
    $slide = $('.homeSlide');
    $body = $('body');

    //FadeIn all sections   
    $body.imagesLoaded( function() {
        setTimeout(function() {

              // Resize sections
              adjustWindow();

              // Fade in sections
              $body.removeClass('loading').addClass('loaded');

        }, 800);

        $('.bxslider').bxSlider({
            auto: true,
            easing: 'ease',
            controls: false,
            pager: false 
        });   

        $('.logos').bxSlider({
          minSlides: 2,
          maxSlides: 5,
          slideWidth: 250,
          slideMargin: 10,
          moveSlides: 3,
          ticker: true,
          speed: 10000
        });        

    });

    function adjustWindow(){

        // Get window size
        winH = $window.height();
        winW = $window.width();

        // Keep minimum height 550
        if(winH <= 550) {
            winH = 550;
        }

        // Init Skrollr for 768 and up
        if( winW >= 768) {

            // Init Skrollr
            var s = skrollr.init({
                forceHeight: false
            });

            // Resize our slides
            $slide.height(winH);

            s.refresh($('.homeSlide'));

        } else {

            // Init Skrollr
            var s = skrollr.init();
            s.destroy();
           $slide.height(winH);
        }

        // Check for touch
        if(Modernizr.touch) {

            // Init Skrollr
            var s = skrollr.init();
            s.destroy();
        }
```

    }

    function initAdjustWindow() {
        return {
            match : function() {
                adjustWindow();
            },
            unmatch : function() {
                adjustWindow();
            }
        };
    }

    enquire.register("screen and (min-width : 768px)", initAdjustWindow(), false).listen(100);

} )( jQuery );
```

your home slide is not getting a height when below the break point. I made an adjustment to adjustWindow() in the else statement. 

The ticker hover issue is a bug, and the fix is currently in development  branch. You can pull the code for the development version from the repo. It's stable, i just need to finish documentation.

**Comment by Tidal-Wave** [comment]
you will also need to set `tickerHover: true` for pause on hover for the ticker.

**Comment by 01Kuzma** [comment]
Great!
Thank you!
The ticker work just fine!

The main slider also doesn't disappear right now!
Only one last question left, could you suggest me how to make a switch between two slider's modes: switch the main slider to proportional images once the smartphone's breakpoint is reached and keep it as it is now for bigger screen size.

**Comment by Tidal-Wave** [comment]
Thats going to be difficult because you are using background images for the slides, which means that heights need to be explicitly set since there is nothing inside the slides to give them dimensions. This is why I had to make the adjustment in your code to set a height below the breakpoint because none was being set, so the `height: 100% !important;` was doing 100% of 0. You can do some research on intrinsic ratios and see if that will do it for you, basically its a technique of using padding to enforce a ratio on an empty box. it's commonly used for responsive video, but could help you in this situation. This technique would replace your css height code and possibly could replace your `adjustWindow()` code entirely. 

http://alistapart.com/d/creating-intrinsic-ratios-for-video/example2.html
http://www.fredparke.com/blog/css-padding-trick-responsive-intrinsic-ratios
http://daverupert.com/2012/04/uncle-daves-ol-padded-box/

**Comment by 01Kuzma** [comment]
Thank you very much!!!
