### ISSUE TITLE
startSlide based on month

### ISSUE THREAD

**Issue by KlaasvnA** [stevenwanderski/bxslider-4#782]
I'm going to use the bxslider as a calender. And I want the startSlide to be the actual month of the year. So in March my slider will begin with the 3rd slide and in April it wil begin with the 4th slide?

The problem is: I don't have a clue how to pull this off? Any help is very much appreciated!

**Comment by Tidal-Wave** [comment]
The easiest way would be to set the `startSlide` option based on the current month when initializing the slider. Please remember that this option is zero based, so for January you would use 0, February would be 1, etc. 

HTH
