### ISSUE TITLE
Slide content with html id

### ISSUE THREAD

**Issue by Bublafus** [stevenwanderski/bxslider-4#785]
I had problem with event handling on slides other than the first one. Then I have discovered that the problem occurs when I adress certain html element by its **id** (using jQuery).
Since bxslider create a clone of an html entity, the id is duplicated, which is againts the definition of id and forbids addressing the entity (actually I returns the html entity, but the wrong one and I am unable to add on click event listener to the right entity).
The solution is to use html classes instead of ids. I guess other people had the same problem. So is there a cleaner solution? If not, I would recomend to write this limitation somewhere in the bxslider documentation.

Thanks

**Comment by Tidal-Wave** [comment]
The cloning method used is fairly common in sliders to create the infinite loop effect. There are a few ways to get around your issue, using classes, data attributes, disable infinite loop, or use the fade transition which doesn't clone.
