### ISSUE TITLE
Something is wrong with transitions (v4.2.3)

### ISSUE THREAD

**Issue by Gr0m** [stevenwanderski/bxslider-4#786]
If you click on .bx-prev right after initialisation, there will be no transition for the first slide change.

**Comment by Tidal-Wave** [comment]
Please, when submitting an issue around a feature that is generally known to work correctly, provide a simple working example of the issue. As it stands this really doesn't help me to help you. 

Possibly related to https://github.com/stevenwanderski/bxslider-4/issues/758, if so fix is will be available soon, but the code change is available in the issue comments if you need an immediate fix.

**Comment by Gr0m** [comment]
Sorry, I thought it is not only me.

Here's an example - http://public.gromslab.com/bxslider-test/test.html . Try to press Previous button right after the page will finish loading.

**Comment by Tidal-Wave** [comment]
This is the same issue as the one linked above. The fix will be available sometime this week in 4.2.4 as soon as it's done, but the fix for this specific issue is in the comments of #758

**Comment by Tidal-Wave** [comment]
Closing due to duplication, fix incoming.
