### ISSUE TITLE
Slider breaks on mobiles and tablets.

### ISSUE THREAD

**Issue by bondimedical3** [stevenwanderski/bxslider-4#787]
CubeCart have recently put your slider in their shopping cart and I noticed that if you are on a mobile and you move the screen when its doing the transition from the last slide to the first one the whole slider breaks. It doesn't happen the first time but if you move the screen a few times on this transition then it completely stops and nothing works, navigation buttons, touch swipe etc. I have then proceeded to the page http://bxslider.com/examples/multiple-slideshows and have noticed that the same issue is there also for Slideshow 2?

**Comment by Tidal-Wave** [comment]
Can you tell me what version of the slider code you are using?

**Comment by abrookbanks** [comment]
It's v4.1.2

**Comment by abrookbanks** [comment]
I'm wondering why the version we have is so old when we only got it from your website a week or so ago. 
https://github.com/cubecart/v6/blob/master/skins/foundation/js/vendor/jquery.bxslider.min.js

**Comment by Tidal-Wave** [comment]
I was brought into this project recently to take over but unfortunately I wasn't given access to the site. I'm working to resolve this but for now can we start by pulling 4.2.1 tag down from this repo. I would suggest holding off on 4.2.3 and wait till I get 4.2.4 up, there is a transition issue in 4.2.3 (#758 outlines the fix). I hope to have 4.2.4 ready really soon.

**Comment by abrookbanks** [comment]
Excellent. Thank you! Really appreciate this.

**Comment by Tidal-Wave** [comment]
Just as an update, the development branch has the current 4.2.4 WIP. It is stable, I just have a few small items and documentation things to finish before I push to master.

**Comment by abrookbanks** [comment]
Awesome thanks for the update. :)

**Comment by davidsalazar** [comment]
is this fixed?  I'm having some weird issues using css animations.

Run this on mobile safari, and you swipe left and you will see some issues.  a temporary fox to this is to remove css animations and rely on jquery but i don't really want to do that?  Can someone replicate my issue? 
http://liveweave.com/qGyins

**Comment by hombrefeo** [comment]
I too am experiencing this same issue on Safari mobile when swiping left.

**Comment by Tidal-Wave** [comment]
The current development branch should fix this. It's stable, and really just needs the documentation finished but I've been swamped.

**Comment by davidsalazar** [comment]
yup, the development branch fixed it...thank you very much sir.

**Comment by Tidal-Wave** [comment]
👍

**Comment by viktorbijlenga** [comment]
@Tidal-Wave @stevenwanderski Can we mark this as solved?
