### ISSUE TITLE
Custom Pager & AngularJS

### ISSUE THREAD

**Issue by georgesofroniou** [stevenwanderski/bxslider-4#794]
I have integrated bxSlider into my website having to use a directive in order for this to be loaded.
What I would also like to achieve is a custom Pager where I can create tooltips on hover of the pager.

My slides are created using ng-repeat getting the data from a JSON file. I then will be required to use a similar process for the Custom Pager. I have set the `pagerCustom` option to `#bx-pager` and the code below is this custom pager:

```html
<!-- bxSlider Initiated -->

<div class="content-results bxslider" 
bx-slider="mode: 'horizontal', pager: true, pagerCustom: '#bx-pager', nextSelector: '#next', prevSelector: '#prev', nextText: '<i class=\'fa fa-chevron-right\'></i>', prevText: '<i class=\'fa fa-chevron-left\'></i>', minSlides: 1, maxSlides:1, infiniteLoop: true, adaptiveHeight: true, hideControlOnEnd: false">
    ....Slide Content....
</div>

<!-- END bxSlider Initiated -->


<!-- Custom bxSlider Pager -->
<div class="bx-controls">
	<div class="bx-pager" ng-repeat="item in employees">
		<div class="bx-pager-item">
			<a href data-slide-index="{{item.cat_id}}" class="bx-pager-link">{{item.cat_id}}</a>
		</div>
	</div>
</div>
<!-- END Custom bxSlider Pager -->
```

```json
[
  {
    "category": "Technology",
    "shortname": "tech",
    "icon": "fa-desktop",
    "cat_id": 1,
    "cards": [...]
  },
  {
    "category": "Motors",
    "shortname": "mot",
    "icon": "fa-car",
    "cat_id": 2,
    "cards": [...]
  },
  {
    "category": "Football",
    "shortname": "foot",
    "icon": "fa-futbol-o",
    "cat_id": 3,
    "cards": [...]
  },
  {
    "category": "Law",
    "shortname": "law",
    "icon": "fa-gavel",
    "cat_id": 4,
    "cards": [...]
  }
]
```

My custom Pager displays fine, however there is no functionality to it? I cannot change the slides on click of the pager icons. I was just wondering whether there was any additional code that needs to be implemented? Please let me know if you'd require any other code, I have attached relevant code from my **HTML** & **JSON** files.

Many thanks.

**Comment by priyesh-infobeans** [comment]
pppp`ppppppppppppp`
