### ISSUE TITLE
slider height isn't defined until window is resized

### ISSUE THREAD

**Issue by ChenRoth** [stevenwanderski/bxslider-4#797]
hey

I'm using a slider of the same configuration on two separate occasions:

1) slider is rendered in a normal page flow, it looks fine
2) slider is rendered into a bootstrap modal box

when the slider is rendered in the modal box, its height is initially 0 and only when I resize the window, the height auto-adjusts and the slider is visible

I'm using the default options, and the only way the slider corrects itself is when "responsive" is set to true (by default); when inspecting the source code, I can tell a responsive slider binds a resize event which probably auto-adjusts the slider

Evidently, something is missing in the initialization that later on is compensated by resizing the window
can anyone help?

**Comment by Tidal-Wave** [comment]
Try calling reloadSlider after you call your modal, currently the slider can not determine its height while hidden.

**Comment by ChenRoth** [comment]
reloading the slider works

thanks

**Comment by Tidal-Wave** [comment]
:+1:
