### ISSUE TITLE
slider in tab doesn't show images unless window is resized or by direct link

### ISSUE THREAD

**Issue by zuhloobie** [stevenwanderski/bxslider-4#804]
I have a page with a subnavigation menu that shows or hides div (as "tabs"). Each tab has a unique id such as "subDivTab1", "subDivTab2", and so on. Clicking on subDivTab1, hides any current tab and shows Tab 1, and so on. Problem is that the slider images aren't appearing in certain conditions...

WHAT DOESN'T WORK
Once landing on the page and using the subnavigation menu, clicking a tab link, which hides current open tab and shows the one I want without reloading the page, no images show in the slider except for the pager. And the pager does show it cycling through each image - there just is no images (or height).

WHAT DOES WORK
(1) If I resize the window, the slider images finally appear. 
(2) If I visit the tab via direct link (like: www.example.com/page.php#subDivTab5) - the images appear.
(3) If I break the show/hide tab system so that all tabs appear at the same time, the images appear. Obviously, I don't want to show all tabs at once - just telling you another circumstance.

How do I get the images to appear when using the internal show/hide div tab system?

Here is the bxslider script:
`
  		$(document).ready(function() {
			$('.solutionSlider').bxSlider({
				mode: 'horizontal', //horizontal vertical fade
  				speed: 750, //transition duration
				infiniteLoop: true,
				captions: false,
				video: false,
				responsive: true,
				pager: true,
				pagerType: 'full', //full or short
				controls: false,
				auto: true,
				pause: 3500,
				autostart: true,
				autoHover: true,
				autoDelay: 2500,
				onSliderLoad: function(){
        			$('.solutionContainer').css('visibility', 'visible').hide().fadeIn(2000);
      			}
			});
		});
`

Here is a fiddle that shows my subnavigation menu show/hide tab system: http://jsfiddle.net/zuhloobie/m1fua9jp/

Can someone help?

**Comment by zuhloobie** [comment]
I solved it by adding this to the container holding the slider:

`.tabSlideContainer ul li {width:650px !important; height:276px !important;}`

Not sure if best solution - would rather have it redraw once the tab is shown, but not sure how likely I'll get an answer here. If someone else has a better idea, please tell me.

**Comment by Tidal-Wave** [comment]
Generally speaking when people use the slider in a tab that is hidden it's necessary to call `reloadSlider()` on tab load so that the slider redraws. It's unable to determine its dimensions when hidden, this is why it works on resize or if you disable the tabs. 

HTH.

**Comment by zuhloobie** [comment]
Do you possibly have an example of how to implement `reloadSlider()` on tab load? I tried and failed :(

**Comment by Tidal-Wave** [comment]
I had to rearrange a little of your example but here you go: http://jsfiddle.net/ewafford/u4rLxtdy/1/

Mostly I just moved your tab code outside of the separate Immediately-Invoked Function Expression (IIFE) because it was out of scope with initializing the slider under the `document.ready` code, and locks in the jQuery Object returned from the selector that is used to find and reload the slider. The Immediately-Invoked Function Expression (as the name implies), fires off immediately, even before `document.ready`.

It's a quick and a little hacky way of doing it, but I was just basing it off of your fiddle real quick. 

The important piece is ` $(containerSelector).find('.bxslider').reloadSlider();`

HTH

**Comment by Tidal-Wave** [comment]
Another, and probably more efficient way, is to use something like `.one()` on the tab link targeting the click event that way the reload is only called once, there's no need to call it every time.  This would be separate from your `.click()` call.  Like I said, the above is just a quick example.

**Comment by zuhloobie** [comment]
I really appreciate your input - swamped with other things at the moment, but I will look it over the next day or so and get back to you if I have any issues. Thanks again!
