### ISSUE TITLE
Cannot read property 'msie' of undefined

### ISSUE THREAD

**Issue by ElliottRoche** [stevenwanderski/bxslider-4#810]
This error pops up after every slide change (I'm using fade mode).

It looks like it comes from this portion of the code:
```javacsript 
function setChildrenFade(){
			// fade out any other child besides the current
			$children.not(':eq('+currentSlide+')').fadeTo(options.speed, 0).css('zIndex', 98);
			// fade in the current slide
			$children.eq(currentSlide).css('zIndex', 99).fadeTo(options.speed, 1, function(){
				isWorking = false;
				// ie fade fix
				if(jQuery.browser.msie){
					$children.eq(currentSlide).get(0).style.removeAttribute('filter');
				}
				// perform the callback function
				options.onAfterSlide(currentSlide, $children.length, $children.eq(currentSlide));
			});
		};
```

.browser() was deprecated in jQuery 1.9 and no longer works. As far as I know, there's been no native replacement and most fixes suggest implementing feature detection rather than browser detection.

**Comment by Tidal-Wave** [comment]
`setChildrenFade()` is not a function of the current bxSlider codebase.. I even looked all the way down to 4.1.2 from before I was added to the project.  Not sure what your asking for..

**Comment by ElliottRoche** [comment]
I installed bxSlider using bower several days ago and now that I look at what was installed it shows v3.0 and a copyright from 2011. I'd run ```bower install bxslider``` to get the package installed. Is there another version that uses bower that I may have missed?

**Comment by ElliottRoche** [comment]
I believe I found it. I'll close the issue.

**Comment by Tidal-Wave** [comment]
:+1:
