### ISSUE TITLE
Susy grid

### ISSUE THREAD

**Issue by CWdesigned** [stevenwanderski/bxslider-4#813]
I am using the susy grid system for easy responsiveness. However when the susy grid span changes the slider stops working. I lack experience to find out what's wrong here. I used a temp fix that reloads the page from cache when window width is changed. I guess this is a real bad solution though.

**Comment by Tidal-Wave** [comment]
Do you have an example page I can see in order to help assess the issue?

**Comment by CWdesigned** [comment]
http://vanhetvossenbosch.nl/zamenwerk/example.htm
I removed the refresh script so it now stops working when resizing from big to mobile size or vica versa.

**Comment by Tidal-Wave** [comment]
Ahh, you are using the 4.1.2 version, which had issues with window resize. Please try either the current master branch, or if you are comfortable please try the development branch. The development branch is stable and is only lacking some documentation. We are currently having people beta test it.

**Comment by Tidal-Wave** [comment]
Beta Development Branch: https://github.com/stevenwanderski/bxslider-4/tree/development
Current Master Branch: https://github.com/stevenwanderski/bxslider-4/tree/master

**Comment by CWdesigned** [comment]
Thank you!!! I just tryed the master branch and all is working as intended. Time to get rid of that amateur refresh script!

**Comment by Tidal-Wave** [comment]
:+1:
