### ISSUE TITLE
.bx-viewport not calculating height/Not opening

### ISSUE THREAD

**Issue by beachpebble** [stevenwanderski/bxslider-4#816]
I have a lot of sliders on one page, perhaps that is contributing to the problem, but firebug is showing no errors in the script.

I have installed an image slider on a popup window and everything is there and looks great, except the viewport is not opening. If I declare a height for the viewport or inspect it in my web-browser, the viewport re-calculates and opens up. When I declare a height for the viewport it opens it up but messes the images.

Is there a solution for this problem?

**Comment by Tidal-Wave** [comment]
You will need to use `reloadSlider()` once the modal is called. If a slider is not visible it cannot currently determine its height.
