### ISSUE TITLE
prevent horizontal scroll when vertical touch swipe delta (page) is greater

### ISSUE THREAD

**Issue by jmp909** [stevenwanderski/bxslider-4#824]
Hi,

would it be possible to implement a delta threshold so that when a user swipes down on the slider to scroll the page, it ignores horizontal movement (and vice versa)

what I find is when they scroll down, the slider is moving back and forth a bit horizontally, since a user cannot make a perfect 90 degree swipe! . i dont want to set a swipeThreshold specifically. even setting this higher, it does not stop the slides moving

the other option would be to stop the slides moving around until the threshold is met.

thanks
J

**Comment by Tidal-Wave** [comment]
This can be circumvented currently by setting `oneToOneTouch` to `false`, but I do plan on improving touch soon. Thanks for the report.

**Comment by jmp909** [comment]
ah thanks. I had missed that. or rather not realised that created the horizontal "snap" feature which was what i really wanted anyway and thus also avoids the issue.
thanksj

Date: Mon, 1 Jun 2015 18:04:16 -0700
