### ISSUE TITLE
bxslider options - half work

### ISSUE THREAD

**Issue by favocarv** [stevenwanderski/bxslider-4#831]
Hi there,

I included the code for bxslider for a website that's running with Wordpress.
The images show and mode: fade also works.

However, auto is not making the slide work automatic, meaning one has to click on the buttons to make it go to the other images; the pagers don't disappear even when setting them to false, they still show; the autoControls don't show even though they are set to true; and the speed option also doesn't work.

So it's like the slide is half working, half not.

The console doesn't show any errors, and I'm using v4.2.4.
When I did a test it worked fine, when I implemented to the website where I need it, those options don't seem to be read.

Anyone knows of conflicts with Wordpress or any other possible issue/things I should look at/change to make it work?

Thanks in advance.

**Comment by Tidal-Wave** [comment]
I haven't witnessed anything like this at the moment, but if you can provide more code I would be happy to look.

**Comment by favocarv** [comment]
Thanks for your prompt response Tidal-Wave.

Apparently it was conflicting with an old js file we had on the website. The senior developer found it and fixed it already. I wasn't given details of what exactly it was, but if they tell me I'll post here later so if anyone ever encounters the same problem there is a reference.

Basically, it wasn't taking boolean values from the options.

Again, thanks for your attention.

**Comment by Tidal-Wave** [comment]
Glad to hear it. I'm gonna close this, but feel free to report back if you get more info.
