### ISSUE TITLE
Autoslide Continues When YoutTube Video Started

### ISSUE THREAD

**Issue by absynthe-minded** [stevenwanderski/bxslider-4#84]
If you click on a YouTube video in the carousel, it doesn't stop the autoslide. This happens when you use the YouTube iframe.

This is because of the origination issue.

There is a solution here: http://stackoverflow.com/questions/7443578/youtube-iframe-api-how-do-i-control-a-iframe-player-thats-already-in-the-html/7513356#7513356

It would be nice to have this included.

**Comment by jdmagic21** [comment]
@stevenwanderski You can also set autoHover to true.
