### ISSUE TITLE
Vertical carousel minSlides not working in current version

### ISSUE THREAD

**Issue by andrews05** [stevenwanderski/bxslider-4#840]
Trying to do a vertical carousel but it's not working as it shows on the examples page. The slider height is not restricted by the minSlides as set in the options. Seems it works properly in v4.1.2 as is used on the examples page but not the current v4.2.4.

**Comment by Tidal-Wave** [comment]
Thanks for the report, a fix will be out some time today.

**Comment by Tidal-Wave** [comment]
Fixed in 4.2.5

**Comment by andrews05** [comment]
Hey thanks heaps, really appreciate all the work you're putting into this :)
