### ISSUE TITLE
Infinite loop sliders show the clone slide on initialisation

### ISSUE THREAD

**Issue by andrews05** [stevenwanderski/bxslider-4#843]
As can be seen in Slideshow 2 [here](http://bxslider.com/examples/multiple-slideshows), the slider is initially showing slide -1 rather than slide 0. The internal state seems to be correct though and it will be fixed if redrawSlider() is called.

**Comment by Tidal-Wave** [comment]
The website isn't controlled by me and isn't using the latest versions. This issue should be corrected, are you experiencing it with 4.2.5?

**Comment by andrews05** [comment]
Yes, I'm experiencing the same behaviour with 4.2.5. Just linked to that as an example.

**Comment by andrews05** [comment]
This turned out to be some sort of CSS issue caused by me overriding the viewport height. Not sure why it was causing the problem but I resolved it now. Sorry about that.
