### ISSUE TITLE
Image doesn't responsive in high resolution screen

### ISSUE THREAD

**Issue by benliu723** [stevenwanderski/bxslider-4#852]
Dear all,

I'm using bxslider in my project.

My working Environment: 
bxslider - 4.1.2
jquery - 2.1.3
screen resolution: 3560px * 1440px

It works perfect that the image is fully responsive with nice proportion in screen with low resolution(like 1366px * 768px). But the image width doesn't responsive in my screen with 1366px * 1440px resolution.

I searched a lot and haven't found the solution. Really need your help.

Looking forward for your reply and have a nice day.

**Comment by benliu723** [comment]
Is there anyone who can help me? This is really an agent bug for me.

**Comment by Tidal-Wave** [comment]
First off you are using an older version, but that shouldn't matter. 

The css isn't designed to implement a cover technique out of the box, so if the slider gets larger then the picture it's not gonna grow with it. Some slight modifications to the css could resolve this easily though. 

If you'd like more help, demo code is required. Also note that this is a bug report system, and general implementation issues would probably get answered faster on stackoverflow. 

That being said if you want to make a simple example for me to see, with code, I can attempt to point you in the right direction.

**Comment by benliu723** [comment]
Thanks for your reply and it really resolved my problem by slight modifications to the css.

Here is the code:
.bx-wrapper img {
         width: 100%;
}
