### ISSUE TITLE
bxSlider Not Loading Uncaught TypeError: Cannot read property 'each' of null

### ISSUE THREAD

**Issue by jasperf** [stevenwanderski/bxslider-4#910]
At http://goo.gl/R1vX3g I am working on a site. The menu is no longer loading due to implementation of megamenu, but the issue I want to talk here is the bxSlider implementation. Initially the bxSlider file was not added properly so I added it. With and without capital S to be sure and all located here: `skin/frontend/rwd/default/js/files`

Now I still get this error 
`Uncaught TypeError: Cannot read property 'each' of null(anonymous function) @ cust.js:4`

The script loaded has:
```
 $('.slider-container #slider').each(function() {
    var _this = $(this).bxSlider({
        slideWidth: 300,
        minSlides: 2,
        maxSlides: 5,
        moveSlides: 1,
        slideMargin: 10,
        auto: false,
        speed: 2000,
        controls:false,
        pager:false,
        pause: 0
    });
    _this.mouseenter(function() {   
         _this.startAuto();      
     }).mouseleave(function() {   
         _this.stopAuto();
    });
});
```
Any ideas how I can fix this?

**Comment by viktorbijlenga** [comment]
@jasperf Did you ever solve this?

**Comment by jasperf** [comment]
@viktorbijlenga been ages.  I think the issue here basically was a conflict with another JS implementation. Sometimes scripts are not ended properly or you need jQuery to load in noConflict mode for example. [Cycle](http://plugins.jquery.com/cycle/) setup seems to to be implemented now. Best of luck!

**Comment by viktorbijlenga** [comment]
@jasperf Great! I’m digging trough old issues, to be able to close things that's solved by now.
