### ISSUE TITLE
Double Click on Next not transition correctly

### ISSUE THREAD

**Issue by seltix5** [stevenwanderski/bxslider-4#951]
hi,

wen you double click on the NEXT or PREV arrow the the slider execute the command 2 times. the problems :
- the second transition doesnt exist (the image just changes instantaneously)
- the pager only change one time

in the demo on the bxSlider side this doesnt append.

thank you.

example : http://codepen.io/seltix/pen/QyLNKJ

**Comment by sekmenhuseyin** [comment]
this is fixed now, thank you very much for your help
