### ISSUE TITLE
adaptiveHeight not working when using Javascript Public method

### ISSUE THREAD

**Issue by jsette** [stevenwanderski/bxslider-4#96]
Hi, I am using this for a product slider in my project. 

I have the following code:
            $(document).ready(function(){
                $('.bxslider').bxSlider({
                    adaptiveHeight: true ,
                    pagerCustom: '#product_thumbs',
                    infiniteLoop: false,
                    hideControlOnEnd: true 
                });
            });        

```
        function go_to_slide(slide_index) {
            var slider = $('.bxslider').bxSlider(); 
            slider.goToSlide(slide_index);
        }
```

I call go_to_slide when a user select a different product colour. e.g. If they select 'Blue', then I go to the Blue image on the slider. The go to action works fine except I have dynamic image sizes with different height.

When calling this function, the new slide display they same height as the slide before that. Hence it's not executing adaptiveHeight.

Any clues on this issue?

**Comment by brunorios1** [comment]
@stevenwanderski Can't access the fiddle, do you remember what is the solution? Thanks!
